### ISSUE TITLE
Fix documentation for presets/sortable

### ISSUE THREAD

**Issue by CaninoDev** [clauderic/dnd-kit#101]
In the documentation for [sortable preset](https://docs.dndkit.com/presets/sortable) the statement 

`In this example, we'll use the ref forwarding pattern to avoid introducing wrapper nodes:` 

doesn't actually reflect the example provided. Instead the example reflects the inverse of the statement. In another words, the example provided utilizes wrapper nodes.

**Comment by clauderic** [comment]
Did you look at the other tabs that show the code using the ref forwarding pattern?

<img width="789" alt="Screen Shot 2021-02-24 at 10 10 06 AM" src="https://user-images.githubusercontent.com/1416436/109021052-85f52f00-7688-11eb-9e4f-029e47a23773.png">

<img width="789" alt="Screen Shot 2021-02-24 at 10 10 01 AM" src="https://user-images.githubusercontent.com/1416436/109021062-87bef280-7688-11eb-8a69-7d626dc5829f.png">

**Comment by CaninoDev** [comment]
Maybe I misunderstood.. In `<App />`, `<SortableItem />` and `<Item />` were both used.
