### ISSUE TITLE
Ability to sort by index

### ISSUE THREAD

**Issue by bit314** [clauderic/dnd-kit#1012]
https://codesandbox.io/s/nervous-gates-fvzves?file=/src/App.js

I wanted to find out if it's even possible to sort lists by index.

I initially have a project, although there is an id in the objects, but it can be repeated or it does not exist. Therefore, I am looking for an option on how to sort lists

**Comment by Akash187** [comment]
Hi @bit314,
Yes, you can sort lists by index but it needs to be a string of indexes and the keys must be a unique random id.
I have created a working example from your code fork. 
You can check it here https://codesandbox.io/s/hardcore-hopper-zbl0xv?file=/src/App.js
Also, I have installed some packages and updated old packages.

**Comment by bit314** [comment]
@Akash187, Thank you, that's what you need, otherwise I had to sort through the arrays and add id indicators
