### ISSUE TITLE
Disable default Keyboard Events

### ISSUE THREAD

**Issue by iamterryclark** [clauderic/dnd-kit#1044]
As the title suggests,

Is there a way to completely disable keyboard based events from dnd kit?

I really do not require ARIA based features for my particular desktop application and I have other key bindings attached to space bar.

Currently `space` will make my list of elements scroll down and `enter` will set a highlight around my element. I'd prefer to completely disable the keyboard interactions on dnd kit.

I'm trying to disable the defaults by changing these values but still the elements will highlight on enter

![image](https://user-images.githubusercontent.com/8614976/220690277-34433c18-f994-43a4-b1f5-e5b83186d7de.png)

```js
const keyboardSensor = useSensor(KeyboardSensor, {
    keyboardCodes: {
        start: [],
        cancel: [],
        end: []
    },
});
```
Many thanks in advance

**Comment by clauderic** [comment]
You can completely opt out of the `KeyboardSensor` yes.

```tsx
import {PointerSensor, useSensor, useSensors} from '@dnd-kit/core';

const sensors = useSensors(
  useSensor(PointerSensor),
);

return (
  <DndContext sensors={sensors}>
    ...
```
