### ISSUE TITLE
fix your documentation PLS

### ISSUE THREAD

**Issue by gevhambarzumyan93** [clauderic/dnd-kit#1050]
the main idea of examples is to give users working code examples and not just show them "LOOK we have this or we have that".
why the hell do I need your storybook if everything inside of it I need to recreate myself or even worse should pull and run on my machine? what? you didn't hear about code sandbox?

**Comment by bricejar** [comment]
Hi @gevhambarzumyan93 . I just came across your comment. 

Do you realize this work is open-source and free ? Therefore you are not entitled to anything about it. Your comment is rude and disrespectful. If you think you can improve the documentation, then you can offer to contribute to the project, that would be helfpul and constructive. 
There aren't that many good drag and drop libraries out there, please realize how generous the author is to share their expertise and high quality code, free of charge. Thank you. 

PS :  I am not related to the project. Just sharing my opinion.

**Comment by gevhambarzumyan93** [comment]
My friend this have nothing to do with entitlement. Main reason why there
are issue section to describe what problem did you have with package. And
for me it was their documentation.and what part of it disrespectful I even
add pls at the end

**Comment by gevhambarzumyan93** [comment]
But maybe you are right. Maybe I was to frustrated at the moment that’s why
it sound that way

**Comment by gevhambarzumyan93** [comment]
I
