### ISSUE TITLE
DragOverlay dropAnimation only animates / applies certain css properties

### ISSUE THREAD

**Issue by oisinlavery** [clauderic/dnd-kit#1061]
I'm trying to make a DragOverlay item animate seamlessly back into place once dropped. 

I'm running into trouble with the DropAnimation, it seems that only certain css properties will animate - eg. background and border
While other properties will not animate - eg. boxShadow, borderRadius

[CodeSandbox example](https://codesandbox.io/s/kind-liskov-rw66pe?file=/src/components/SortableList/components/SortableOverlay/SortableOverlay.tsx)

**Comment by clauderic** [comment]
You can specify custom keyframes to animate those properties, or define other `sideEffects` you would like to perform:

https://github.com/clauderic/dnd-kit/blob/5c58f0fe5d19b5aaa5cf93572f3435f4a0a6e54f/stories/3%20-%20Examples/Tree/SortableTree.tsx#L75-L88
