### ISSUE TITLE
Is there any way we can look at the code behind the Stories?

### ISSUE THREAD

**Issue by vlad-solomon** [clauderic/dnd-kit#1062]
The documentation on the site is ok, but it would be much easier if we would have access to the code behind the examples. Is there any way we can study those? Have I missed them? 

Being a newcomer to this library I think I would get the hang of things easier if the working examples would be accompanied by the code.

Sorry if I missed some really obvious thing, but I think I looked everywhere. Thank you! 🤗

**Comment by moxxuk** [comment]
You missed a really obvious thing ;)

https://github.com/clauderic/dnd-kit/tree/master/stories

**Comment by vlad-solomon** [comment]
Oh my god finally. For some reason I looked at the ```.storybook``` folder and thought that was it. Thank you

**Comment by moxxuk** [comment]
Happy to help :) And if it helps, I did the same thing when I first started using this!

**Comment by vlad-solomon** [comment]
Hahaha, glad I wasn't the only one 😎
