### ISSUE TITLE
DragOverlay animates back to the drag start position when dropped

### ISSUE THREAD

**Issue by patrickliechty** [clauderic/dnd-kit#1075]
I am using a <DragOverlay>.  I drag the item to a new droppable area and do a mouse up.  The DragOverlay animates back to the drag start position.  I want it to not animate when I drop.  What do I need to do?  onDragEnd I set dragInfo to null.  Should that stop the animation?

BTW, this is an awesome library.  I tried 2 other React dnd libs and they were difficult to use.  I couldn't use them for my circumstance.  Congrats on a great lib.

Code:

` {createPortal(
          <DragOverlay
            style={{
              borderLeft: `4px solid${colors.blue10}`,
              boxShadow: '0 0 5px rgb(68 68 68 / 0.6)',
              background: 'white',
            }}
          >
            {dragInfo && (
              <PersonDisplay
                person={dragInfo.person}
                t={t}
                key={dragInfo?.person?.id}
                record={dragInfo.record}
                rightIcon={SocialFaceMad}
              />
            )}
          </DragOverlay>,
          document.body
        )}`

**Comment by patrickliechty** [comment]
I found the dropAnimation prop and set it to null.  That worked!

**Comment by bva999** [comment]
I have the same problem .  dropAnimation prop set  to null helps, but it turns animation off.

**Comment by Saddage** [comment]
I think that turning off something that doesn't work might not be the best solution. Kind request to @clauderic to reopen. I experience the same issue.

The thing I noticed is that the issue appears when I use `apollo` cache as the source of the data. I made an experiment where I simply throw whatever `apollo` fetches and caches into `React` state, and the issue was gone. However, this is also not a solution, since it introduces two sources of data, instead of one.

**Comment by zhouzi** [comment]
I am facing a similar issue.

In certain scenarios dnd-kit disables the drop animation as expected but not in other scenarios. I feel like there's some kind of logic trying to figure out whether the animation makes sense or not but can't find documentation about it.

**Comment by odo48** [comment]
> I am facing a similar issue.
> 
> In certain scenarios dnd-kit disables the drop animation as expected but not in other scenarios. I feel like there's some kind of logic trying to figure out whether the animation makes sense or not but can't find documentation about it.

Having the same issue, I couldn't find how to fix it yet
