### ISSUE TITLE
Prop `aria-describedby` did not match. server: "dnddescribedby-0" client: "dnddescribedby-1"

### ISSUE THREAD

**Issue by paulwongx** [clauderic/dnd-kit#1103]
This warning appears in the console whenever I load the page. I'm using Next13 app dir, react server components. Is there a common "gotcha" when using RSC to make sure server and client renders the same? I have "use client" on all my pages. Wondering if it's standard procedure to NEED to do the `isMounted` `useEffect` trick so that you return null if it's not mounted yet

**Comment by paulwongx** [comment]
Same issue as https://github.com/clauderic/dnd-kit/issues/926. My solution is in that post. Essentially...
```js
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  if (!isMounted) return null;
``` 
for a quick fix and library needs to use `useId()` (I think) for library fix

**Comment by hqasmei** [comment]
Hi is this the only way to solve this? Any updates with Next.js 14?

**Comment by paulwongx** [comment]
> Hi is this the only way to solve this? Any updates with Next.js 14?

@hqasmei It's been quite a while since I encounted this issue. Specific to this library, I believe it was still needed. Just put it in a hook and use it in your component. There are a lot of live issues with animations and server components even with other packages like framer motion. Fundamentally... it wasn't built with RSC in mind when it was built. But at the same time, I haven't used the library in a long time so open to be corrected.
