### ISSUE TITLE
Missing id prop for Droppable in Quick Start guide

### ISSUE THREAD

**Issue by sampl** [clauderic/dnd-kit#112]
The ["Pushing things a bit further" example](https://docs.dndkit.com/introduction/getting-started#pushing-things-a-bit-further) in the Quick Start implies that you can reuse the `Droppable.jsx` file from the [previous example](https://docs.dndkit.com/introduction/getting-started#assembling-all-the-pieces). However that file doesn't work because it has a hard-coded id of "droppable".

Instead, I think there should be a slightly different `Droppable.jsx` that uses the `id` being passed to it like so:

### Previous example from "Assembling all the pieces"

```jsx
import {useDroppable} from '@dnd-kit/core';

export function Droppable(props) {
  const {isOver, setNodeRef} = useDroppable({
    id: 'droppable',
  });
  const style = {
    color: isOver ? 'green' : undefined,
  };
  
  
  return (
    <div ref={setNodeRef} style={style}>
      {props.children}
    </div>
  );
}
```

### Add this version to "Pushing things a bit further"

```jsx
import {useDroppable} from '@dnd-kit/core';

export function Droppable(props) {
  const {isOver, setNodeRef} = useDroppable({
    id: props.id,
  });
  const style = {
    color: isOver ? 'green' : undefined,
  };
  
  
  return (
    <div ref={setNodeRef} style={style}>
      {props.children}
    </div>
  );
}
```

Not the end of the world, just erring on the side of clarity :)

**Comment by clauderic** [comment]
Updated, thanks for pointing this out!
