### ISSUE TITLE
Question, how i can render a different element before the drop?

### ISSUE THREAD

**Issue by mantegnous** [clauderic/dnd-kit#1120]
I'm moving an item from one column to another,
I would like to see a different item in the other column when I move the card closer to it,

for example, I would like to see a +. instead of the card I'm moving

i have only to see the card y in the drag overlay and once I drop it in the other column

do i need to create something custom, like creating fake elements in the various arrays (by current index, position) or is there any way to do this?

![image](https://user-images.githubusercontent.com/37369193/235856855-3af397af-a81e-420b-a86b-ee09807e39ca.png)

**Comment by uptonking** [comment]
- you can render any valid React component as `DragOverlay` `children`
- just pass drag data like activeId/childContent to the `children` component

**Comment by mantegnous** [comment]
@uptonking not this.. i dont need to change the drag overlay componente when i drag, i want see the selected element when im dragging, so onDragOver, but, when im near to drop it, i dont want to see the same component in the future position, but another, this until i relase and the drop is end.

**Comment by mantegnous** [comment]
![image](https://user-images.githubusercontent.com/37369193/236187718-5f9519df-a8d9-4775-89be-a3dc02b79083.jpg)
