### ISSUE TITLE
closestCenter imported incorrectly in docs

### ISSUE THREAD

**Issue by sampl** [clauderic/dnd-kit#113]
[The "Collision detection algorithm" docs](https://docs.dndkit.com/presets/sortable#collision-detection-algorithm) show `closestCenter` being imported from `@dnd-kit/sortable`:

<img width="760" alt="Screen Shot 2021-03-02 at 10 04 38 AM" src="https://user-images.githubusercontent.com/231851/109668025-bd5b5400-7b3e-11eb-8ca2-b6f77617a666.png">

But that causes an import error:

<img width="449" alt="Screen Shot 2021-03-02 at 10 05 22 AM" src="https://user-images.githubusercontent.com/231851/109668107-d2d07e00-7b3e-11eb-8bc8-d2f23ba8e93c.png">

It should probably be imported from `@dnd-kit/core` instead like it is [at the top of the same page](https://docs.dndkit.com/presets/sortable#overview):

<img width="781" alt="Screen Shot 2021-03-02 at 10 05 55 AM" src="https://user-images.githubusercontent.com/231851/109668198-eb409880-7b3e-11eb-825d-a64c08f1b4ef.png">

**Comment by clauderic** [comment]
Updated, thanks!
