### ISSUE TITLE
Variable height items stretching and compressing in sortable list

### ISSUE THREAD

**Issue by reinvanimschoot** [clauderic/dnd-kit#1138]
Hi guys

We just switched to this package from react-dnd and while initially it seemed great, we ran into a weird issue when using the sortable context/hook.

![2023-05-25 17 12 52](https://github.com/clauderic/dnd-kit/assets/35171567/622e6559-85bb-4c58-a237-828faf5d71cb)

It seems that when having variable height items in a list, the dragged items shrinks or stretches depending on the item it hovers over.

My code is the following:

List:
```tsx
    <DndContext>
      <SortableContext items={parts} strategy={verticalListSortingStrategy}>
        <div className="space-y-4">
          {parts.map((p) => (
            <PartItem item={p} key={p.slug} bookSlug={bookSlug} />
          ))}
          <FormCreate bookSlug={bookSlug} />
        </div>
      </SortableContext>
    </DndContext>
```

Item:
```tsx
export function PartItem(props) {
  const { item } = props;

  const { attributes, listeners, setNodeRef, setActivatorNodeRef, transform, transition } =
    useSortable({
      id: item.id,
    });

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
  };

  return (
    <div ref={setNodeRef} style={style} {...attributes}>
      <div className={'relative flex justify-between flex-1 rounded-md shadow-sm cursor-pointer'}>
        <div className="flex items-center border pl-2 flex-grow rounded-none rounded-l-md">
          <div
            {...listeners}
            ref={setActivatorNodeRef}
            className="cursor-pointer mr-1 p-0.5 hover:bg-zinc-100 hover:rounded">
            <DragIndicator className="w-4 h-4 text-gray-500 " />
          </div>

          <h4 className="flex items-center pl-1 w-full font-medium text-sm text-gray-700">
            {item.title}
          </h4>
        </div>

        <OptionsMenu part={item} />
      </div>

      <div className="pl-10 mt-2">
        <NestedPartList items={item.children} />
      </div>
    </div>
  );
}
```

I tried adding a specific height but that also didn't work. Any help would be greatly appreciated!

**Comment by Dace** [comment]
@reinvanimschoot I was having a similar issue and this helped to solve it - https://github.com/clauderic/dnd-kit/issues/117

> The items are stretched because you're using `CSS.Transform.toString()`, use `CSS.Translate.toString()` if you don't want to have the scale transformation applied.

Hope this helps!

**Comment by reinvanimschoot** [comment]
@Dace You are a life savior! Thank you very much!

**Comment by ticmaidev** [comment]
disabling this prop also solved my issue:

```tsx
<DragOverlay adjustScale>
```

**Comment by ninjarogue** [comment]
I am also facing the same issue with `@dnd-kit/core 6.0.8`

**Comment by plrthink** [comment]
how to apply adjustScale to the `useSortable`?
