### ISSUE TITLE
Sortable items jump in flexbox container

### ISSUE THREAD

**Issue by sampl** [clauderic/dnd-kit#115]
https://www.loom.com/share/371fae83e98046ed98d4fffe277d27a2

From what I can tell, any items that should change "columns" during drag have a correct `y` position, but keep their old `x` position until the drag ends.

Parent div styles:

```css
  display: flex;
  flex-wrap: wrap;
  flex-direction: column;
  align-content: flex-start;
  background: #eee;
  padding: .5rem;
  height: 100%;
  max-height: 30rem;
```

I would be using grid layout, but [it doesn't seem to support this layout](https://stackoverflow.com/a/44092580/1061063). 

(FWIW I got here via [this issue from another lib](https://github.com/atlassian/react-beautiful-dnd/issues/316)).

Not sure if this is supported by dnd-kit, but I'd love it if it was. I'm happy to make a code sandbox if that would be helpful!

**Comment by clauderic** [comment]
What [sorting strategy](https://docs.dndkit.com/presets/sortable#sorting-strategies) are you using? Do share a codesandbox if you can.

**Comment by sampl** [comment]
@clauderic was just about to comment--I worked on a sandbox but was unable to reproduce

https://codesandbox.io/s/dndkit-sortable-image-grid-forked-yt4rv

Sorry for the bother--will circle back if I find something later

**Comment by sampl** [comment]
Ok, looks like it happens with `verticalListSortingStrategy` but not `rectSortingStrategy`. Thanks for the tip, I've got at least a temporary fix :)

**Comment by clauderic** [comment]
That's an intentional limitation, as its name implies, `verticalListSortingStrategy` is optimized to only support single column vertical lists. 

Your layout is a grid so you indeed need to use `rectSortingStrategy`.

**Comment by sampl** [comment]
Fair enough, thanks @clauderic
