### ISSUE TITLE
Can't drag a sortable element if its id = 0

### ISSUE THREAD

**Issue by MarkelMartiartu** [clauderic/dnd-kit#1150]
I have a SortableContext container with items as a number array [0, 1, 2, 3]. I can move all the items but the one with the id 0.

There's this code in the [useSortable](https://github.com/clauderic/dnd-kit/blob/master/packages/sortable/src/hooks/useSortable.ts) hook that might be causing the problem, since `if (0)` is false.
```
if (activeId && !previous.current.activeId) {
  previous.current.activeId = activeId;
  return;
}
```

**Comment by onnobos** [comment]
I have a similiar issue as well.

**Comment by nicostombros** [comment]
Would say to set the array of numbers to be an array of strings instead so you can still use `"0"`.

**Comment by Grawl** [comment]
https://typescript-eslint.io/rules/strict-boolean-expressions/
