### ISSUE TITLE
TypeScript error for `/@dnd-kit/utilities`

### ISSUE THREAD

**Issue by airtable-JayRansijn** [clauderic/dnd-kit#116]
I am getting the following issue in our TypeScript check:

```
../../node_modules/@dnd-kit/utilities/dist/types.d.ts(3,59): error TS2344: Type 'number' does not satisfy the constraint 'keyof Arguments<T>'.
  Type '0' is not assignable to type '"forEach" | "length" | "slice" | "push" | "reverse" | "fill" | "map" | "filter" | "toString" | "concat" | "indexOf" | "lastIndexOf" | "includes" | "sort" | "toLocaleString" | "pop" | ... 13 more ... | "values"'.
  ```
  
  
I will be investigating more, but thought I share here as well.

**Comment by clauderic** [comment]
What version of TypeScript are you using?

**Comment by airtable-JayRansijn** [comment]
We are at `4.1.3`. I am about to try to patch-package and maybe split up the args [in types](https://github.com/clauderic/dnd-kit/blob/ae212fe3e756213d51edb2ba6c3a75869856d535/packages/core/src/modifiers/types.ts#L4-L13) into a separate type:

```
export type ModifierArgs = {
  transform: Transform;
  activeNodeRect: ViewRect | null;
  draggingNodeRect: ViewRect | null;
  containerNodeRect: ViewRect | null;
  overlayNodeRect: ViewRect | null;
  scrollableAncestors: Element[];
  scrollableAncestorRects: ViewRect[];
  windowRect: ClientRect | null;
};

export type Modifier = (args: ModifierArgs) => Transform;
```

This might be a long shot, but one of my co-workers is mentioning there was an issue with `Array.isArray` with 4.1.2/4.1.3: https://github.com/microsoft/TypeScript/issues/40463 https://github.com/microsoft/TypeScript/issues/41808

Let me know if you have any suggestions.

**Comment by airtable-JayRansijn** [comment]
This seems to work for us as well, and is the patch we are likely picking to avoid patching both packages:
```
type FirstArgument<T> = T extends (firstArg: infer U, ...args: Array<any>) => any ? U : never
```

**Comment by clauderic** [comment]
I personally can't replicate, though haven't tried on that specific version of TypeScript. Do you want to open a pull request?

**Comment by airtable-JayRansijn** [comment]
Afaict, `FirstArgument` is only used in this one place. One option is to remove it altogether and split up the modifiers args type. Or if you want to keep `FirstArgument` around for something else I can make the change described above.

**Comment by clauderic** [comment]
Hey @airtable-JayRansijn, I don't think `FirstArgument` is used anywhere else in the codebase so no strong opinions either way. Do feel free to open a PR if this is blocking you though.
