### ISSUE TITLE
Variable sized sortables stretched when dragged

### ISSUE THREAD

**Issue by sampl** [clauderic/dnd-kit#117]
Hi @clauderic, sorry for the onslaught of issues this week :)

I have sortables with various heights getting stretched during drag. It looks like the size is being based on the size of the previous item in that position or something else, rather than the item's size?

https://www.loom.com/share/6013cf18e6b44fa2ad3e60826d57f814

Unlike the [rectSortingStrategy various sizes demo](https://5fc05e08a4a65d0021ae0bf2-vfebfgjygq.chromatic.com/?path=/story/presets-sortable-vertical--variable-heights), I'm not setting the size of my items using CSS grid. The size is determined by the content of each item.

Code Sandbox: https://codesandbox.io/s/dnd-kit-various-sizes-wo-grid-wnxzo

Apologies if this is my mistake or a documented known limit (I looked but didn't see anything).

**Comment by clauderic** [comment]
The items are stretched because you're using `CSS.Transform.toString()`, use `CSS.Translate.toString()` if you don't want to have the scale transformation applied.

In the example you've provided, the layout of your items is not predictable, therefore you won't be able to use any of the built-in sorting strategies, you'd need to build one yourself for that use-case (refer to https://github.com/clauderic/dnd-kit/issues/44#issuecomment-757312037).

You can however try to re-order the items `onDragOver` instead of `onDragEnd` as in this example, but it's not perfect as it is stretching the library beyond the use cases it is optimized for https://codesandbox.io/s/dnd-kit-various-sizes-wo-grid-forked-flxee?file=/src/App.jsx

**Comment by sampl** [comment]
> the layout of your items is not predictable, therefore you won't be able to use any of the built-in sorting strategies

Good to know, thanks for the clarification @clauderic 

Based on [this comment](https://github.com/clauderic/dnd-kit/issues/44#issuecomment-757222539) it sounds like you already plan to update the docs--I think that definitely would have helped set me straight.

> You can however try to re-order the items onDragOver instead of onDragEnd as in this example

Thank you! Looks good to me, I'll try this and see how it goes.

**Comment by eliot-loxo** [comment]
+1 to a doc update -- this GitHub issue saved me.

**Comment by ticmaidev** [comment]
this is not working for me:

> use CSS.Translate.toString()

---

**solution**

I just realized I had this option set, which actually solved my issue:

```tsx
<DragOverlay adjustScale>
```

**Comment by YakuBrangJa** [comment]
I used `verticalListSortingStrategy` in <SortableContext /> and it solved it.
`
import {SortableContext, verticalListSortingStrategy} from '@dnd-kit/sortable'

      <SortableContext
        items={formData.map(field => field.id)}
        strategy={verticalListSortingStrategy}
      >
      // Your sortable items
     </ SortableContext>
`

**Comment by chrisstayte** [comment]
This all did not work for me. I had a list of different size items. 
![Screenshot 2024-11-22 at 8 13 03 AM](https://github.com/user-attachments/assets/207bca87-646f-4580-98ef-a5371d17c4b4)
Attached is an example. 

Here is a code example of my solution to fix this.
`import { useDraggable } from '@dnd-kit/core';
import { CSS } from '@dnd-kit/utilities';

function DraggableItem() {
  const { attributes, listeners, setNodeRef, transform } = useDraggable({
    id: 'your-item-id',
  });

  const style = {
    transform: transform ? CSS.Translate.toString(transform) : undefined,
  };

  return (
    <div ref={setNodeRef} style={style} {...attributes} {...listeners}>
      {/* Your item content */}
    </div>
  );
}
`
