### ISSUE TITLE
how to get position of Draggable element relative to Droppable that isOver? in Sortable too

### ISSUE THREAD

**Issue by terlan4** [clauderic/dnd-kit#1187]
![image](https://github.com/clauderic/dnd-kit/assets/138553763/16230840-321f-4993-89ae-bb341f0aac3e)

## What I want to achive: 
when draggable element is over a droppable, I want to know how far away my mouse is from center/top border/ bottom border of that droppable. For example: 
if draggable's proximity to center of droppable is between 0.5 and 1, then make draggable child,
otherwise
if pointer is closer to top/bottom corner, then add draggable before/after that droppable(sortable) item.

### What I did try: 
Ive played with Sortable Tree example and tried to understand implementation. That example defines being child based of offsetLeft value/ indentationWidth. 

```ts
function handleDragMove({ delta, over, collisions, activatorEvent }: DragMoveEvent) {
  console.log('delta', delta.x, delta.y); //position of mouse from DragStart point
  over && over.rect && console.log('over.rect', over.rect) //position of element relative to entire screen
}
```
So I thougt using clientX clientY values instead of delta to compare with over.rect values and calculate proximity to center. But everthing I can think of feels hacky and gonna have other errors when scrolling and so on.

## My goal is getting the experience Notion is giving: 
close to center => nest the file
otherwise => sort before or after

https://github.com/clauderic/dnd-kit/assets/138553763/18b81096-bad1-4e8b-920d-c0b8f2174a65

<br>
Would be happy to get guidance on this 🙂(if somebody has implemented it, I would love to get link to that repo as well if possible)

**Comment by terlan4** [comment]
I guess I figured out how to check for center, but still would love to have further guidance on implementing the whole functionality.

```ts
function handleDragMove({ over, active }: DragMoveEvent) {
	let draggableCenterY;
	if (active.rect.current.translated) {
		draggableCenterY = active.rect.current.translated?.top + active.rect.current.translated?.height / 2;
	}
	let overCenterY;
	if(over){
		overCenterY = over.rect.top + over.rect.height / 2;
	}

	console.log('draggableCenterY: ', draggableCenterY)
	console.log('overCenterY', overCenterY)
}
```

**Comment by Anishali2** [comment]
hello brother @tommy-typos  i need your help for a bit please respond if possible
