### ISSUE TITLE
Maintance

### ISSUE THREAD

**Issue by Aarbel** [clauderic/dnd-kit#119]
@clauderic Will this repo will be poorly maintained  ?

Like your repos :
- https://github.com/clauderic/react-infinite-calendar
- https://github.com/clauderic/react-sortable-hoc

Or do you plan to ask Shopify to help you maintain your open source libraries ?
Or will you help other developers to have the rights to maintain your libraries as well ? 

Thanks a lot anyway for your work

**Comment by spyshower** [comment]
That's a bold thing to say. Reminds me of myself :P

Nevertheless, I would like to know the author's thoughts as well.

**Comment by sampl** [comment]
I share your concern about maintenance, but I want to come to the creator’s defense a bit here.

This is an open source project that I’m sure required a ton of work to build, and it has been offered to you completely free.

If you want to encourage upkeep, you could consider [becoming a sponsor](https://github.com/sponsors/clauderic).

**Comment by Aarbel** [comment]
@sampl i'll sure be a sponsor if the repo contributions administration is managed by more than two developers.

**Comment by Aarbel** [comment]
I think it's a big problem today on github. A lot of repos with a lot of stars are not maintained, and it's hard for forks to get the same attention / community / stars. It's completely impossible to get ownership of a project if it's not maintained.

**Comment by Aarbel** [comment]
@clauderic adding this on your repos would be great (i addition to accept other maintainers):

![image](https://user-images.githubusercontent.com/25119847/110655300-3867de80-81bf-11eb-8a7a-c2b64c8722c0.png)

**Comment by clauderic** [comment]
Hey @Aarbel, I do intend this repository to be well maintained. Thanks for your suggestions, I'll consider adding a maintainers table to my repositories when I get the chance.
