### ISSUE TITLE
Drag and drop functionality doesn't work inside of an iframe

### ISSUE THREAD

**Issue by odicho** [clauderic/dnd-kit#1192]
Hi! I bootstrapped the Sortable Tree example and everything is working fine when running it in a react application locally. The draggable functionality for nodes with children stopped working when the react application is loaded within an iframe on another website. Does anyone have any context on how to make this work? Reproduction is to wrap the entire DndContext inside an iframe.

**Comment by eduardorubim** [comment]
Found a solution for working within iFrame?

**Comment by ying-bin** [comment]
same problem
