### ISSUE TITLE
Sortable arrayMove doesn't work as intended

### ISSUE THREAD

**Issue by natan-fernandes** [clauderic/dnd-kit#1195]
Hello folks! I don't know why but when using `arrayMove`, sometimes a different item changes its position. Here's an example:
![](https://i.imgur.com/cypJIv6.gif)
As you can see, when I move B, A moves too. [codesandbox link](https://codesandbox.io/p/sandbox/dnd-kit-weird-arraymove-behavior-7vxhyg?file=%2Fsrc%2FApp.tsx%3A55%2C31)

When I use this function instead of `arrayMove` it works as intended:
```ts
setFoos((items) => {
  const newItems = [...items];

   const activeIdx = newItems.findIndex((x) => x.id === active.id)!;
   const overIdx = newItems.findIndex((x) => x.id === over.id)!;

   [newItems[activeIdx], newItems[overIdx]] = [newItems[overIdx], newItems[activeIdx]];

   return newItems;
});
```

Am I missing something?

**Comment by Chunkford** [comment]
Because you're using the `rectSwappingStrategy` use [arraySwap](https://github.com/clauderic/dnd-kit/blob/5c58f0fe5d19b5aaa5cf93572f3435f4a0a6e54f/packages/sortable/src/utilities/arraySwap.ts) instead of arrayMove

More info in this issue - https://github.com/clauderic/dnd-kit/issues/336

**Comment by natan-fernandes** [comment]
> Because you're using the `rectSwappingStrategy` try using [arraySwap](https://github.com/clauderic/dnd-kit/blob/5c58f0fe5d19b5aaa5cf93572f3435f4a0a6e54f/packages/sortable/src/utilities/arraySwap.ts) instead of arrayMove
> 
> More info in this issue - #336

Thanks, I'm feeling 100 times dumber now
