### ISSUE TITLE
Support for multi-select and drag?

### ISSUE THREAD

**Issue by junqdu** [clauderic/dnd-kit#120]
Trying to implement a grid view and drag multiple items at the same time. But it seems like dnd-kit only support the grid view but not selecting multiple items.

**Comment by clauderic** [comment]
You can refer to https://github.com/clauderic/dnd-kit/pull/13 for a general idea of how to implement this, but there are no immediate plans for multi-select to be available out of the box, this is something that consumers can fairly easily implement on top of dnd-kit.

**Comment by junqdu** [comment]
@clauderic Thanks!

**Comment by script8888** [comment]
> You can refer to #13 for a general idea of how to implement this, but there are no immediate plans for multi-select to be available out of the box, this is something that consumers can fairly easily implement on top of dnd-kit.

It's 2024 bro pls merge that patch 😭, 3years later
