### ISSUE TITLE
Feature Request: expose a way to access ActiveDraggableContext's data

### ISSUE THREAD

**Issue by amirhhashemi** [clauderic/dnd-kit#1205]
In my application, I need to have more control over the drop animation of `DragOverlay`. I want to completely replace the animation logic with Framer Motion.

There isn't an official way to implement a custom DragOverlay and I had to copy/paste a lot of code from the repo. Honestly it's not that bad, but, one thing I wish I had access to is the [`ActiveDraggableContext`](https://github.com/clauderic/dnd-kit/blob/5c58f0fe5d19b5aaa5cf93572f3435f4a0a6e54f/packages/core/src/components/DndContext/DndContext.tsx#L122C14-L122C36) from your internal code.

To render the Overlay in the correct position, I should know the coordinates of the active draggable node. As far as I know, there is no way to access the coordinates globally. `useDraggable` returns a `transform` object that can be used but I have to render the `DragOverlay` on the same level to be able to use it which is not very convenient.

It would be nice if there was a way to access the data of that context for more advanced use cases.

**Comment by yf-yang** [comment]
[Here](https://github.com/clauderic/dnd-kit/blob/5c58f0fe5d19b5aaa5cf93572f3435f4a0a6e54f/packages/core/src/components/DragOverlay/hooks/useDropAnimation.ts#L198) you can pass your custom function to compute the animation.
[Here](https://github.com/clauderic/dnd-kit/blob/5c58f0fe5d19b5aaa5cf93572f3435f4a0a6e54f/packages/core/src/components/DragOverlay/hooks/useDropAnimation.ts#L208) is how the function is function is called, you can pass a function and log all the input parameters, seems your demand is covered.
Check [DragOverlay's dropAnimation prop]'s type signature for more details

**Comment by amirhhashemi** [comment]
Hey @yf-yang. Thank you for the help. It worked.

Here is what I did in case anyone else is wondering:
```tsx
import { animate } from "framer-motion";

const dropAnimation = async ({ transform, dragOverlay }) => {
  await animate(
    dragOverlay.node,
    {
      x: [transform.x, 0],
      y: [transform.y, 0],
    },
    {
      type: "spring"
    },
  );
};

const Overlay = ({children}) => (
  <DragOverlay dropAnimation={dropAnimation}>{children}</DragOverlay>
)
```
