### ISSUE TITLE
dnd-sortable not working with objects instead of array values

### ISSUE THREAD

**Issue by mazimazur** [clauderic/dnd-kit#121]
Tested sortable with objects as items and not working anymore:

const [items, setItems] = useState([{ id: "1" }, { id: "2" }, { id: "3" }])

**Comment by ranbena** [comment]
Looking at the code and versions, it seems `<SortableContext>` only accepted a string array from day one.

**Comment by mazimazur** [comment]
> Looking at the code and versions, it seems `<SortableContext>` only accepted a string array from day one.

ok, thank you, will this stay like that or if needed with objects it's up to me to extend it?

**Comment by ranbena** [comment]
> ok, thank you, will this stay like that or if needed with objects it's up to me to extend it?

Personally I like it bc it keeps the consumer code a bit cleaner. @clauderic wdyt?

Itmt @mazimazur, all you gotta do is:
```tsx
<SortableContext items={items.map(item => item.id)}>
  ...
</SortableContext>
```

**Comment by mazimazur** [comment]
> > ok, thank you, will this stay like that or if needed with objects it's up to me to extend it?
> 
> Personally I like it bc it keeps the consumer code a bit cleaner. @clauderic wdyt?
> 
> Itmt @mazimazur, all you gotta do is:
> 
> ```tsx
> <SortableContext items={items.map(item => item.id)}>
>   ...
> </SortableContext>
> ```

big hug for that! works like a charm :-) thx a lot!
