### ISSUE TITLE
Nested sortable grid?

### ISSUE THREAD

**Issue by dancixx** [clauderic/dnd-kit#124]
Hi guys, can i use dnd-kit for nested sortable grid?
I need something like this https://5fc05e08a4a65d0021ae0bf2-nlpqzbyoil.chromatic.com/?path=/docs/presets-sortable-multiple-containers--vertical-grid, but i should be able to change the wrapper container too?

Thx for answer. :)

**Comment by jarredwitt** [comment]
@dancixx I've been searching for something similar and saw #39. Here's my attempt - https://codesandbox.io/s/dnd-kit-nested-containers-kvdgn?file=/src/app.js. It's based around rows, columns and items. Hopefully it helps.

**Comment by moxxuk** [comment]
@jarredwitt This is what I need too, but unfortunately the codesandbox is not working. Do you have a working version?

**Comment by jarredwitt** [comment]
@moxxuk I fixed the codesandbox. The particular example was built using v2 of dnd-kit. Definitely some edge cases that are not covered and dragging is a bit sporadic. It was mainly built to just see if it was even possible so hopefully you can take a look at how the re-parenting works in the handlers to build what you need.

**Comment by moxxuk** [comment]
Thanks for fixing the codesandbox, very close to what I need and simple enough to understand and build upon :)
