### ISSUE TITLE
Race condition with `useDraggable` and `useDroppable` register / un-register effects

### ISSUE THREAD

**Issue by migueloller** [clauderic/dnd-kit#125]
We were implementing a file tree navigation component using dnd-kit and ran into an issue that happens when sorting folders. The UI component looks something like this:

![image](https://user-images.githubusercontent.com/5677929/110716250-c8645300-81d4-11eb-9ef3-a191a99ea901.png)

You can drag folders around to drop them inside other folders. The issue happens when doing one of these sort operations. React doesn't guarantee that `useEffect` registrations and cleanup will run in tandem so what ends up happening when moving a folder is something like this:

1. `ActionTypes.RegisterDroppable` component dropped into new location
2. `ActionTypes.UnregisterDroppable` cleaning up from previous location

Note that the unregister action fires before the register action. This is the case when moving a folder higher up in the tree. In the past we've solved this issue by using a counting semaphore. Instead of simply having a map and then calling `set` and `delete` on the register/unregister actions, we increment a counter on register and decrement on unregister. If the count hits 0, then delete it.

Here's an almost drop-in replacement for `Map` that we use for this:

```ts
type CountingSemaphore<V> = { count: number; value: V }

export class CountingSemaphoreMap<K, V> {
  map: Map<K, CountingSemaphore<V>>

  constructor(map?: CountingSemaphoreMap<K, V> | null)
  constructor(entries?: readonly (readonly [K, V])[] | null)
  constructor(mapOrEntries?: CountingSemaphoreMap<K, V> | readonly (readonly [K, V])[] | null) {
    this.map =
      mapOrEntries instanceof CountingSemaphoreMap
        ? new Map(mapOrEntries.map)
        : new Map(mapOrEntries?.map(([key, value]) => [key, { count: 1, value }]))
  }

  toMap = (): Map<K, V> => {
    return new Map(Array.from(this.map.entries()).map(([key, { value }]) => [key, value]))
  }

  get = (key: K): V | undefined => {
    return this.map.get(key)?.value
  }

  set = (key: K, value: V): this => {
    const existing = this.map.get(key)

    this.map.set(key, { count: (existing?.count ?? 0) + 1, value })

    return this
  }

  delete = (key: K): boolean => {
    if (!this.map.has(key)) return false

    const existing = this.map.get(key)!

    if (existing.count === 1) return this.map.delete(key)

    this.map.set(key, { ...existing, count: existing.count + 1 })

    return true
  }
}
```

Unfortunately we're going to have to move off of dnd-kit due to this issue, #43, and #50. The latter 2 are due to not polling droppable and draggable bounding client rects, which should really be the source of truth when doing collision detection. It avoids having to do any transformations with scrollable parents, etc. We also found ourselves having to hack a pointer intersection algorithm using a ref because dnd-kit doesn't provide the pointer in the `collisionDetection` API.

Anyway, Hopefully this bug report helps out! Thanks again for creating this library and open sourcing it!

**Comment by clauderic** [comment]
Could you share a video or a sandbox replicating the issues you've encountered? Just want to make sure I'm understanding everything correctly before jumping to conclusions.

**Comment by messerc** [comment]
Hi @clauderic, I think we've encountered a similar issue, and it is potentially pretty serious. More specifically, we're having issues with draggable and droppable registration in a nested context. If a container with nested draggable / droppable nodes is dragged and re-ordered, all droppable and draggable components within are un-registered, never to come back. If you refresh the page, of course all the nodes are registered as expected.

As GP pointed out, the offending code seems like it could be a race condition in within the clean-up of the `useEffect` (ex: https://github.com/clauderic/dnd-kit/blob/master/packages/core/src/hooks/useDroppable.ts#L24-L45). 

To patch this up quickly for now, I've reached into some of the internals of dnd-kit and forcefully re-register when needed, like so:

```
export function useForcefulDroppableRegister(
  dragId: string,
  node: React.MutableRefObject<HTMLElement | null>,
  rect: React.MutableRefObject<LayoutRect | null>,
) {
  const { dispatch, droppableContainers } = useDndContext();
  const droppableContainer = droppableContainers[dragId];
  const isDroppableContainer = Boolean(droppableContainer);
  const prevData = usePrevious(droppableContainer?.data);
  const prevDataRef = React.useRef(prevData);
  prevDataRef.current = prevData;
  React.useEffect(() => {
    if (!isDroppableContainer && prevDataRef.current) {
      dispatch({
        type: Action.RegisterDroppable,
        element: {
          id: dragId,
          node,
          rect,
          disabled: false,
          data: prevDataRef.current,
        },
      });
    }
  }, [dragId, dispatch, isDroppableContainer, node, rect]);
}
```

Making a clean repro on a sandbox would take too much time since dnd-kit doesn't come with off-the-shelf nested context examples, but hopefully this is enough to get started.

**Comment by eschaefer** [comment]
@messerc I want to thank you for posting this workaround code. It did exactly fix the same issue for us. I ended up needing to spread a little more data into the `draggableNodes[dragId]`, but it actually worked and re-registered forcefully.

```
...
       draggableNodes[eventId] = {
        node,
        data: {
          current: {
            // Same `data` properties that `useDraggable` was initiated with...
            type: 'x',
            event: {
              title: 'y',
            },
          },
        },
      };
```

**Comment by messerc** [comment]
thanks for that @eschaefer - I'm glad at least someone else got some benefit from my hours of confusion and pain.
