### ISSUE TITLE
Sorting: Item jumps back to original position if the distance between items is more than the width of an item.

### ISSUE THREAD

**Issue by Puneet56** [clauderic/dnd-kit#1259]
Codesandbox link: https://codesandbox.io/s/hungry-cartwright-hc63h9?file=/src/App.js

When moving the items in a horizontal flex box and the gap between the items is more than the items width, the item jumps back to original position.

In the sandbox link, moving boxes with blue border to visualize the issue.

https://github.com/clauderic/dnd-kit/assets/26213419/a3b74785-bc5c-4976-ae9a-35905729cc3a

**Comment by BauerPh** [comment]
Try using a DragOverlay:
https://docs.dndkit.com/api-documentation/draggable/drag-overlay
