### ISSUE TITLE
Help - Documentation - Sortable grid reordering

### ISSUE THREAD

**Issue by mihainsto** [clauderic/dnd-kit#126]
Hi, I am following the documentation and the result isn't the expected one, I implemented almost exactly the code from this example 
https://docs.dndkit.com/presets/sortable#drag-overlay 

And I have multiple problems, the reordering looks odd, all the items move in all the places, and the element that I am dragging is showing twice.

Here is the sandbox with the issue:
https://codesandbox.io/s/dnd-kit-grid-problem-gv8v4?file=/src/App.js

**Comment by ranbena** [comment]
>  all the items move in all the places

That's because you're using the `index` as the SortableItem key value instead of `item`. Change to this:
```tsx
return <SortableItem id={item} key={item} />;
```

> element that I am dragging is showing twice.

One is the original item, the other is the dragged item. You can use different styling on the original item when dragging.
Here's an example to make it translucent upon dragging:
```tsx
const {
  attributes,
  listeners,
  setNodeRef,
  transform,
  transition,
  isDragging, // <-- add this
} = useSortable({ id });

const style = {
    transform: CSS.Transform.toString(transform),
    transition,
    opacity: isDragging ? 0.5 : 1, // <-- add this
  };
```

**Comment by mihainsto** [comment]
Thank you, here is the updated sandbox in case there are other people with this issue:
https://codesandbox.io/s/dnd-kit-grid-problem-fixed-14hse?file=/src/App.js
