### ISSUE TITLE
Multi select

### ISSUE THREAD

**Issue by Radhakrishnan-gopal** [clauderic/dnd-kit#1277]
When are we getting multi select?

**Comment by clauderic** [comment]
Multi-select is supported but is something that mostly needs to be handled in your application logic. Refer to this example https://github.com/clauderic/dnd-kit/pull/588

**Comment by Radhakrishnan-gopal** [comment]
@clauderic Awesome work. I am doing R&D for choosing DND lib. 

I like dnd-kit. Which version do i need to use for muti-select? 

Some Quick Feedback
it seems to react beautifully DND is easier to implement with less code and it can adopt any code base.
