### ISSUE TITLE
Trying to drag and drop with Cypress while using DragOverlay

### ISSUE THREAD

**Issue by swavans** [clauderic/dnd-kit#1278]
Hi,

I'm trying to test my drag and drop components with cypress but can't seem to get it to work.
The problem seems to be that when I try to start dragging, cypress still has the focus on the display element rather then the draggable element in the DragOverlay. I tried using the example code in the /cypress/support/commands.ts but that didn't work. 

Anyone that tried this before? Thnx in advance.

**Comment by jeffal** [comment]
@swavans This worked for me too! Thnx for following up here!
