### ISSUE TITLE
Make drag and drop relative to pointer

### ISSUE THREAD

**Issue by paralin** [clauderic/dnd-kit#1296]
The default behavior is to have the dragged element (and the div within the DragOverlay) be dragged relative to its original position. If I click and drag the Draggable at some offset from the origin of the Draggable, it will move relative to its original position with an offset according to the distance I have dragged the pointer.

How can I instead have the dragged item "jump" to the location of the pointer immediately? I want the dragged item to be located directly below the pointer instead of relative to its original position.

**Comment by x-Foz3R-x** [comment]
is what are you after the collisionDetection={pointerWithin} on dndContext imported from "@dnd-kit/core"?

**Comment by paralin** [comment]
Changes the collision detection but not the positioning.

**Comment by paralin** [comment]
https://stackoverflow.com/a/78527248/431369

I have not tried it yet but this seems like the answer:

Snap cursor to center: install `@dnd-kit/modifiers` and pass `snapCenterToCursor` into `DragOverlay`: 

```
<DragOverlay modifiers={[snapCenterToCursor]}> <YourDraggableComponentCopy /> </DragOverlay>
```

Collision detection: add `collisionDetection={pointerWithin}` prop to `DndContext`:

    <DndContext collisionDetection={pointerWithin}>...</DndContext>

See the ["Pointer within" docs][1] for more info.


  [1]: https://docs.dndkit.com/api-documentation/context-provider/collision-detection-algorithms#pointer-within
