### ISSUE TITLE
Is it possible to give the over element a style? 

### ISSUE THREAD

**Issue by Gellipapa** [clauderic/dnd-kit#1299]
Thanks for this library, it's really very simple and easy to use lib, but I'm a bit stuck and I'd like to ask for your help.

I have a two-column layout and I want to make it so that if I drag an element in one column over another element, I can control the style of the over element. 

I tried to get the element.id in dragOver based on the context but if I set the useState there I get into a render loop, is there any solution how to control the style of the over element?

What I mean is that when I drag the element up, I can set the style of the div below the dragged element, which I get back in the over as a key in the context. 

Thank you in advance for your reply.
![image](https://github.com/clauderic/dnd-kit/assets/22717950/1b099436-a581-4973-ac4d-fd830d6c1a08)

**Comment by jamesthomsondev** [comment]
The `useDroppable` hook exposes a `isOver` boolean. You can use that to determine if an element is being dragged over an area and response accordingly.

**Comment by Gellipapa** [comment]
> The `useDroppable` hook exposes an `isOver` boolean. You can use that to determine if an element is being dragged over an area and respond accordingly.

Hi! Thank you for your reply. I have solved the problem with your help and will change the default collision strategy to Pointer inside. Because this way there was no more continuous detection and so it could work as I wanted. Thank you.
