### ISSUE TITLE
Active item briefly flashes back to starting position before moving to a new position

### ISSUE THREAD

**Issue by Gokul-Manoh** [clauderic/dnd-kit#1307]
When I sort an item, it moves to a new position but only after it flashes back to its original position as shown in the video. Any help is appreciated. 

I find this issue same as that of the one here [https://github.com/clauderic/dnd-kit/issues/743](url). But that did not help me. 

@clauderic can you please have a look?

I assume the below code helps
![image](https://github.com/clauderic/dnd-kit/assets/149458857/26fef7b1-5840-4cab-9a03-bb1074543fcb)

![image](https://github.com/clauderic/dnd-kit/assets/149458857/07f7f755-ceef-4e5a-89e4-1af0da3444d9)

![image](https://github.com/clauderic/dnd-kit/assets/149458857/239ff1a7-8f05-4ece-b4ef-228582562c1b)

https://github.com/clauderic/dnd-kit/assets/149458857/754c35a2-59cc-4398-9608-087d1dbb3763

**Comment by Gokul-Manoh** [comment]
Update
I fixed the issue. I had set the duration as 500ms while calling useSortable hook. I changed it to 0 and it worked.

**Comment by Gokul-Manoh** [comment]
Closing the issue.

**Comment by xixihhhh** [comment]
have the same problem, it can slove, but it turns animation off.
