### ISSUE TITLE
Cannot sort Elements with identifier={0}

### ISSUE THREAD

**Issue by LukasOchmann** [clauderic/dnd-kit#1327]
When using numbers as identifiers an element that recives the id={0} cannot be dragged/sorted.

Please see the following [Sandbox](https://codesandbox.io/p/sandbox/dnd-kit-bug-8rtgt7?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrri9obt00062v6fm3cdi0xd%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrri9obt00022v6fe7ibhyrk%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrri9obt00032v6faz3qqh0u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrri9obt00052v6fyopausug%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrri9obt00022v6fe7ibhyrk%2522%253A%257B%2522id%2522%253A%2522clrri9obt00022v6fe7ibhyrk%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clrri9obt00052v6fyopausug%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrri9obt00042v6ff9rd4w3y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrri9obt00052v6fyopausug%2522%252C%2522activeTabId%2522%253A%2522clrri9obt00042v6ff9rd4w3y%2522%257D%252C%2522clrri9obt00032v6faz3qqh0u%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrri9obt00032v6faz3qqh0u%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D):

Is this a a bug or an expected behaviour? If this is an expected behaviour, it would be nice to mention it in the Docs.

Of course a Workaround is to just start at 1 instead.

Thank you in advance.

**Comment by blinkcat** [comment]
duplicated issue  #858
