### ISSUE TITLE
useSortable draggable items moving twice

### ISSUE THREAD

**Issue by FalconiZzare** [clauderic/dnd-kit#1362]
# 🐛 Need Help With Draggble Item Moving Twice Issue
## 📝 Description Of The Issue
I'm using DnDContext, SortableContext and useSortable hook and a DragOverlay. Whenever I start dragging an item and move it over to another draggbale item within the context, the active item moves to that place and the over item moves left or right while i'm still holding the overlay. So far so good, but when I let go of the dragging item as in dragEnd event, the over item that was moved, does the moving animation/logic again. I highly doubt it might be related to the implementation, but I have no clue where. Used it previously too, but never faced this issue. Any help will be really appreciated.
## 👀 Visual Preview Of The Issue
![0MSNNBcVG8](https://github.com/clauderic/dnd-kit/assets/65172465/553bbf4d-66da-4b93-8927-f93867d1681b)
## 🔗Link to repositories
GitHub: [Link](https://github.com/FalconiZzare/dnd-issue)

GitHub Pages: [Link](https://falconizzare.github.io/dnd-issue/)

StackBlitz: [Link](https://stackblitz.com/edit/fz-dnd-issuue)
## ⚙️ My Environment
| Package  | Version |
| ------------- | ------------- |
| node  | v21.7.1  |
| react  | v18.2.0  |
| @dnd-kit/core | v6.1.0 |
| @dnd-kit/modifiers | v7.0.0 |
| @dnd-kit/sortable | v8.0.0 |
| @dnd-kit/utilities | v3.2.2 |

**Comment by Ilannildo** [comment]
<img width="658" alt="Captura de Tela 2024-03-14 às 09 03 31" src="https://github.com/clauderic/dnd-kit/assets/71016400/97c650a8-caeb-42ad-ae1d-df5f2244dbf0">

Put the category id in place of the index

**Comment by FalconiZzare** [comment]
> <img alt="Captura de Tela 2024-03-14 às 09 03 31" width="658" src="https://private-user-images.githubusercontent.com/71016400/312829499-97c650a8-caeb-42ad-ae1d-df5f2244dbf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDY4ODcsIm5iZiI6MTcxMDcwNjU4NywicGF0aCI6Ii83MTAxNjQwMC8zMTI4Mjk0OTktOTdjNjUwYTgtY2FlYi00MmFkLWFlMWQtZGY1ZjIyNDRkYmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDIwMTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZGM4ZTUzNTIzOTY2NmI5MWRkMzgyNzU2YzQ2ZWQ3MTgwNWE4NWRhYzI5OGQ4MGUxMzUyNjQ1MGYxYTI5NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RplU3wsUdC72IFMt7D7HM7wlFkdzzdkU1_qE7sfvp1Q">
> Put the category id in place of the index

Thanks man! Completely forgot about this.
