### ISSUE TITLE
Unable to scroll with mouse wheel when dragging

### ISSUE THREAD

**Issue by sebak94** [clauderic/dnd-kit#1364]
Hello! I got a layout as shown in the image where you can drag and drop items through a calendar. So basically each day is a container of sortable items.

<img width="1224" alt="image" src="https://github.com/clauderic/dnd-kit/assets/18013876/8b109482-6d6c-4926-acf2-41096339a541">

The problem is that I can't scroll with the mouse wheel when grabbing an item. It does scroll when moving the item up and down to different weeks though.

I should be able to do that, right? In this example https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/presets-sortable-multiple-containers--vertical it's possible.

Any ideas? Thank you very much.

**Comment by nippolito** [comment]
Bump! I'm also experiencing this issue

**Comment by sebak94** [comment]
Solution:

Add `pointer-events: none` to `DragOverlay` component
