### ISSUE TITLE
Getting `aria-describedby` warning

### ISSUE THREAD

**Issue by divyam-mistry** [clauderic/dnd-kit#1389]
Getting this warning
- app-index.js:33 Warning: Prop `aria-describedby` did not match. Server: "DndDescribedBy-3" Client: "DndDescribedBy-0"

Is there any way to remove this warning? I am happy to share my code later, if this is any issue from my side (i.e implementation)

**Comment by richardvanbergen** [comment]
@divyam-mistry https://github.com/clauderic/dnd-kit/issues/926#issuecomment-1640115665

Using the search function before opening new issues is good practice
