### ISSUE TITLE
Is it possible to add more data about the draggable in DragStartEvent?

### ISSUE THREAD

**Issue by jaymathew** [clauderic/dnd-kit#139]
Hey, Thanks so much for this library. 

Is it possible to add more data into the DragStartEvent? I know you can see the id currently. I would need to filter through an extensive list to find the object I need, and using an index as the id wouldn't work as I render two arrays in one DndContext. 

Thank you,

**Comment by salali** [comment]
Would it be possible for the useDroppable `data` property to be passed to the `DndContext` event handlers?

interface UseDroppableArguments {
  id: string;
  disabled?: boolean;
  data?: Record<string, any>; // Add this property to the event.active object?
}

**Comment by clauderic** [comment]
Adding `data` to draggable items and exposing `data` of the `over` droppable in handlers is planned, just haven't had time to get around to it.

@salali if you want to get started working on a PR with that change I'd gladly work with you to get it done.

**Comment by norbertas-gaulia** [comment]
That would be great addition. 
Is there any way to get any info about draggable currently? If i want to switch css class based on who is over? Thanks

**Comment by clauderic** [comment]
@norbertas-gaulia you can already get info about the current draggable and what droppable it is over in what is returned by `useDraggable()` and `useDroppable` or in the `onDragOver` callbacks of `DndContext`.

This is documented in the [Quick start guide](https://docs.dndkit.com/introduction/getting-started) along with the docs for [`useDraggable`](https://docs.dndkit.com/api-documentation/draggable/usedraggable#over) and [`useDroppable`](https://docs.dndkit.com/api-documentation/droppable/usedroppable#over).

**Comment by norbertas-gaulia** [comment]
Correct, i missed `over` prop from `useDroppable `. Thanks.

**Comment by clauderic** [comment]
> But it gives droppable node and droppable id, what if i want draggable id in droppable?

```tsx
import {useDndContext} from '@dnd-kit/core';

function Droppable() {
  // You can get the `id` of the active draggable 
  const {active} = useDndContext();
}
```

**Comment by growthwp** [comment]
I just wanted to comment and say that @jaymathew most likely needs to insert metadata in other to identify a type of a draggable. I'm almost 100% positive he has multiple, unrelated draggables in a list. With the `active` from `useDnDContext`, he'll be getting an active draggable's ID, but then the pseudo-code for actually finding more information about that draggable is basically "look through N number of lists, in M number of items to find the draggable by ID, then work out its type and metadata" where-as if you could provide metadata, all you'd have to do is a simple lookup `draggablesList[active].type`.

Being able to decorate a draggable with metadata allows passing arbitrary data to droppables (and therefore the context) that let you have complex logic. An example would be, as the issue I'm having: determining what type of draggable should land into what type of droppable on the `onDragEnd` event.

**Comment by clauderic** [comment]
@growthwp the plan is for consumers to be able to define arbitrary data on both draggable and droppable elements when invoking the `useDraggable` / `useDroppable` hooks and have this data available in handlers (`onDragStart`, `onDragOver`, `onDragEnd`, etc.) as well as sensors and collision detection algorithms. 

Something like:

```ts
const {} = useDraggable({
  id: 'draggable-thing',
  data: {
    type: 'button',
  }
});
```

```ts
const {} = useDroppable({
  id: 'droppable-thing',
  data: {
    accepts: {
      type: ['button'],
    },
  }
});
```

**Comment by growthwp** [comment]
@clauderic Can't wait! Only keep reading if you don't wanna end up rolling your eyes at some possibly stupid stuff 😭
 
 This should solve lots of issues and allow for draggables/droppables to communicate regardless of where they are, but if the current architecture is kept (usage of `Context`), is that actually possible?

Let's assume that we already have sensors, collision and data on droppables/draggables, does the library then switch from the approach of wrapping everything you need into a `DndContext` to just freely using draggables/droppables? As it currently stands, the problem with the usage of context in `dndkit` is that you don't really have access to outside contexts, so, no matter how you decorate draggables, with this new approach, there will be only one single shared context, right?

As of now, you can bypass this issue by having conditional collision techniques and **the shame, shared context.**

**Comment by clauderic** [comment]
As of version `^3.0.0` of `@dnd-kit/core`, the `data` argument for `useDraggable` and `useDroppable` is now exposed in event handlers and on the `active` and `over` objects.

**Example usage:**

```tsx
import {DndContext, useDraggable, useDroppable} from '@dnd-kit/core';

function Draggable() {
  const {attributes, listeners, setNodeRef, transform} = useDraggable({
    id: 'draggable',
    data: {
      type: 'type1',
    },
  });

  /* ... */
}

function Droppable() {
  const {setNodeRef} = useDroppable({
    id: 'droppable',
    data: {
      accepts: ['type1', 'type2'],
    },
  });

  /* ... */
}

function App() {
  return (
    <DndContext
      onDragEnd={({active, over}) => {
        if (over?.data.current.accepts.includes(active.data.current.type)) {
          // do stuff
        }
      }}
    />
  );
}
```

Refer to https://docs.dndkit.com/api-documentation/droppable/usedroppable#data and https://docs.dndkit.com/api-documentation/draggable/usedraggable#data for more details.
