### ISSUE TITLE
Unable to drag item backwards (Sandbox available)

### ISSUE THREAD

**Issue by samkingtwentytwo** [clauderic/dnd-kit#1392]
Hi guys, my handleDragOver function seems to be working fine, apart from when i drag the item backwards after going in one direction, it jumps an extra one each time. Been working on this for ages :(

https://codesandbox.io/p/devbox/kanban-3wq44f?file=%2Fapp%2Fpage.jsx

Much appreciated in advance!

**Comment by VladimirAfanasievFS** [comment]
Hi. Id should match with itemsIds

 <SortableContext items={column.taskIds.map((id) => `task-${id}`)}>
 
https://docs.dndkit.com/presets/sortable/usesortable#identifier

**Comment by samkingtwentytwo** [comment]
!!!!!!!!!!!!!!!!!!!!!!!! MY GUY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

THANKYOU SO MUCH!!!

You have saved weeks of trial and tribulation!

Thankyou my friend.
