### ISSUE TITLE
Example pages are not accessible

### ISSUE THREAD

**Issue by LordZardeck** [clauderic/dnd-kit#1395]
Going to this url provides the following error: https://examples.dndkit.com/
![image](https://github.com/clauderic/dnd-kit/assets/1145989/a971d183-a7b6-411f-9bc3-67d691d9cc5b)

**Comment by niltonslf** [comment]
Same here

**Comment by zxpzdtom** [comment]
+1

**Comment by welschmoor** [comment]
Same

**Comment by yarapolana** [comment]
Same

**Comment by welschmoor** [comment]
can be closed, it's available as of today 20240505
