### ISSUE TITLE
@dnd-kit/react (beta). Wrong nested scrollable elements activating

### ISSUE THREAD

**Issue by AddMoreScripts** [clauderic/dnd-kit#1429]
Greetings!
Thank you for publishing the experimental beta-branch in npm.
I want to use @dnd-kit/react for kanban-board. But I encountered a bug.

I have one `DragDropProvider` and several nested scrollable elements with draggables located inside them (useDraggable({...})).
When I start dragging the first element, everything works well, autoscroll works correctly.

But if then I start dragging an element from another container, the first container will still scroll.
Is this a bug? or am I doing something wrong?
I am attaching a video demonstration:

https://github.com/clauderic/dnd-kit/assets/52598143/2d64e6e9-8b4d-4eef-876a-b38214e16eaa

**Comment by clauderic** [comment]
Which version are you using? I've released several beta versions under the beta tag on npm

https://www.npmjs.com/package/@dnd-kit/react?activeTab=versions

**Comment by AddMoreScripts** [comment]
@clauderic screen recorded on 0.0.2-beta-20240610024106
I just saw the new beta version. Perhaps this bug is no longer there?

**Comment by AddMoreScripts** [comment]
@clauderic, yes, sure:

https://codesandbox.io/p/sandbox/dnd-kit-beta-gxm2lk?file=%2Fsrc%2FApp.tsx

**Comment by clauderic** [comment]
It's fixed now:
https://codesandbox.io/p/sandbox/dnd-kit-beta-forked-yymnjq?file=%2Fpackage.json%3A9%2C24

Fixed by this commit:
https://github.com/clauderic/dnd-kit/commit/1483a9f24d2891cb2eee838bc8e72288911dac38

Available in the latest beta release:
[0.0.2-beta-20240610193339](https://www.npmjs.com/package/@dnd-kit/react/v/0.0.2-beta-20240610193339)


Let me know if you run into any other issues with the beta packages :)

**Comment by AddMoreScripts** [comment]
@clauderic 
Thank you.
I updated my version too. Unfortunately, scrolling now stops when the dragged element goes beyond the border of a scrollable div, whereas previously it continued at maximum speed in this case. But I think that my request is very specific, it may be very difficult to implement.

**Comment by clauderic** [comment]
I pushed a small tweak to the auto scroller that should make this behave more like most consumers would expect, try it out and let me know what you think.

**Comment by AddMoreScripts** [comment]
its work perfect, thankyou.
