### ISSUE TITLE
does `useSortable` support different draggable types?

### ISSUE THREAD

**Issue by cusxio** [clauderic/dnd-kit#143]
It isn't entirely clear from the Docs, but currently in [`Multiple Containers - Basic Setup`](https://5fc05e08a4a65d0021ae0bf2-ozsuihnmxx.chromatic.com/?path=/story/presets-sortable-multiple-containers--basic-setup) is it also possible to sort the droppable(container) as well? Thereby achieving a Kanban like app?

---

I'm wondering if it's possible to use `dnd-kit` to replicate [this](https://react-beautiful-dnd.netlify.app/?path=/story/board--with-combining) behavior? 

i.e. boards can be sorted and combined, board items can also be sorted and combined.

**Comment by clauderic** [comment]
As for your first question,you can nest multiple levels of `<DndContext>` providers. To make the columns also sortable, all that is needed is also wrapping the columns in a second `<DndContext>` provider and `<SortableContext>`. I've been planning to add this functionality to the stories, just have not gotten around to it yet.

As for combining items, this is _possible_ but you will have to put in some work to get it done. Refer to this issue to learn more #114

**Comment by cusxio** [comment]
Noted and thank you!

**Comment by ranbena** [comment]
@clauderic in such a case, in order to render the appropriate **dray overlay**, one should conditionally render according to custom sortable data (example below)? Or is there simpler way?

```tsx
// Item.tsx
const { ... } = useSortable({ id, data: { type: "item"} });

// Column.tsx
const { ... } = useSortable({ id, data: { type: "column"} });

// Main.tsx
const dragOverlay = () => {
  const type = draggedItem?.data.current?.type;

  if (type === "column") {
    return <Column ... />;
  }

  if (type === "item") {
    return <Item ... />;
  }

  return null;
};

return (
  <DndContext>
    <SortableContext items={columnIds}>
      ...
      <NestedSortableContext items={itemIds}>...</...>
      ...
    </SortableContext>
    <DragOverlay>{dragOverlay}</DragOverlay>
  </DndContext>
);
```

**Comment by clauderic** [comment]
Hey @ranbena, the example you have above is the way to _currently_ do it, but it doesn't lead to the greatest separation of concerns.

The main reasons why rendering the `<DragOverlay>` component within a component that uses `useSortable` isn't recommended is that the `DragOverlay` component should not unmount while dragging, so if you have items that shift from one column to another while dragging (which causes them to unmount and re-mount), that's a no-go.

Currently, the `<DragOverlay>` component doesn't support being conditionally rendered because of how the drop animation works. That could be fixed by introducing an `onDropAnimationComplete` prop on `<DragOverlay>` to unmount it after the drop animation has completed though.

**Comment by ranbena** [comment]
> The main reasons why rendering the <DragOverlay> component within a component that uses useSortable isn't recommended is that you should only have a single instance of DragOverlay mounted at a time, and the DragOverlay component should not unmount while dragging, so if you have items that shift from one column to another while dragging (which causes them to unmount and re-mount), that's a no-go.

Whoops, it's a typo - it's actually `<SortableItem>` and `<SortableColumn>` that implement `useSortable`, not `<Item>` and `<Column>`. Of course, the `DragOverlay` should not render a sortable component.

> Currently, the <DragOverlay> component doesn't support being conditionally rendered because of how the drop animation works. That could be fixed by introducing an onDropAnimationComplete prop on <DragOverlay> to unmount it after the drop animation has completed though.

Not sure I understand what scenario can yield a problem. (I've already implemented this and it does work perfectly)

**Comment by clauderic** [comment]
@ranbena I was referring to this type of pattern:

```tsx
function SortableItem({id, type}) {
  const {active} = useSortable({
    id,
    data: {
      type,
    }
  });

  return (
    <>
      <Item />
      <DragOverlay>
        {active?.data.current?.type === type ? <Item /> : null}
      </DragOverlay>
    </>
  );
}
```

It's not recommended because:
- You should only have a single instance of DragOverlay mounted at a time (assumptions in the library, performance reasons)
- The DragOverlay component should ideally not unmount while dragging; if `SortableItem` is unmounted and moved to a different column while dragging, that assumption will be broken.

**Comment by ranbena** [comment]
Oh I understand.
I implemented a single `DndContext` and single `DragOverlay` that encompass all the sortables within the kanban.

**Comment by AlanaFarkas** [comment]
@ranbena Glad you got it working! Is there any code you can share? I'm trying to make a kanban-type board as well. Currently I can reorder the parent columns and the reorder the children within the parent. But when I reorder the parents, the children don't move with its parent.

**Comment by AlanaFarkas** [comment]
@ranbena thank you! This is helpful although in your sandbox, the items don't get reordered, just dragged around.

**Comment by ranbena** [comment]
Yeah I skipped that part to make the code more readable where it counts 😎

**Comment by clauderic** [comment]
I just finished implementing a working example of multiple containers with sortable columns in the official stories: https://5fc05e08a4a65d0021ae0bf2-rvnnplhsjm.chromatic.com/?path=/story/presets-sortable-multiple-containers--basic-setup

https://user-images.githubusercontent.com/1416436/132930538-3d8c5b99-a9de-4bde-8919-3bb724126437.mp4


It allowed me to find a couple bugs along the way too 😄

**Comment by valerii15298** [comment]
@clauderic  thank you. That is exactly what I need. Can you please share code for it?
