### ISSUE TITLE
Question before migrating :)

### ISSUE THREAD

**Issue by EdmundsEcho** [clauderic/dnd-kit#145]
This library looks absolutely great.  Nice work.

I'm eager to find a new solution.  My data is in the form of a tree.  Each layer of the tree specifies a droppabal/draggable pair.  The depth of the tree is 5 (in other words, I'm not expecting more than 10 layers ever).  

The flat version of the state is:
```js
tree: {
    0: {
       id: 0, 
       height: 0,
       data: {}, 
       parent: null, 
       childIds:[1,2],
    },
  1: {
       id: 1, 
       height: 1,
       data: {}, 
       parent: 1, 
       childIds:[...etc],
    },
    2: {
       id: 2, 
       height: 1,
       data: {}, 
       parent: 1, 
       childIds:[...etc],
    },
// etc...
    15: {
        id: 15,
        height: 4,
        data: { item },
        parent: 14,
        childIds: [],
    }
}
```

The leaf nodes have the items of interest.  The nodes to that point are just ways to group the items.  The system needs to capture the drop events at the various height/nodes.  The draggables can be any node or leaf.

Can this library track the movement events in such a layered design?

Thanks in advance for letting me know.

\- E

**Comment by clauderic** [comment]
Hey @EdmundsEcho, what type of interface are you building? Looking at your data structure, it sounds like you're building a sortable tree. If so, you can take a look at this story which should give you a general idea of how to flatten your data structure to make it work with `@dnd-kit` https://github.com/clauderic/dnd-kit/pull/76
