### ISSUE TITLE
There is an unwanted highlight animation when i click on the draggable item

### ISSUE THREAD

**Issue by bookjukies** [clauderic/dnd-kit#1455]
Thank you for the great library.

The issue is that when i click on the item there is this whitish highlight effect animation.
 
https://github.com/user-attachments/assets/34de6abc-26ac-400c-9ab2-4a1b6ed6beef

**Comment by aarjithn** [comment]
@bookjukies This seems to be a specific use case with custom buttons / tabs - why do you think the issue lies with dnd-kit library rather than with the implementation?
