### ISSUE TITLE
Drag breaks with multiple droppables on Chromium - experimental

### ISSUE THREAD

**Issue by justinnais** [clauderic/dnd-kit#1462]
Hi Claudéric,

I've been trying out the alpha, and it's much easier to set up and reason with. The documentation is also a great improvement. Thank you!

However, I'm encountering an issue with using multiple sortable containers on Chromium mobile browsers. This issue doesn't occur on Safari or Firefox.

## Expected Behaviour

Dragging an item from sortable column A over column B should drop the item into column B. This works correctly when using a mouse pointer.

https://github.com/user-attachments/assets/70da7346-be6e-4309-a439-c7ac0e4d83e6

## Current Behaviour

When using a touch pointer, the dragged item gets stuck in a drag state once it is placed into column B's stack, even after releasing the item.

https://github.com/user-attachments/assets/f0223a83-9b88-402f-b661-00c60f90baa6

https://github.com/user-attachments/assets/a0f96370-9738-4ce2-b29b-6b96e165ea87

## Steps to Reproduce

1. Navigate to the multiple sortable list example in [Storybook](https://experimental--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/react-sortable-multiple-lists--debug)
2. Enter device emulation mode as a mobile device
3. Drag an item between columns
4. Observe that the item gets stuck in a draggable state and is not placed in either column

### Environment:

Desktop browser: Chrome 127 on macOS (Sonoma)
Mobile browser: Chrome 127 on Android 14

**Comment by clauderic** [comment]
Fixed by https://github.com/clauderic/dnd-kit/commit/f219549087d9100cee53ab0cf35d820fe256aa85

**Comment by justinnais** [comment]
Cheers 🙏
