### ISSUE TITLE
Sortable in @dnd-kit/dom is unusable

### ISSUE THREAD

**Issue by baiye0** [clauderic/dnd-kit#1467]
Module '"@dnd-kit/dom"' has no exported member 'Sortable'.
![image](https://github.com/user-attachments/assets/b5767db6-c622-4aca-86c2-c6d97f0f79db)

**Comment by kaaappi** [comment]
i think u need to install 
`npm install @dnd-kit/sortable`
and import from there

maybe check this link [https://docs.dndkit.com/presets/sortable](url)

**Comment by JiuRanYa** [comment]
hi, I have the same problem. I using the vanilla version. Link here: https://next.dndkit.com/concepts/sortable

**Comment by JiuRanYa** [comment]
I just check the code, you need to import as this:  `import { Sortable } from '@dnd-kit/dom/sortable'`

**Comment by clauderic** [comment]
Updated in https://github.com/clauderic/dnd-kit/commit/b5e5962ea690f3338b67186b477ae64e238af30f, sorry about that!

As @JiuRanYa mentioned, you need to `import { Sortable } from '@dnd-kit/dom/sortable'`
