### ISSUE TITLE
Drag and Drop not working when screen reader is on

### ISSUE THREAD

**Issue by Nayeemuddin-khan** [clauderic/dnd-kit#147]
I am using dnd-kit library and overall I am really impressed with it.  :)
But facing issue when trying using drag and drop for my components when screen reader is on. 
Tested the same on the library given examples (storybook) and found the same behavior (drag and drop not supported when screen reader is on).
Tried searching a work around for this but didn't find anything.

_version using: 1.0.2_

**Comment by clauderic** [comment]
@Nayeemuddin-khan what screen reader are you using? Are there any errors in the console? Could you share a video?

**Comment by Nayeemuddin-khan** [comment]
@clauderic  I am using Mac voice over and windows screen narrator. 
No errors in console.

https://user-images.githubusercontent.com/39629476/112043519-bfe61380-8b16-11eb-91d6-314bfbb70709.mov

**Comment by clauderic** [comment]
@Nayeemuddin-khan to be clear, you are pressing the up / down arrow keys to move the item and nothing is happening?

Can you record your video with [KeyCastr](https://github.com/keycastr/keycastr) running so I can see what keys are being pressed?

**Comment by Nayeemuddin-khan** [comment]
@clauderic  Yes I am pressing up and down arrow key to move item. 
Tried using KeyCastr but the up and down arrow are not been captured in that when voice over is on.

_Note: The up and down arrow worked when dragging and dropping with our screen reader is on. The issue is reproducible when voice over is on and trying to use key board arrows to drag and drop._

**Comment by Nayeemuddin-khan** [comment]
@clauderic  Just wanted to check if you were able to reproduce this reported issue?
or do you need anything else from me?

**Comment by clauderic** [comment]
Hey @Nayeemuddin-khan, what options do you have enabled for VoiceOver navigation?

<img width="942" alt="Screen Shot 2021-04-02 at 11 06 10 AM" src="https://user-images.githubusercontent.com/1416436/113427652-7366c780-93a3-11eb-8698-6de6ced46401.png">


You added this note which was confusing:

>Note: The up and down arrow worked when dragging and dropping with our screen reader is on. The issue is reproducible when voice over is on and trying to use key board arrows to drag and drop.

Did you mean to say that the up/down arrows work when the screan reader is _off_?

**Comment by flora8984461** [comment]
Thank you @lynnntropy for sharing. I recently encounter this and I use Windows Narrator. If I turn off the scan mode by "CAP" key, it works fine including the proper announcement. Similar to NVDA. 

> Not sure if this is actually related to the issue OP had, but I just encountered something very similar with NVDA, so I figured I'd put this here in case someone else runs into the same thing. In my case, the problem was that NVDA defaults to browse mode, and has to be manually switched to focus mode for interacting with draggables to work (I think [nvaccess/nvda#14084](https://github.com/nvaccess/nvda/issues/14084) is related to this).

**Comment by sbaechler** [comment]
I have the same issue on Mac with VoiceOver. The keyboard handling is working as expected when VoiceOver is off. But if VoiceOver is on, then focus is moved to the previous/next element in drag mode. The placeholder element is left in the DOM. This can be reproduced both with Safari and Chrome.

(VoiceOver can be turned on by holding CMD + pressing the TouchId 3x)

**Comment by smassa-auditboard** [comment]
I was encountering the same issue with VoiceOver. Turns out, I had accidentally turned on [Quick Nav](https://support.apple.com/guide/voiceover/with-quick-nav-vo27943/mac). That changes how the arrow keys navigate the page, causing this issue. Turning off Quick Nav (pressing left and right arrow at the same time) makes this act as expected.
