### ISSUE TITLE
Sorting variable width items in a wrapping flex container (tag/chip list)

### ISSUE THREAD

**Issue by theenoahmason** [clauderic/dnd-kit#1473]
I love this library, we use it on several projects so first of all thank you @clauderic for the awesome work.

My latest use case is to make a sortable **tag/chip list**. It seems that this library only works when items are always the same width. Is there some combination of settings that will remedy this? I have tried all strategy methods. Would fixing this take the shape of a new strategy?

![image](https://github.com/user-attachments/assets/5a620d93-3ea4-4aaa-8595-967e4c13b4b5)

### Example:

> Note that this is forked from the main example and modified slightly to illustrate the issue.

https://codesandbox.io/s/currying-flower-88dkqq

**Comment by clauderic** [comment]
This is possible yes, you have to move the items in `onDragOver` and set `strategy` prop on `SortableContext` to a function that returns `null`.

https://codesandbox.io/p/sandbox/cocky-booth-vwds4p

**Comment by theenoahmason** [comment]
Brilliant. Thanks again 🚀
