### ISSUE TITLE
Transform property mismatches on dragged item with flex layout

### ISSUE THREAD

**Issue by Pravin1616** [clauderic/dnd-kit#1478]
I have implemented a flexbox layout and am using the dnd-sortable library for rearranging items. However, I'm facing an issue with the drag animation. It utilizes the transform property to move the dragged item to a new position. The problem occurs when the flex items have varying sizes—the drag animation adjusts to the size of the drop container, causing the item to resize during the drag process. I've shared my code on codesandbox. Can someone please check and help me resolve this issue?

Link to the codesandbox solution?
[https://codesandbox.io/p/sandbox/vigilant-lake-m2mdcr]

**Comment by m-kolomoyets** [comment]
@Pravin1616 

It was marked as completed. What was the issue and how did you fix it? CodeSandBox link is not working
