### ISSUE TITLE
Drag animation not working

### ISSUE THREAD

**Issue by andreicorpo** [clauderic/dnd-kit#158]
Hi, I am new to this library and it looks pretty cool, great job!

But it appears the animation for dragging items in a sortable list is not visible when using `@dnd-kit/scrolable: 1.0.2 or 1.1.0`.

E.g:  https://codesandbox.io/s/dreamy-bhaskara-pb9sn

It is working though with with `@dnd-kit/scrolable: 1.0.1`.

E.g: https://codesandbox.io/s/recursing-greider-je2q6

Let me know if you need more information. Thank you.

**Comment by clauderic** [comment]
There's an issue with the `@dnd-kit/modifiers` package, upgrade to version `^1.0.3` or higher https://codesandbox.io/s/sleepy-shaw-7y47n?file=/src/App.js

**Comment by clauderic** [comment]
Turns out this was actually an issue in CodeSandbox 😅   https://github.com/codesandbox/codesandbox-client/pull/5609
