### ISSUE TITLE
CollisionDetectionStrategy - add draggable id

### ISSUE THREAD

**Issue by roeycohen** [clauderic/dnd-kit#162]
Hi!

on my scenario, not all draggables suits all droppables (working on a sortable tree, when parents can't be dragged into children).

It would be nice to add the dragged element id to the "customCollisionDetectionStrategy" function.
currently it exists only for "rects" parameter but not in "rect.
(see https://docs.dndkit.com/api-documentation/context-provider/collision-detection-algorithms#custom-collision-detection-strategies)

hope i was clear enough :)
10x for this great library!

**Comment by roeycohen** [comment]
Of course it's possible to get the moving draggable id with onDragStart event, but it still can be a nice addition :)

**Comment by clauderic** [comment]
As mentioned by @roeycohen, this can be achieved fairly easily if you keep track of the active `id` in `onDragStart`.

Something like:

```js
import React, {useCallback, useState} from 'react';
import {closestCenter, DndContext} from '@dnd-kit/core';

function MyComponent() {
  const [activeId, setActiveId] = useState(null);
  const customCollisionDetection = useCallback((entries, target) => {
    /* Custom collision detection with activeId */
  }, [activeId]);

  return (
    <DndContext
      collisionDetection={customCollisionDetection}
      onDragStart={(event) => setActiveId(active.id)}
      onDragEnd={() => setActiveId(null)}
    />
  )
}
```

Considering there is a fairly straightforward workaround, no plans to work on this in the near future, but feel free to open a PR.
