### ISSUE TITLE
'AutoScrollActivator' is not exported from '@dnd-kit/core'.

### ISSUE THREAD

**Issue by shayc** [clauderic/dnd-kit#163]
Hey @clauderic, thank you for your wonderful `dnd-kit`!

I've upgraded to v2.0 but get this error while trying to import:
![image](https://user-images.githubusercontent.com/6969966/112643531-82a2be00-8e55-11eb-90a8-18913354adfe.png)

This is my import statement:
```js
import {
  DndContext,
  useSensor,
  MouseSensor,
  TouchSensor,
  useSensors,
  AutoScrollActivator,
} from '@dnd-kit/core';
```

Am I doing anything wrong?

**Comment by clauderic** [comment]
Looks like I forgot to export it 😬

**Comment by shayc** [comment]
Happens to the best of us! Just wanted to share that we're experimenting with `dnd-kit` on [Cboard](https://github.com/cboard-org/cboard). Thanks for the hard work!

**Comment by shayc** [comment]
@clauderic after trying the `2.0.1` version, `AutoScrollActivator` was still not exported.
I've made a PR #166 that fixes this by omitting the `type` keyword from the export.
