### ISSUE TITLE
Sortable - onClick event fired when moving a SortableItem to a lower index 

### ISSUE THREAD

**Issue by lonk** [clauderic/dnd-kit#172]
Hi !

I'm facing an issue using sortable: when I'm moving a SortableItem from right to left, the onClick event is fired along the onDragEnd event. This isn't happing if I'm moving my item to the right.

Here is the simple sample of code I'm using:
``` 
              <DndContext
                    sensors={sensors}
                    collisionDetection={closestCenter}
                    onDragEnd={handleDragEnd}
                    modifiers={[restrictToParentElement]}
                >
                    <SortableContext
                        items={displayedArticles.map(article => article.id)}
                        strategy={rectSortingStrategy}
                    >
                        {displayedArticles.map(article => (
                            <Article
                                key={article.id}
                                name={article.name}
                                id={article.id}
                                onDeleteClick={() => {
                                    setArticleToDelete(article.id);
                                }}
                                onClick={() => console.log('onClick fired')}
                            />
                        ))}
                        <Add onClick={onOpen} />
                    </SortableContext>
                </DndContext>
```

And here is a video of what's happening:
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/2729398/112909698-3cb65600-90f2-11eb-9332-0d99237a5aee.gif)

Is this an expected behavior ? Do I miss something ?
Is there a way to completely silent onClick when the Item has been dragged ?

Thank you !

**Comment by lonk** [comment]
Hi @clauderic !

Thank you for your quick reply.

Your workaround doesn't work in my case because onDragEnd is fired before onClick so I think I'll go with the DragOverlay workaround :)

Have a nice day !

**Comment by tjunghans** [comment]
I have a similar issue with items in a grid, where the first item (cell) is larger than the rest. When dragging any item to the first  cell (top, left), the click event is fired. For any other re-order, the click event is not fired (as expected). This includes dragging the first cell to another position, which also works as expected.

I've tried the above suggestions without success. The click event is fired after dragEnd and DragOverlay creates new problems for me. I have one last idea and that is to track when the first cell is being replaced and ignore the first click after drag start.

**Comment by firede** [comment]
> onClick event fired when moving a SortableItem to a lower index

Got the same issue, I created a CodeSandbox: <https://codesandbox.io/s/sortabletabs-without-dragoverlay-vg3vg?file=/src/SortableTabs.tsx>

---

After that, I forked this and uses `DragOverLay`: <https://codesandbox.io/s/sortabletabs-with-dragoverlay-kdvgg?file=/src/SortableTabs.tsx>
Got a new issue, all the click events cannot be triggered.

**Comment by baptisteArno** [comment]
The issue is still here when using `<DragOverlay>`. So as far as I know there is no workaround.

Any idea of another workaround or how to approach this issue @clauderic? I could make a PR

**Comment by ShakurOo** [comment]
Same problem. The onClick event attached to the button inside my draggable element doesn't trigger anything :/

**Comment by Shajansheriff** [comment]
@ShakurOo @chickenwing i faced the same issue. One of my button inside draggable element has onClick and it wasn't working before, but I used this solution https://github.com/clauderic/dnd-kit/issues/296#issuecomment-849841749

**Comment by roks0n** [comment]
I faced the same issue and none of the suggestions in the comments seemed to have helped. Tried to find where the issue is but without much luck so far (I just started using the library today). As a **hacky workaround** I added a timeout into the onDragEnd callback. If I extend on the @clauderic's sample code in https://github.com/clauderic/dnd-kit/issues/172#issuecomment-810521878, I basically added:
```
function handleDragEnd() {
  setTimeout(() => setIsSorting(false), 0);
}
```

I'll update my comment in case I find a where the issue lies and how to fix it.

**Comment by Arkellys** [comment]
Hello, is this supposed to be fixed? Because I have the same issue...

**Comment by ChangeHow** [comment]
One more question:
It happens again after i wrappered DndContext with a div(or anyhting else) and bound with `onClick`.

A demo fork from https://github.com/clauderic/dnd-kit/issues/172#issuecomment-840380019

https://codesandbox.io/s/sortabletabs-with-dragoverlay-forked-wkdxf?file=/src/App.tsx

* And it's weird that if i drag item in a short distance, `onClick` would be never invoked.

**Comment by irtaza9** [comment]
@ChangeHow can you please share the dnd grid codesandbox Implementation. I've to implement the grid dnd in my project and have no idea about it.

**Comment by bxclib2** [comment]
This is a so basic feature. I don't understand why this is not include in the doc.

Besides, the author just close this issue, only leave us some very dirty and tricky solution...

I think this issue deserves someplace in the doc.
