### ISSUE TITLE
Help with multiple sortable containers

### ISSUE THREAD

**Issue by AndrisBorbas** [clauderic/dnd-kit#176]
I am trying to create a multiple zoned grid but anytime I try to move an item from one zone to the other it either crashes or the item just disappears. I have been trying to make this work for days now, but I can't do it. I tried copying from the storybook example , with no luck. 
Here is the relevant code, but the whole repo can be cloned and built to reproduce the issue: https://github.com/AndrisBorbas/destiny-launcher/blob/dev/src/components/banner/BannerSection.tsx

Also I never managed to get the empty droppables to work, onDragOver never fires when moving over an empty droppable.

Could anyone help me with this?

**Comment by clauderic** [comment]
> Also I never managed to get the empty droppables to work, onDragOver never fires when moving over an empty droppable.

Do your empty droppables have a computed height or width that is greater than zero when empty? 

> Could anyone help me with this?

Perhaps others can jump in on this. I personally don't have time to jump into other folks repositories, clone them, install dependencies and figure out how to run the project and finally try to understand all of its moving pieces and dependencies.

The best way for me to assist you is by opening an issue with a link to a CodeSandbox that contains the minimum amount of code necessary to replicate the issue you are facing.

**Comment by AndrisBorbas** [comment]
In the array that shows all the droppables, it is there with correct height and width values. 
I'll try to create a codesandbox of the issue, but the file I linked is the whole thing.

**Comment by jonasHChristiansen** [comment]
I experienced this as well. My workaround is to use a custom collision detection strategy when the div is empty

**Comment by AndrisBorbas** [comment]
I had some spare time to work on this and I managed to make it work by only using one array, with the ids and data both inside it. But I still cant drop items into empty droppables. @Joe-HC could you show me an example of your workaround?
