### ISSUE TITLE
More Detail from DragEndEvent?

### ISSUE THREAD

**Issue by mcookdev** [clauderic/dnd-kit#189]
Is it possible to get more than just the `id` of the `active` and `over` components from the `DragEndEvent`?

For context I'm trying to use `@dnd-kit/sortable` to implement drag/drop columns in a table that supports _multiple_ levels of headers (basically grouped headers).

In order to find and update the the proper item in the column I need some way to know the hierarchy/parents of the active item. I can easily pass that to the component, but I cannot easily get it to my event handler.

**Comment by clauderic** [comment]
Not yet, but coming soon, refer to this issue https://github.com/clauderic/dnd-kit/issues/139#issuecomment-814178995
