### ISSUE TITLE
When add a new Object to the sortable array's head, the animation is wrong

### ISSUE THREAD

**Issue by hzura** [clauderic/dnd-kit#192]
I'm using dnd-kit because the animation is cool, but I find sometimes it does'nt show the correct animation, here is the situation:
when I first sort the array and then unshift a new object to the array's head, the animation is wrong. all animation's first frame is their original position, not the position that it has been sorted.
here is the sandbox:
https://codesandbox.io/s/dnd-kit-grid-problem-fixed-forked-xcy4y?file=/src/SortableGrid.js
I hope that someone can help me about it, thanks!

**Comment by clauderic** [comment]
Use the `layoutMeasuring` prop of `DndContext` and set it to:

```tsx
import {DndContext, LayoutMeasuringStrategy} from '@dnd-kit/core';

<DndContext 
  layoutMeasuring={{
    strategy: LayoutMeasuringStrategy.Always,
  }}
```

https://codesandbox.io/s/dnd-kit-grid-problem-fixed-forked-ekjc1?file=/src/SortableGrid.js
