### ISSUE TITLE
Linting/Build Error

### ISSUE THREAD

**Issue by adaptedbee** [clauderic/dnd-kit#193]
![image](https://user-images.githubusercontent.com/14358216/114227963-64bd7900-997e-11eb-9213-d8a02c391425.png)
I'm getting error doing linting or building

I guess the problem is: [https://stackoverflow.com/questions/59833120/parsing-error-expected-in-import-type](https://stackoverflow.com/questions/59833120/parsing-error-expected-in-import-type), and that syntax is still [not supported](https://github.com/typescript-eslint/typescript-eslint/issues/1436)

**Comment by clauderic** [comment]
Check your version of `typescript-eslint`, that syntax is supported https://github.com/typescript-eslint/typescript-eslint/pull/1697

**Comment by adaptedbee** [comment]
@clauderic I installed the latest version, still the same error

**Comment by clauderic** [comment]
Are you certain your project is failing to compile because of `typescript-eslint`? Doesn't look like that's necessarily the case from the screenshot you posted above.

**Comment by adaptedbee** [comment]
@clauderic 
Linter shows multiple errors 
![image](https://user-images.githubusercontent.com/14358216/114229300-4d7f8b00-9980-11eb-9453-fb1689d3aded.png)
And no errors after removing the library

**Comment by clauderic** [comment]
What version of `typescript` do you have in your `package.json`, `yarn.lock` /` package-lock.json` files?

**Comment by adaptedbee** [comment]
"typescript": "^3.7.4",

"@typescript-eslint/eslint-plugin": "^4.21.0",
"@typescript-eslint/parser": "^4.21.0",

**Comment by clauderic** [comment]
You have to use `typescript^3.8.x`

**Comment by adaptedbee** [comment]
It looks like it helped, thank you!
