### ISSUE TITLE
Add documentation for LayoutMeasuringStrategy

### ISSUE THREAD

**Issue by nicolaerusan** [clauderic/dnd-kit#200]
I was just following along with the `Pages` example, and noticed mention of the `LayoutMeasuringStrategy`. I went to the docs to understand it's recommended usage is but saw it's not mentioned there yet. I think it might be helpful to add a quick section in the docs on this, as it seems it's also solved a few people's animation issues recently.

(sidebar: we're really enjoying using dnd-kit, so great work :) )

**Comment by clauderic** [comment]
https://docs.dndkit.com/api-documentation/context-provider#layout-measuring
