### ISSUE TITLE
Help - Documentation - Button inside a draggable

### ISSUE THREAD

**Issue by mihainsto** [clauderic/dnd-kit#203]
Hello, I want to have a button inside a draggable and it does not work as expected, you have to click multiple times for it to work.
Take a look in this sandbox: https://codesandbox.io/s/dnd-kit-button-glj0t?file=/src/App.js

Any ideas? Thanks

**Comment by clauderic** [comment]
Set an [`activationConstraint` on your PointerSensor](https://docs.dndkit.com/api-documentation/sensors/pointer#activation-constraints) 

https://codesandbox.io/s/dnd-kit-button-forked-71g2g?file=/src/App.js
