### ISSUE TITLE
Unable to trigger drag event after clicking any draggable element with PointerSendor

### ISSUE THREAD

**Issue by dzcpy** [clauderic/dnd-kit#216]
Example:
https://codesandbox.io/s/test-dnd-kit-forked-myy7t
Every tag is draggable until you click one of them.
However it used to work with an old version of this library:
https://codesandbox.io/s/test-dnd-kit-forked-qyjw2

**Comment by clauderic** [comment]
Seems like a regression in `@dnd-kit/core`, investigating

**Comment by clauderic** [comment]
Fix in progress here https://github.com/clauderic/dnd-kit/pull/217

**Comment by clauderic** [comment]
Fix has shipped with `@dnd-kit/core@3.0.1`, confirmed that it solves the issue: 

https://user-images.githubusercontent.com/1416436/115492706-4d10ab00-a230-11eb-866c-3e179bf19158.mp4

**Comment by clauderic** [comment]
I wanted to update the CodeSandbox to show you the issue being fixed there, but there's a bug with the package version resolution of CodeSandbox 🙈  It's resolving to `@dnd-kit/core@3.0.0` even if you specify `^3.0.1`; this bug only happens in CodeSandbox, not if you download the code and run it locally.

Opened an issue here https://github.com/codesandbox/codesandbox-client/issues/5687

**Comment by dzcpy** [comment]
@clauderic Thanks, that was really quick! ✨
Tested on my side and it's working now 👍
