### ISSUE TITLE
How to make a 'passive' sortable list?

### ISSUE THREAD

**Issue by heroboy** [clauderic/dnd-kit#219]
The 'passsive' I mean is the items position change is not caused by the user drag and drop. 
My code sort the items, and let this library to do the transition animation.

I looked at your `Removable` example, its animation working. But when I write my code, it's not working. I have add code like:
```
layoutMeasuring={{ strategy: LayoutMeasuringStrategy.Always }} 
animateLayoutChanges: () => true
```
But when I sort the items, or remove an item, there's no animation

**Comment by clauderic** [comment]
Refer to https://github.com/clauderic/dnd-kit/discussions/108#discussioncomment-524987

If you run into issues, [open a new discussion](https://github.com/clauderic/dnd-kit/discussions/new) under `Q&A` with a link to a CodeSandbox that replicates the issue you are having.
