### ISSUE TITLE
same code works in old version but not in new

### ISSUE THREAD

**Issue by kelvindc** [clauderic/dnd-kit#220]
Hi, does this newest 3.0.2 work with React 17?

I took this example from sampl:
https://codesandbox.io/s/dnd-kit-flex-wrap-layout-yt4rv

upgrade it to newest 3.0.1, react 17.0.2:
https://codesandbox.io/s/dnd-kit-flex-wrap-layout-forked-wrjig

with a few minor changes:
1) remove fade={isDragging} to disable isDragging=null error
2) CardsWrapper: remove flowDirection:column
3) strategy: use rectSortingStrategy

and it just stop working.

I tried to build another newest version of the same code, the dragging works but only for top 1 row:
https://user-images.githubusercontent.com/2488106/115527362-91995680-a2c3-11eb-93be-a0a5bd3b5fd4.mov

**Comment by clauderic** [comment]
Hi @kelvindc,

This is a bug in CodeSandbox. Multiple versions of `@dnd-kit/core` end up being included in that sandbox, which results in the code not working. 

If you download the sandbox, run `yarn install && yarn start`, the code works fine:

<img width="416" alt="Screen Shot 2021-04-21 at 9 47 58 AM" src="https://user-images.githubusercontent.com/1416436/115564658-aacfe200-a286-11eb-8aad-bfdfe33e9be4.png">

I opened an issue in CodeSandbox here https://github.com/codesandbox/codesandbox-client/issues/5687#issuecomment-824073854
