### ISSUE TITLE
SortableContext item with percentage width

### ISSUE THREAD

**Issue by bellybailey** [clauderic/dnd-kit#221]
First of all, I want to thank you for building this amazing library.

In my current project, I would like to use drag and drop on items which have percentage width. For example:

https://codesandbox.io/s/test-dnd-kit-forked-q2m6u

However, when I click on an item to drag, the item width shrinks:

![image](https://user-images.githubusercontent.com/82514004/115547776-caa0ed80-a2fa-11eb-99e0-cddf4c783f44.png)

I was wondering if there is a way to make the width of the dragged item the same as its original width?

Thanks very much.

**Comment by clauderic** [comment]
https://codesandbox.io/s/test-dnd-kit-forked-rjbuo?file=/src/Item.js

The trick is to add `width: 100%` to the `item` rendered by `<DragOverlay>`
