### ISSUE TITLE
Droppables will randomly interact when dragging over empty space on the bottom of scrolled container

### ISSUE THREAD

**Issue by ohayojp** [clauderic/dnd-kit#239]
When droppables are in scrolled container, dragging over bottom area (place for padding/margin) when this container is scrolled will cause those droppables to interact randomly and React will start throwing `Maximum update depth exceeded` error resulting in freeze at some point. 
If you remove elements or increase the window size to remove the scroll this won't happen.

https://user-images.githubusercontent.com/6364234/116394319-0d932180-a823-11eb-9f0f-433f62674180.mov

Codesandbox: https://codesandbox.io/s/restless-hooks-zjyht - just scroll down and drag element from left palette under the table.

**Comment by clauderic** [comment]
There's a bit too much going on in this sandbox for me to fully diagnose if this is a bug in the library or just user-error;

However, it looks like you have double scrollbars (one for the document body and one for the table wrapper), which is what is causing the issues you're seeing.

Commenting this out appears to solve the issue:

<img width="253" alt="Screen Shot 2021-04-28 at 12 08 05 PM" src="https://user-images.githubusercontent.com/1416436/116436765-b8531200-a81a-11eb-8dad-5f5a40076736.png">
