### ISSUE TITLE
Dragging Over Issue.

### ISSUE THREAD

**Issue by tarequl143** [clauderic/dnd-kit#244]
I have used dndkit multicontainer sortable but when I am dragging an item from one droppable container to over another droppable container its working but when I am doing it FAST its giving me error. That is from sortable context. I am attaching the screenshot. Is it an bug of dndkit please help if possible.

<img width="1077" alt="Screenshot 2021-04-30 at 5 59 55 PM" src="https://user-images.githubusercontent.com/33724412/116692656-88546c00-a9de-11eb-81a6-50f5ac1e39cd.png">

**Comment by clauderic** [comment]
Pleas open issues with a CodeSandbox reproducing the issue to receive help

**Comment by tarequl143** [comment]
I have solved out the issue. Thanks.
But I have another issue about click event. I want to make my draggable element clickable. But when I am clicking in my draggable element 4 or 5 time at a time with speedy clicking its making whole dragging disabled. After that I can'd drag my draggable element. Can you please help me about it?

**Comment by clauderic** [comment]
Please re-open as a [Discussion](https://github.com/clauderic/dnd-kit/discussions) under `Q&A` with a CodeSandbox reproducing the issue to receive help

**Comment by tarequl143** [comment]
Its simple. I want to make my draggable element as a link. How can i do this?
