### ISSUE TITLE
Columns > 3 and vertical true on MultipleContainers

### ISSUE THREAD

**Issue by MSchiavi** [clauderic/dnd-kit#247]
If columns are greater than 3 and vertical is true, if i empty one of the item lists by dragging items out you can no longer put items into that list. I attached a gif of the behavior reproduced in the MultipleContainers.story.tsx. 

https://gyazo.com/5b7b04d660bb5fe37cdc3913ec52fd6e

**Comment by clauderic** [comment]
Try with the `closestCenter` collision detection algorithm.

This isn't a bug, it's just how the `closestCorners` collision detection algorithm works, it's not optimized for that use-case. Read more here https://docs.dndkit.com/api-documentation/context-provider/collision-detection-algorithms#closest-corners
