### ISSUE TITLE
useDraggable has no listeners if there are no droppables

### ISSUE THREAD

**Issue by clauderic** [clauderic/dnd-kit#25]

**Comment by mitchheddles** [comment]
Hey @clauderic I know this is an old ticket, but I'm seeing this issue with `useSortable`.

Do you know what causes this or have any tips for debugging? It looks like `useDraggable` is getting the default context value.

<img width="785" alt="Screen Shot 2021-04-15 at 12 28 57 pm" src="https://user-images.githubusercontent.com/20656128/114805432-5b9d3380-9de6-11eb-95e1-47293ad5bbc2.png">

I don't think there's anything special about my usage:

```tsx
const sensors = useSensors(
  useSensor(PointerSensor),
  useSensor(KeyboardSensor, {
    coordinateGetter: sortableKeyboardCoordinates,
  }),
);

<DndContext sensors={sensors}>
  <SortableContext items={sortedStatuses} strategy={verticalListSortingStrategy}>
    {sortedStatuses.map((idx) => {
      const status = statusMap[idx];

      return <SettingsStatusListItem key={idx} id={idx} boardIdx={board.idx} status={status} />;
    })}
  </SortableContext>
</DndContext>;

```

**Comment by clauderic** [comment]
This happens when you have multiple versions of `@dnd-kit/core` installed locally. Double check your `package-lock.json` or `yarn.lock` files, you most likely have multiple versions installed in parallel.

Refer to this issue for more debugging steps https://github.com/clauderic/dnd-kit/issues/182

**Comment by mitchheddles** [comment]
@clauderic That did it, thanks pal!
