### ISSUE TITLE
Cursor offset with draggable item when dragging and scrolling

### ISSUE THREAD

**Issue by namroodinc** [clauderic/dnd-kit#252]
Similar to this issue (which I think has a great video showing the issue): https://github.com/clauderic/dnd-kit/issues/86

If you select a draggable item and either scroll vertically, the cursor and the point from which you were dragging the item end up having an offset.

I've got a Code Sandbox going: https://codesandbox.io/s/compassionate-carson-y1f0h

You can replicate the above by dragging the top table row and scrolling down, or bottom table row and scrolling up. Is there any way to fix this?

Many thanks!

**Comment by clauderic** [comment]
You have to track scroll offsets yourself if you don't use the [`<DragOverlay>` component.](https://docs.dndkit.com/api-documentation/draggable/drag-overlay)

> If your draggable item is within a scrollable container, we also recommend you use a <DragOverlay>, otherwise you'll need to set the draggable element to position: fixed yourself so the item isn't restricted to the overflow and stacking context of its scroll container, and can move without being affected by the scroll position of its container.

**Comment by Croden** [comment]
Issue is actually by having scroll on <html /> instead of <body />
