### ISSUE TITLE
Provide data to CollisionDetection functions

### ISSUE THREAD

**Issue by wmain** [clauderic/dnd-kit#255]
Loving the improved ergonomics of the `data` field on sortables/draggables! Performance for our case would be greatly improved if that data was available in our custom collision detection function so that we don't have to continue encoding information about our objects in our unique identifiers. At a minimum we'd like target, which is currently a `ViewRect`, to be a `RectEntry` so that we can extract that information from the target's id.

Alternatively (and this may be better), changes to `disabled` in our components consuming `useSortable` could propagate during the drag so that those changes would correctly filter the list of entries once the drag has begun.

**Comment by clauderic** [comment]
Agreed, this would be a worthy addition. I originally planned to do this in the 3.0.0 release but decided to defer that to the next major version bump.

Don't have bandwidth to work on this in the short term but I should pick this up in a couple of weeks unless someone opens a PR.

**Comment by wmain** [comment]
@clauderic I might take a stab at implementing this. Would love al little guidance, though, namely regarding: Should `RectEntry` be updated or should the signature of `CollisonDetection` change to some new type that is `[RectEntry, DataRef]`? The first doesn't seem "correct," but the second is a breaking change, which doesn't feel great either.

**Comment by clauderic** [comment]
Yeah unfortunately this was a poor design decision on my part, this will require a breaking change. The `CollisionDetection` interface should more closely match something like this:

```ts
interface DraggableNode {
  id: UniqueIdentifier;
  node: MutableRefObject<HTMLElement | null>;
  data: DataRef;
  rect: ViewRect;
}

interface DroppableContainer { 
  id: UniqueIdentifier; 
  node: MutableRefObject<HTMLElement | null>;
  rect: LayoutRect;
  disabled: boolean;  
  data: DataRef;
}

type CollisionDetection = ({
  draggableNode: DraggableNode,
  droppableContainers: DroppableContainer[]
}) => UniqueIdentifier;
```
