### ISSUE TITLE
iPad iOS 12: Items can be Dragged, but not Dropped

### ISSUE THREAD

**Issue by fabb** [clauderic/dnd-kit#256]
On an iPad a drag can be started fine, but when removing the finger, the drag overlay keeps showing and the drag is not finished.
Reproducible in the example storybook: https://5fc05e08a4a65d0021ae0bf2-evxexveqfg.chromatic.com/?path=/story/presets-sortable-grid--basic-setup

![image (18)](https://user-images.githubusercontent.com/153960/117295235-e1575080-ae73-11eb-9b3e-4084b889fd8b.png)

Reproduced on an iPad Air 2 with iOS 12.4.1.

**Comment by fabb** [comment]
It looks like this is a known issue in the iOS world and additionally listening to `touchendoutside` could solve it:
https://github.com/pixijs/pixi.js/issues/6191#issuecomment-575129079

**Comment by clauderic** [comment]
`touchendoutside` [is not something that is part of the Touch events specification](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events), it's something specific to PixiJS.

The issue probably has to to do with the Storybook iframe document losing focus, and therefore no longer receiving touch events. If you give focus back to the iframe things should work as expected.

It should be possible to listen to the `blur` event of the `window` in `AbstractPointerSensor` however to cancel the drag operation

**Comment by fabb** [comment]
I have the same issue on my page where i don‘t use iframes. I read that iOS has issues when the touches end on a different element than they start, so maybe it‘s related to the drag overlay?

Unfortunately i currently don‘t have an ipad to debug the issue in depth, a remote colleague reported the issue.

**Comment by fabb** [comment]
We retested with an iPad with iOS 14, and there it works correctly. Also on iOS 12 with the example `Without Drag Overlay` it works correctly, so I guess iOS 12 has some bug with touch-up events happening on different elements than the previous touch-down.
