### ISSUE TITLE
Is dnd-kit production ready?

### ISSUE THREAD

**Issue by Donorlin** [clauderic/dnd-kit#257]
Good day sir, 

More of a question than an issue (kind of both).. is this package production ready? Since your logo says beta I assume it should not be used in production.. however, this package is exactly what I need.

Thanks for your answer.

DJ

**Comment by clauderic** [comment]
The library is labeled as beta, meaning that some issues and bugs should be expected. The core concepts are stable, but some of the APIs may change in the future.

You can take a look at the open issues, most issues currently are related to advanced use-cases, so for many simpler use-cases, especially those that [are documented in the examples](http://examples.dndkit.com/), the library should be production ready.
