### ISSUE TITLE
DragOverlay for table row loses cell spacing

### ISSUE THREAD

**Issue by rawcomposition** [clauderic/dnd-kit#266]
When the `position:fixed` CSS property gets applied to the DragOverlay element with `wrapperElement="tr"`, the row cells lose their spacing, and they all end up squished to the left side. What is the recommended workaround for this? Seems like sorting table rows is a fairly common use case, so I assume there must be some kind of workaround?

**Comment by clauderic** [comment]
You probably need the `wrapperElement` to be `table`

**Comment by rawcomposition** [comment]
The `wrapperElement` of `DragOverlay` surrounds the actively dragging element, not the entire list. My list is already surrounded with a `table` element. Here's a page discussing how `react-beautiful-dnd` handles it. They have a "dimension locking" option to keep the cells the same size while dragging: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/tables.md

**Comment by clauderic** [comment]
Perhaps you could open a CodeSandbox replicating the issue you are facing to illustrate.

`<DragOverlay>` applies a fixed `width` / `height` to the wrapper element it renders, which should match the width and height of the row you are currently dragging.

I'd recommend always rendering the `<DragOverlay>` component in a portal, in which case you need your row to be wrapped in a `table` wrapper element, otherwise you'll have invalid HTML (`body > td` instead of `body > table > tr`)

**Comment by rawcomposition** [comment]
I'll work on getting a CodeSandbox setup to recreate the issue. The fixed width/height of the row is not the problem, it's the sizing of the cells within the row. Dnd-kit applies a `position: fixed` attribute to the row, which causes it to lose the context of of the other rows, so the width of the individual cells inside the row no longer matches the table. See article here, discussing a similar problem: https://css-tricks.com/position-sticky-and-table-headers/

If I did set the wrapper element to a `table`, again, my row will lose the context of the rest of the table, so the individual cells won't be aligned with the other columns in the table. Using fixed width cells solves the problem, but having the auto cell sizing is nice sometimes.

Here's an example, where I've drug an element below the table so you can see how it compares to the "shadow" of where I drug it from.
<img width="1214" alt="Screen Shot 2021-05-12 at 12 34 50 PM" src="https://user-images.githubusercontent.com/740090/118012008-9d09fb80-b31e-11eb-9e8d-403c6b65e04b.png">

If I add `display: table` to the DragOverlay wrapper, it starts to look better, but the sizing of the cells still doesn't match the original table.
<img width="1215" alt="Screen Shot 2021-05-12 at 12 35 25 PM" src="https://user-images.githubusercontent.com/740090/118012005-9c716500-b31e-11eb-8b9d-ade8e46c8422.png">

**Comment by clauderic** [comment]
Thanks @rawcomposition, this is helpful context. I don't think this is something that should natively be part of `@dnd-kit/core`, it's a fairly advanced use-case and it adds a lot of complexity to the codebase to try to support this.

You could create an abstraction yourself to measure the size of each table cell for the row being dragged and propagate those measurements to the component you render within `<DragOverlay>` however.

**Comment by clauderic** [comment]
Something like this would probably work (untested):

```ts
function DragOverlayRow() {
   const {active} = useDndContext();
   const columnWidths = useMemo(() => {
     if (!active || !active.node.current) { return; }
     
     const columns = Array.from(active.node.current.querySelectorAll('td'));
     const widths = columns.map(column => column.getBoundingClientRect().width);
     
     return widths;
   }, [active]);
   
   return <Row columnWidths={columnWidths} />
}
```

**Comment by rawcomposition** [comment]
Makes sense, and thanks for the sample code, that should give me a good head start!

**Comment by larissa-n** [comment]
@clauderic Is this still the case, `dnd-kit` does not support tables out of the box like `react-beautiful-dnd` does? Thank you!
