### ISSUE TITLE
mobile looses scroll focus on sortable items within scrollable div

### ISSUE THREAD

**Issue by augustblack** [clauderic/dnd-kit#272]
Hi,

There seems to be some weird behavior on mobile interfaces that require touch/pointer input and sortable items within a scrollable container div.

When you first load the page, you can scroll the list of items within the div.
As soon as you stop scrolling the first time, the div is not scrollable any more.

You can see this behavior on all of the examples.  Try loading the following on a mobile device:

https://5fc05e08a4a65d0021ae0bf2-pmliirrbge.chromatic.com/?path=/story/presets-sortable-vertical--scroll-container

**Comment by augustblack** [comment]
to add a bit more info, I think the problem is that having a sortable list inside of a scrollable container on mobile presents a significant challenge.

On mobile, the pointer device is used for both clicking and scrolling.  If you view the following on mobile, you can only drag and rearrange the list, you cannot scroll it:

https://5fc05e08a4a65d0021ae0bf2-pmliirrbge.chromatic.com/?path=/story/presets-sortable-vertical--scroll-container

Adding a drag handle should make sense for this use case, and the following works fine on mobile:

https://5fc05e08a4a65d0021ae0bf2-pmliirrbge.chromatic.com/?path=/story/presets-sortable-vertical--drag-handle

In the above, you can scroll the list and drag/drop/sort individual items.

The problem comes when you try the sortable-vertical--drag-handle above when the outer container is constrained in height.

I think the problem should be illustrated if you were to add this to the storybook:

export const RestrictToScrollContainerWithHandle = () => (                                                                                                                       
  <div
    style={{
      height: '50vh',
      width: 350,
      margin: '200px auto 0',
      overflow: 'auto',
    }}
  >
    <Sortable {...props} modifiers={[restrictToFirstScrollableAncestor]} handle />
  </div>
);

(Note: I can't test the story above because the storybook won't build for me)

**Comment by augustblack** [comment]
After further investigation, I think the issue can be solved by preventing the touch events on mobile from bubbling up to the parent container ( eg adding touch-action: none to the parent)

**Comment by HoussemDjeghri** [comment]
Hi @augustblack, I'm having the same issue, could you send a code example on how you managed to fix it ? 
Thanks.

**Comment by clauderic** [comment]
@HoussemDjeghri if you are using the TouchSensor, this should not be an issue, at least in the [versions of `@dnd-kit` tagged with `@next` on npm](https://github.com/clauderic/dnd-kit/pull/342#issuecomment-871842286).

For the Pointer sensor, you absolutely must specify `touch-action: none` on the draggable element to prevent scrolling on mobile, refer to the docs around this here: https://docs.dndkit.com/api-documentation/sensors/pointer#touch-action

**Comment by HoussemDjeghri** [comment]
Hi @clauderic, thanks for the answer, I'm using the version 2.1.2 of dnd-kit/core so it's not tagged with @next, and for `touche-action:none` I have added it on the parent div like @augustblack proposed, but I still can't scroll down the parent div on touch devices, here is how my code looks like ( I also tried adding `touche-action:none` to the SortableItem css but nothing ) 

```
<Box style={{overflowY:"scroll"}}>
               
         OTHER LONG CONTENT .......
              
         <Box style={{touchAction:"none"}}>
                <DndContext
                  sensors={sensors}
                  autoScroll={false}
                  collisionDetection={closestCenter}
                  onDragEnd={handleDragEnd}
                >
                  <SortableContext
                    items={items}
                    modifiers={[restrictToVerticalAxis]}
                    strategy={verticalListSortingStrategy}
                    handle
                  >
                    {items.map(id => (
                      <SortableItem
                        setOrder={handleOrderChange}
                        index={items.indexOf(id)+1}
                        total={items.length}
                        key={id}
                        id={id}
                        family={familiesDetails.find((family)=>family.id===id)}
                      />
                )
                )}
                  </SortableContext>
                </DndContext>
          </Box>
 </Box>

```

**Comment by HoussemDjeghri** [comment]
@clauderic can you check my code please it's urgent. Thanks

**Comment by archisvaze** [comment]
@clauderic "For the Pointer sensor, you absolutely must specify touch-action: none on the draggable element to prevent scrolling on mobile". Thanks this was it! Adding this to the div that contained the draghandle stopped the glitchy dragyscroll that was happening.
