### ISSUE TITLE
[Request] support for ES5

### ISSUE THREAD

**Issue by yuri-scarbaci-lenio** [clauderic/dnd-kit#284]
Hello,

We need support for ES5, 
 would it be possible to support compilation to both `esm` and `cjs` ?
 
If I investigate how to add it and raise a PR, would you be willing to merge it?

thank you for the great library!

**Comment by yuri-scarbaci-lenio** [comment]
Sorry, I just reviewed the building process and configuration, I understand the library is already compiling both `cjs` and `esm` version, but "module" is pointing at the `esm` version as it should, problem was on our part, our webpack configuration should handle it, I will investigate the issue further on our side...

**Comment by clauderic** [comment]
Hey @yuri-scarbaci-lenio, going to close this issue as there doesn't seem to be anything actionable in the @dnd-kit repo. Feel free to re-open with more details if you find something that needs to be changed in the repository.
