### ISSUE TITLE
Sortable animations don't work on latest release.

### ISSUE THREAD

**Issue by tonyjara** [clauderic/dnd-kit#286]
Hi, I'm new to the library so excuse me if this is already being discussed. I couldn't find an open issue. 
Expected: https://codesandbox.io/s/mh95t?file=/package.json
Actual behaviour: https://codesandbox.io/s/dnd-kit-sort-demo-forked-irhhk?file=/package.json

**Comment by clauderic** [comment]
`id` must be a string, not a number https://codesandbox.io/s/dnd-kit-sort-demo-forked-r3n3e

**Comment by morgoth** [comment]
@clauderic Could you put some some light why it changed to be a string? I think it's common to have numeric ids in apps. I'm debugging problems with upgrade in my app and I'm not sure if it is caused by this change or not.

**Comment by clauderic** [comment]
The documentation always explicitly stated that the `id` for draggable / droppable / sortable items had to be a string. It was a happy accident if it was working.

**Comment by morgoth** [comment]
@clauderic I'm going through documentation and I cannot find a mention about a hard requirement about string items. I can see it in examples as strings, but I guess it might be a common mistake made by end users, even more that in the examples there is an "id" name used, which most of the time is numeric in apps.

Is it making some big problems in the code to support numeric items?

**Comment by clauderic** [comment]
This is documented in multiple places:

<img width="812" alt="Screen Shot 2021-05-25 at 12 07 46 PM" src="https://user-images.githubusercontent.com/1416436/119531376-d9dbe680-bd51-11eb-8d51-182cc8ad9d21.png">

[useDraggable](https://docs.dndkit.com/api-documentation/draggable/usedraggable)

<img width="827" alt="Screen Shot 2021-05-25 at 12 08 20 PM" src="https://user-images.githubusercontent.com/1416436/119531437-e82a0280-bd51-11eb-978c-3ebcc407c49b.png">

[useDroppable](https://docs.dndkit.com/api-documentation/droppable/usedroppable)

<img width="551" alt="Screen Shot 2021-05-25 at 12 08 51 PM" src="https://user-images.githubusercontent.com/1416436/119531493-fa0ba580-bd51-11eb-8c04-d44209bbe653.png">

[useSortable](https://docs.dndkit.com/presets/sortable/usesortable)


It's probably not a major change to support this, you're welcome to open a PR if you want this to happen.

**Comment by ThiefMaster** [comment]
String IDs are a huge mess for anyone whose data comes from a database.
