### ISSUE TITLE
3.0 changes event object in onDragOver

### ISSUE THREAD

**Issue by morgoth** [clauderic/dnd-kit#287]
I have something like:
```
const handleDragOver = (e) => { console.log(e) }
<DndContext onDragOver={handleDragOver}>
<DndContext
```
In the 3.x version I'm getting an object with active, delta and over keys, but in 2.x it was object with keys: active, draggingRect, droppableRects over.

I don't see such change on https://github.com/clauderic/dnd-kit/releases/tag/%40dnd-kit%2Fcore%403.0.0 and I'm not sure how to upgrade.

Is this a bug or intentional change?

**Comment by clauderic** [comment]
Hey @morgoth, this was an intentional change. What properties were you using before that you're trying to migrate from?

**Comment by morgoth** [comment]
I'm sorry, that I can't get detailed issue description, but I'm new to this part of code in our application.
This now fails (which I believe checks if draggins is done "below target":
`draggingRect.offsetTop > over.rect.offsetTop + over.rect.height`

**Comment by clauderic** [comment]
Replace with:
```ts
active.rect.current.translated.offsetTop > over.rect.offsetTop + over.rect.height;
```

**Comment by morgoth** [comment]
Thanks, that helped. Now I'm debugging other issues with upgrade.

**Comment by ABSanthosh** [comment]
@clauderic 
Now in a project with these versions, the `offsetTop` key is not available.
```Javascript
"@dnd-kit/core": "^5.0.1",
"@dnd-kit/sortable": "^6.0.0",
"@dnd-kit/utilities": "^3.1.0",
```

Instead, the `active.rect.current` object returns
```javascript
{
    initial: {
      top: 313,
      left: 21.5,
      width: 268,
      height: 100,
      bottom: 413,
      right: 289.5,
    },
    translated: {
      top: 438,
      left: 164,
      width: 268,
      height: 100,
      bottom: 538,
      right: 432,
    },
  };
```

Trying `top` key in place of `offsetTop` doesn't seem to work too.
I tried updating the packages and making this change in this [codeSandBox](https://codesandbox.io/s/lknfe?file=/src/app.js) of yours but its showing error.
