### ISSUE TITLE
@dnd-kit/core upgrade can't drag

### ISSUE THREAD

**Issue by me82852578** [clauderic/dnd-kit#289]
When I upgrade `@dnd-kit/core` from version `3.0.1` to `3.0.2` or `3.0.3`, my component can't drag. 
Then I back to version `3.0.1` and the problem solved.
Maybe something wrong in 3.0.2 or 3.0.3 ?

**Comment by clauderic** [comment]
Kind of hard to help you without more details. Can you share the code?

**Comment by h0liday** [comment]
I`ve faced the same issue after upgrade to 3.0.2 from 3.0.0.

**Comment by clauderic** [comment]
Closing this issue, most likely due to having multiple versions of `@dnd-kit/core` installed locally. This should be less of an issue now that we have moved `@dnd-kit/core` to `peerDependencies` of `@dnd-kit/sortable` and `@dnd-kit/modifiers` in #294 

Feel free to open with replication steps.
