### ISSUE TITLE
redundant rerenders - different objects equal by value

### ISSUE THREAD

**Issue by Logaqm** [clauderic/dnd-kit#290]
Im attempting to optimize performance for my application using [WDYR ](https://github.com/welldone-software/why-did-you-render)and I think ive found an area where a lot of unnecessary rerenders could be saved. Information is provided in the logs of the codesandbox, but it seems a ton of updates could be saved with a simple equity check before updating the transform. This is especially unnecessary in my use-case, since I am snapping to the grid and the widget should only need to rerender anytime a snap to a new point is detected.

https://codesandbox.io/s/objective-dew-g1o1z?file=/src/App.js
I dont reccomend dragging around for long, since the console spamming from WDYR destroys performance.
You can also disable WDYR above the export and enable the console log, which will give a count of how many times it has rerendered. This amount seems a big crazy to me, far more than is needed.  

I could also be entirely missing something here, feel free to school me.

**Comment by clauderic** [comment]
Could you elaborate on where in the code you think there are redundant re-renders that could be avoided? Feel free to open a PR

**Comment by clauderic** [comment]
Closing as there is more active discussion in https://github.com/clauderic/dnd-kit/issues/389
