### ISSUE TITLE
Vertical sort resizing issue

### ISSUE THREAD

**Issue by elohmrow-vscode** [clauderic/dnd-kit#292]
## The problem

When I drag these components and they are all the same size, it works fine as expected:

[![Image from Gyazo](https://i.gyazo.com/577239e803f06667ccd56d7de1838fbf.gif)](https://gyazo.com/577239e803f06667ccd56d7de1838fbf)

If I start dragging a component that was in a larger expanded state it breaks the animation (as expected):

[![Image from Gyazo](https://i.gyazo.com/5ff49216a64f29fa9b32587c15c6199f.gif)](https://gyazo.com/5ff49216a64f29fa9b32587c15c6199f)

## What I tried

I thought it would be a simple fix to auto-collapse all siblings when any sibling is being dragged. I simply check to see if there is an active component being dragged and collapse all of them:

[![Image from Gyazo](https://i.gyazo.com/7a883da91295cef11c31e8e48a62f985.gif)](https://gyazo.com/7a883da91295cef11c31e8e48a62f985)

## Relevant code

In my presentational component, this handles the animations for collapsing and expanding the component when dragging. `shouldExpand` controls whether the component is expanded, `collapse` is used to force the component to collapse, and `shouldCollapse` is used to collapse the overlay on render (this was necessary because the overlay is memoized afaik).

![image](https://user-images.githubusercontent.com/70706530/119597344-ae7aeb00-bd95-11eb-8c00-d0bef3fab777.png)

_Note: This is the best way I could figure out how to animate the collapse/re-expand behavior. If there is a better way, please let me know :)_

**Comment by clauderic** [comment]
Use `CSS.Translate.toString(transform)` instead of `CSS.Transform.toString(transform)`.

**Comment by elohmrow-vscode** [comment]
What is the difference between the different `CSS` utility functions? I don't see it in the API documentation.

**Comment by clauderic** [comment]
`Transform` applies `translatet3d() scale()` transformations whereas `Translate` only applies `translate3d()`
