### ISSUE TITLE
useDraggable onMouseDown handler swallows element's onClick event

### ISSUE THREAD

**Issue by shauntrennery** [clauderic/dnd-kit#296]
Given the code below, the handleClick is never called. Removing {...listeners} fixes the issue. It appears the `listeners.onMouseDown` prevents propagation of the event.

`<li
      onClick={handleClick}
      ref={setNodeRef}
      {...attributes}>
      {...listeners}
      <Content />
    </li>`

I've tried wrapping it with a div, wrapping Content with a div etc. 

Any advice / pointers would be greatly appreciated.

**Comment by clauderic** [comment]
Set an `activationConstraint` on the Mouse or Pointer sensor that is either based on `distance` or `delay`: https://docs.dndkit.com/api-documentation/sensors/pointer#activation-constraints

```ts
useSensor(PointerSensor, {
  activationConstraint: {
    distance: 10,
  },
});
```

**Comment by shauntrennery** [comment]
@clauderic sorry, I forgot to include my container's code in the snippet above:

`const pointerSensor = useSensor(PointerSensor, { activationConstraint: { distance: 10 } });
  const sensors = useSensors(pointerSensor);`

`<DndContext sensors={sensors}><ul...`

**Comment by clauderic** [comment]
Your issue describes `onMouseDown` handlers swallowing `onClick` events, but the Pointer sensor doesn't use `onMouseDown`, it uses `onPointerDown` 🤔 

Possibly a duplicate of #172?

Please consider opening a CodeSandbox replicating the issue for further assitance.

**Comment by shauntrennery** [comment]
Thank you for the prompt replies @clauderic. I'll share a CodeSandBox example shortly.

**Comment by shauntrennery** [comment]
@clauderic for your reference: [https://codesandbox.io/s/dndkit-k75i3?file=/index.tsx](https://codesandbox.io/s/dndkit-k75i3?file=/index.tsx)

It works 100% as expected. I'm trying to see what I'm doing wrong in my project.

**Comment by fulopdaniel** [comment]
Hey all,

I had the same issue, removing the DragOverlay solved it for me. I suppose it was something like onPointerDown is triggered, and the dragOverlay appeared on top of the button before the mouseUp event was triggered, so the button was never really clicked at all.
