### ISSUE TITLE
onDragEnd delta.y property inaccurate when inside position fixed container

### ISSUE THREAD

**Issue by rawcomposition** [clauderic/dnd-kit#298]
I've encountered an issue where the `delta.y` property on the `onDragEnd` callback of `DndContext` shows an incorrect result if the container element is inside an element that does not scroll with the page. The issue is much easier to show than explain, so I created a CodeSandbox for it: https://codesandbox.io/s/headless-glitter-54n1r?file=/src/App.js

In the real world, I'm trying to drag a little circle over an image and have the circle stay exactly where it is dropped. I was using the delta.x and delta.y properties to calculate the final CSS position based on the starting point and the width/height of the image. In my case, the image is inside a bootstrap modal, but for the codesandbox I just used a simple position:fixed div for demonstration purposes.

Is there a workaround for this? Or perhaps a better way to accomplish what I'm attempting to do?
I found a random codepen that shows what I'm trying to accomplish: https://codepen.io/vinsongrant/pen/QGodXV

**Comment by clauderic** [comment]
Hey @rawcomposition, currently there are bugs with position fixed items, I need to spend a bit more time reflecting on the best way to handle that use case as it will require a number of significant changes. Haven't had the headspace to prioritize that refactor yet

**Comment by nc** [comment]
+1

**Comment by nc** [comment]
Might there be something to apply in the interim to get it working again?

**Comment by rawcomposition** [comment]
@nc my very "hacky" solution was to subtract the scrollTop from delta.y. Since my modal was scrolling, I also had to subtract the modal scrollTop.

```
const modalScrollOffset = imgRef.current?.closest(".modal-content")?.scrollTop || 0;
const documentScrollOffset = document.documentElement.scrollTop;
const correctedDeltaY = delta.y - modalScrollOffset - documentScrollOffset;
```

**Comment by srmagura** [comment]
Just wanted to add that `delta.y` may also be incorrect if the draggable is inside a scrollable container that is scrolled down some of the way. (Nothing has `position: fixed`.)

Let me know if you would like me to create a separate issue for this or provide a minimal repro.
