### ISSUE TITLE
[FEATURE]: Drag a copy

### ISSUE THREAD

**Issue by L-U-C-K-Y** [clauderic/dnd-kit#308]
Hi all

Thanks for this great project!

I was wondering if there is the possibility to drag a copy.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/14868134/120163267-a25db600-c1f9-11eb-9654-7e200b803e38.png">

In our use-case, we would like to group identical tasks into 1 element and indicate the copies with a badge.
If all 4 copies are dragged, then the element itself can be dragged.
I was thinking if we could set a `dragCopy` prop that enables copies as long as it's `true`.

**Comment by clauderic** [comment]
This is possible via the [DragOverlay component](https://docs.dndkit.com/api-documentation/draggable/drag-overlay)
