### ISSUE TITLE
how to test if a rect is being dragged over upper half or bottom half of target?

### ISSUE THREAD

**Issue by lanyusan** [clauderic/dnd-kit#315]
I am sorry if this has been asked before. I couldn't find out the answer by searching issues.

Is there a way to test if a rect is being dragged over upper half or bottom half of target?

I need to explicitly test this for some usecase.

Thanks.

**Comment by medihack** [comment]
Isn't it just possible to split the droppable in two? One for the upper target and one for the lower target. You can even wrap it in another droppable.

**Comment by lanyusan** [comment]
That is a way to do it. Thanks.

**Comment by medihack** [comment]
You're welcome. And maybe time to close the issue.
