### ISSUE TITLE
Sorting event listener is not called when we use dnd/Sortable with antd table instead drag start and drag end is called when we try to sort the column

### ISSUE THREAD

**Issue by rajat-sf** [clauderic/dnd-kit#322]
Sorting event listener is not called when we use dnd/Sortable with antd table instead drag start and drag end is called when we try to sort the column

@clauderic thank you in advance

**Comment by clauderic** [comment]
This isn't an issue with @dnd-kit. Please re-open an issue in the [ant-design repository](https://github.com/ant-design/ant-design/) or the [react-component/table repository](https://github.com/react-component/table) (which is what ant design uses under the hood to power its table component)
