### ISSUE TITLE
Error with snowpack and dnd-kit

### ISSUE THREAD

**Issue by Zmeu213** [clauderic/dnd-kit#327]
Hi. I got this error with just a rendering `<DndContext />` anywhere in the app created with snowpack
```
Unhandled Runtime Error

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

**Comment by clauderic** [comment]
This is most likely an issue with the latter:

> 3. You might have more than one copy of React in the same app

Double check your `package-lock.json` or `yarn.lock` file and make sure you don't have more than a single copy of `react` or `@dnd-kit/core` installed.

**Comment by Zmeu213** [comment]
@clauderic im pretty sure i only have one `react` package, why would i have more. If only `react` and `react-dom` is that 2 packages you talking about. Here is lines from my package.json
```json
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
```
except it nope, i dont have extra reacts, whatever they are

**Comment by clauderic** [comment]
You have to check in the package lock files, not in package.json to make sure you don't have multiple resolved versions installed.

Double check your package-lock.json or yarn.lock file and make sure you don't have more than a single copy of react or @dnd-kit/core

**Comment by Zmeu213** [comment]
Nope, got several `"react": ">=16.3.0"` and similar lines in package-lock as peerDependancies of some packages and only one `react`.
Also i checked react in different modules in project as `window.reactN` and compared them, no extra react detected.
So I pretty much think the problem is in snowpack and way it works with modules
