### ISSUE TITLE
Drag only when long pressing

### ISSUE THREAD

**Issue by baptisteArno** [clauderic/dnd-kit#329]
Hey!

It would be great to only enable the drag on long-pressing an element. I tried using [use-long-press](https://github.com/minwork/use-long-press)

```tsx
const bind = useLongPress(
    () => {
      setCanDrag(true);
    },
    {
      onCancel: () => setCanDrag(false),
      onFinish: () => setCanDrag(false),
    }
  );

const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({ id: message.id, disabled: !canDrag });
  const [isDraggingDebounced] = useDebounce(isDragging, 100);
```

It calls setCanDrag but it doesn't drag. Any idea how I can achieve this?

**Comment by clauderic** [comment]
This isn't quite the right mental model for how you would implement something like this with @dnd-kit. 

Make sure you [read about how Sensors work with @dnd-kit](https://docs.dndkit.com/api-documentation/sensors).

Specifically, the built-in sensors support [activation constraints](https://docs.dndkit.com/api-documentation/sensors/pointer#activation-constraints) such as delay or distance. In this case, it sounds like you're looking for the `delay` constraint:

```tsx
import {DndContext, PointerSensor, useSensor, useSensors} from '@dnd-kit/core';

function App() {
  const sensors = useSensors(
    useSensor(PointerSensor, {
      activationConstraint: {
        delay: 250,
        tolerance: 5,
      },
    }),
  );
  
  return (
    <DndContext sensors={sensors}>
      {/* ... */}
    </DndContext>
  );
}
```
