### ISSUE TITLE
Display bug when sorting items with different widths?

### ISSUE THREAD

**Issue by baptisteArno** [clauderic/dnd-kit#330]
https://user-images.githubusercontent.com/16015833/121776780-10f22a80-cb8f-11eb-8348-e82525e17513.mp4

What am I doing wrong here?

https://codesandbox.io/s/sortabletabs-with-dragoverlay-forked-4l9k2?file=/src/SortableTabs.tsx:1835-1847

**Comment by clauderic** [comment]
```diff
import {CSS} from '@dnd-kit/utilities';

- CSS.Transform.toString(transform)
+ CSS.Translate.toString(transform)
```

**Comment by baptisteArno** [comment]
Thank you for your fast answer! 😃

I made the change, but it's still not ideal?

https://user-images.githubusercontent.com/16015833/121778557-b3161080-cb97-11eb-8d15-0218737dcdc0.mp4

Also, on the `Sortable` doc example, it uses `CSS.Transform`

**Comment by clauderic** [comment]
Refer to https://github.com/clauderic/dnd-kit/issues/44#issuecomment-757312037

**Comment by baptisteArno** [comment]
That makes total sense. Thank you, keep up the good work!
