### ISSUE TITLE
The response is lost after moving in Touch mode

### ISSUE THREAD

**Issue by dataangel** [clauderic/dnd-kit#332]
![image](https://user-images.githubusercontent.com/587849/121818883-8f001f80-ccbc-11eb-8fb0-71253db7c8a6.png)

**Comment by clauderic** [comment]
This is only a bug in the storybook environment with the iframe. Try visiting the story directly, the bug cannot be reproduced:

https://5fc05e08a4a65d0021ae0bf2-bjcalsbrgz.chromatic.com/iframe.html?id=presets-sortable-multiple-containers--basic-setup&args=&viewMode=story
