### ISSUE TITLE
DataTransfer

### ISSUE THREAD

**Issue by Eneris** [clauderic/dnd-kit#338]
Hi. My use-case requires some dragging of data out of the site context / browser windows.
In other words, I need to use https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer

Is there a way to access Drag event to be able to set DataTransfer data?

Best,
Martin

**Comment by clauderic** [comment]
There isn't. This is by design. Refer to https://github.com/clauderic/dnd-kit/discussions/306

**Comment by Eneris** [comment]
Thanks for the quick response

**Comment by myckhel** [comment]
I made this hack in place of DataTransfer
```tsx
const onDragStart = (e: DragStartEvent) => {
  if (e.active.data) {
    // @ts-ignore
    e.active.data.mode = 'form'
    // @ts-ignore
    e.active.data.type = 1
  }
}

function handleDragEnd(event) {
  console.log(event) // {active: {data: {current, type: 1, mode: 'form'}}}
}
  
<DndContext onDragEnd={handleDragEnd} onDragStart={onDragStart} />
```
