### ISSUE TITLE
DND disabled when Dragging in same element twice or more at a time.

### ISSUE THREAD

**Issue by tarequl143** [clauderic/dnd-kit#352]
I have used dndkit in my project, I am facing a big issue that when I am moving a draggable element from one droppable container to another droppable container its working fine but when I am trying to move that same element again into another container whole dnd is disabled and its not working. This is a major issue I can't find out this problem. If there is any solution can anyone help me out. Also sometime draggable element is moved in new container and also have in same container too. I mean its getting duplicate and then when i am moving one of them another one is moving. its really bad.

https://www.loom.com/share/531beb5706e340ca85fb20ee5c2d1e2e?sharedAppSource=personal_library

**Comment by whytspace** [comment]
@tarequl143 I am facing a very similar issue using the `useSortable` hook to order items in a list.

I am passing the items of the list into my component as prop an `items` prop. And I noticed that this bug would occur whenever this `items` prop changes (eg after reload from server). Similar to your video, the items would still show the `:hover` state on mouseover but dragging them has no effect at all.

Help very much appreciated :)

**Comment by clauderic** [comment]
@tarequl143 / @whytspace can you share a reproduction case of the issue on CodeSandbox?

**Comment by paynecodes** [comment]
I had a similar issue. My problem was not paying careful attention to the following line in the [`<DragOverlay />` docs](https://docs.dndkit.com/api-documentation/draggable/drag-overlay#usage)

> make sure that the components rendered within the drag overlay do not use the useDraggable hook.

**Comment by tarequl143** [comment]
@whytspace The issue was in our code. Disabled issue only happen when 2 Draggable elements has same reference or same ID. I have solved the issue and now there is no disabled issue. You can check if you have any render issue or state change issue. In my case when I was dragging and dropping an element another container I was updating my local file state and after getting success result from API. I was updating my global state based on Dragged and Dropped container ID. My purpose was to make less API request. But it was making same element in another container with same reference.

**Comment by tarequl143** [comment]
@clauderic I have solved the issue so you can closed the issue. But there is few more problem in dndkit I faced but that is not in React dnd. Like When I am dragging an element into another container its just blinking within 2 containers. Its getting same result for 2 container collision detection. Also Overflow container has a big issue. Like a container has so many items and few items is overflow and When i am dragging an element from one container to another container the overflow conatiner's overflow items are catching dragggin element. It should not be happend like that.

**Comment by tarequl143** [comment]
Here is a video for both problem. Blinking between 2 container and overflow items catching Dragging element. If you notice when I was dragging Paypal and Skrill it should be detected in test container as test container was near of Dragging element but it was detecting overflow items container and overflowed items also.

https://www.loom.com/share/44e422764121426b8026cb433d4adc08

**Comment by tarequl143** [comment]
@whytspace if you couldn't solve the disabled issue yet. You can contact me I will be happy to help you.

**Comment by clauderic** [comment]
Going to close this issue, feel free to re-open more specific issues @tarequl143

**Comment by vidhimultiqos** [comment]
@tarequl143 Can you please share or give a reference about the code? I am facing the same issue. I have more than one tab whose ids are the same.
