### ISSUE TITLE
Snap to grid can cause mouse leaving its original relative position to dragging element

### ISSUE THREAD

**Issue by otakustay** [clauderic/dnd-kit#356]
This can be reproducted in [useDraggable - snap to grid](https://5fc05e08a4a65d0021ae0bf2-cbfrwoklyt.chromatic.com/?path=/story/core-draggable-hooks-usedraggable--snap-to-grid) example:

https://user-images.githubusercontent.com/639549/124537129-e2910380-de4b-11eb-84a6-a3fedadeb1a1.mp4

Dragging to left and top are quite comfortable, however dragging to right and bottom can cause mouse leave the original relative position (on my video its the "d" character)

If some options can be provided to `createSnapModifier` to ensure element only moves when mouse hit the grid edge, this dragging experiment can be much better

**Comment by clauderic** [comment]
This isn't really a bug, I'd say this is expected behavior. The `createSnapModifier` function is a fairly simplistic implementation, you're welcome to fork it and make adjustments to it as you see fit.
