### ISSUE TITLE
Selecting a near edge item in a list causes immediate scrolling

### ISSUE THREAD

**Issue by casimcdaniels** [clauderic/dnd-kit#362]
Not sure if this is a configurable thing, but this is a common behavior I see with DND  libraries (ahem, react-beautiful-dnd) which is quite annoying! When selecting an item in a list near the edge of the scroll container, the list will start scrolling immediately. The solution could be something like including a threshold from the original position before beginning scroll, relative to scroll speed, or allow configuring of autoscroll to only happen when dragged past the edge (which I prefer since this feels more natural personally but YMMV).

Example from storybook:

https://user-images.githubusercontent.com/4147943/125172856-0628b680-e18a-11eb-8442-76d42b32a44f.mov

**Comment by clauderic** [comment]
Feel free to open a PR to let consumers have more control on the autoscroll behavior

**Comment by andelkocvjetkovic** [comment]
Try using threshold of DndKit Context, it worked for me.

```
autoScroll={{
	threshold: {
	  x: 0,
	  y: 0.02,
	},
}}

```
