### ISSUE TITLE
snapCenterToCursor is not exported in dist version of @dnd-kit/modifiers

### ISSUE THREAD

**Issue by virajsoni06** [clauderic/dnd-kit#365]
![image](https://user-images.githubusercontent.com/13236286/125780291-f1e13abc-0aea-4297-8110-e837f6699a1c.png)

**Comment by clauderic** [comment]
That's because it hasn't been released yet https://github.com/clauderic/dnd-kit/pull/342

If you want to try it right away, install `@dnd-kit` packages tagged with `@next` on npm

**Comment by virajsoni06** [comment]
@clauderic Saw the latest release has snapCenterToCursor. Nice one!
I've updated dnd-kit packages in my project. However they don't seem to work. Looked into the package and don't see any code from the master branch in it. This is what I see
![image](https://user-images.githubusercontent.com/13236286/135607682-f6dfa387-110c-456a-8dbe-d7e139e7c8c4.png)
