### ISSUE TITLE
Hooks causing re-rendering of items

### ISSUE THREAD

**Issue by enjoykcc456** [clauderic/dnd-kit#368]
Hi, im currently working on an infinite scroll of items (prolly more than thousands), where each item is attached to useDraggable and useDroppable hooks to allow them to be draggable/droppable among each other. However, i am having problem of the hooks triggering the re-render of the thousands of items whenever im trying to drag a single item into another one. I tried setting the disabled to false for some of the items, but it will still cause them to re-render. Hence, would like to know does anyone face this kind of use case before and is there any way to handle this.

Thank you.

**Comment by clauderic** [comment]
Have you considered using a virtualized infinite list? It's generally not a good idea to try to add drag and drop functionality to a list of thousands of items, it will result in severe performance concerns.

**Comment by enjoykcc456** [comment]
Hi, thanks for the reply. I am now using react-virtualized so that not all items are re-rendered on drag. But, i realised that for example when i am at item 570 - 600, even though the 'draggableNodes' in the context are only these 30 nodes, but the preview of the custom drag overlay is much more laggier than if i am at item 1 - 30. Do u know what could be the reason? Thanks

**Comment by clauderic** [comment]
I'm not sure, it shouldn't make a difference in theory. Can you share a codesandbox replicating the issue?
