### ISSUE TITLE
Resizing a content of a div in sorting between diffrent width containers

### ISSUE THREAD

**Issue by logikalcamp** [clauderic/dnd-kit#38]
maybe you have an idea how can I solve it

https://www.loom.com/share/101663e9b04449b9a220ee5891ce26d3

**Comment by clauderic** [comment]
Ah yes, this needs to be documented better.

You need to use `CSS.Translate.toString` instead of `CSS.Transform.toString` if you don't want the scale to change when sorting between variable sized items

**Comment by badloop** [comment]
I know this is quite old, but the above code is now unavailable and I am running into the same issue.  @clauderic would you be able to provide more context as to where this needs to be implemented to avoid the stretching/resizing when dragging?
