### ISSUE TITLE
Mystery "Draggable" text element in DOM

### ISSUE THREAD

**Issue by n8sabes** [clauderic/dnd-kit#382]
On iOS, I am seeing an invisible text field become selected in the top-left of the page on a long-press. I have searched my code but nothing is standing out.

**QUESTION:** Does `dnd-kit` inject a "Draggable" text element into the DOM when dragging starts? If so, is there a way to obscure or prevent this element from being auto-selected?

![Mystery Text](https://user-images.githubusercontent.com/10445528/126880812-0a074278-bc73-4d4a-9c8c-c565bfeea63c.jpg)

**Comment by clauderic** [comment]
Could be the `LiveRegion` component which renders accessibility announcements 🤔  https://github.com/clauderic/dnd-kit/blob/master/packages/accessibility/src/components/LiveRegion/LiveRegion.tsx

**Comment by n8sabes** [comment]
Hi @clauderic,

I tried adding `userSelect: 'none'`, including `!important` everywhere I could think of (from handlers to DOM elements), but still get the 'Draggable' text injected and selection of the text.

Thank you for including a fix for this.

**Comment by clauderic** [comment]
You may need to try `WebkitUserSelect: 'none'`

**Comment by n8sabes** [comment]
Good thought. I just tried explicit inclusion of the webkit vendor prefix, but unfortunately get the same result.

**Comment by MKraust** [comment]
I have same problem using 
```
"@dnd-kit/core": "^6.1.0",
"@dnd-kit/sortable": "^8.0.0",
"@dnd-kit/utilities": "^3.2.2",
```
