### ISSUE TITLE
Droppable targets less than ~20% height of Draggable element is skipped

### ISSUE THREAD

**Issue by n8sabes** [clauderic/dnd-kit#383]
In my implementation, if a Droppable target is less than ~20% of the height of the Draggable element, the droppable target is not seen and then ALL SUBSEQUENT droppable items are offset by that skipped element’s height.

I’m still investigating the cause of this anomaly, either in my code or `dnd-kit`. If anybody else has seen this behavior please let me know. Are there any 0.22 or 1.22 ratios in the library that might cause this? Any thoughts on the matter welcome and I will share what I learn as I simplify my project to isolate the cause.

**Comment by n8sabes** [comment]
I've created a sandbox that reproduces this issue along with a screen recording.

[CodeSandbox of Issue #383](https://codesandbox.io/s/claudericdnd-kit-issue-383-1vm16)

![clauderic dnd-kit Issue 383](https://user-images.githubusercontent.com/10445528/127259942-adcd45f9-d6dc-423d-a680-ee83818a1f27.GIF)

**Comment by n8sabes** [comment]
Any thoughts on this? Cause and/or a workaround?

**Comment by clauderic** [comment]
I would recommend creating your own collision detection algorithm that is optimized for this type of use-case to fix this.

For example, you could compare only the top or bottom offsets of the droppable areas to make sure no droppable elements in the list are skipped.

**Comment by n8sabes** [comment]
Thanks @clauderic, I'll give that a try.
