### ISSUE TITLE
State is frozen after dragging between multiple containers

### ISSUE THREAD

**Issue by zrothauser** [clauderic/dnd-kit#386]
I'm working on a use-case where results can be dragged from a sidebar (and then removed from the sidebar) into a list of selected items. 

After dragging one item from the sidebar list into the "selected" list, the state sometimes gets stuck. If it doesn't get stuck, the transitions on the next drag event don't completely work - the newest item in the list will stay in place, and other items kind of move around it. 

I've been able to replicate a simplified version of my app in CodeSandbox:
https://codesandbox.io/s/hopeful-brook-6j00k?file=/src/App.tsx

(Note: the "empty" useDroppable container isn't fully implemented here, but that shouldn't affect the issue in question, because I'm starting with a list that has a few items in it)

The monitor state in the `DndContext` component looks to be stuck on "dragEnd" - I'm not sure if this is just related to the issue, or if the issue is caused by that event somehow not ending.

**Comment by mateuszkosmider** [comment]
I'm not an expert but from my perspective, the main issue in your example is two separate variables with sortable items:
```
const [searchResults, setSearchResults] = useState<ItemData[]>([
    { id: 1, value: "First" },
    { id: 2, value: "Second" },
    { id: 3, value: "Third" },
    { id: 4, value: "Fourth" }
  ]);

const [items, setItems] = useState<ItemData[]>([
    { id: 5, value: "Fifth" },
    { id: 6, value: "Sixth" }
]);
```
I think you should consider modifying it to something like:
```
const [items, setItems] = useState<{searchResults: ItemData[], items: ItemData[]}>({
    searchResults: [
      { id: 1, value: "First" },
      { id: 2, value: "Second" },
      { id: 3, value: "Third" },
      { id: 4, value: "Fourth" }
  ],
  items: [
      { id: 5, value: "Fifth" },
      { id: 6, value: "Sixth" }
  ]
});
```

Take a look at example here https://github.com/clauderic/dnd-kit/blob/master/stories/2%20-%20Presets/Sortable/MultipleContainers.tsx

You can find that `items` is an object with multiple keys:
![Screenshot 2021-07-27 at 23 43 51](https://user-images.githubusercontent.com/974368/127231565-2971550c-6dc2-4a00-872d-231d19eb65f0.png)

and all operations are made using just one `setItem` method.

**Comment by zrothauser** [comment]
Thanks for the suggestion @mateuszkosmider, I tried making that change (to this fork below), but I'm still experiencing the same issue:
https://codesandbox.io/s/affectionate-mountain-gdhbq?file=/src/App.tsx

**Comment by HawKyre** [comment]
I've been having this same problem, and it also breaks after selecting any kind of text in the page.

**Comment by sanex3339** [comment]
Same thing for me.

**Comment by sanex3339** [comment]
@zrothauser in your case you shouldn't use `useSortable` inside of the `DragOverlay => SearchResultItem` component. Make a standalone version of  `SearchResultItem` special for `SearchResultItem`

Im my case i don't have any `useSortable` inside my `DragOverlay` components

**Comment by zrothauser** [comment]
Thanks @sanex3339! That was the issue here.
