### ISSUE TITLE
Possible solution to the disappearance of the Tree example in the storybook

### ISSUE THREAD

**Issue by hsmr29** [clauderic/dnd-kit#387]
Hi, checking inside the [storybook examples](https://5fc05e08a4a65d0021ae0bf2-lsezdewkhf.chromatic.com/) to see the Tree example, I realized that it was gone. Checking a bit in /stories/3 - Examples/Tree/SortableTree.tsx I saw that the strategy passed inside the **[measuring object](https://github.com/clauderic/dnd-kit/blob/master/stories/3%20-%20Examples/Tree/SortableTree.tsx#L70)** was still **LayoutMeasuringStrategy.Always** and changing it to **MeasuringStrategy.Always** somehow makes the storybook compile correctly the Tree example and yes show it within the list of examples. Of course, you have to import **MeasuringStrategy** from **@dnd-kit/core** and you could remove **LayoutMeasuringStrategy** and **Measuring** that are no longer used.

I hope it will be helpful, and the adjustment can be made soon to have that component available again within the storybook examples. I take this opportunity to give thanks for the excellent work done in this library.

**Comment by clauderic** [comment]
Fixed by https://github.com/clauderic/dnd-kit/commit/ad4a26f1ba9b01ea8f6050bcfc21c12125063dc3
