### ISSUE TITLE
activeNodeRect has wrong type

### ISSUE THREAD

**Issue by trungdo-epi** [clauderic/dnd-kit#392]
In the `Modifier` type definition, `activeNodeRect` has type `ViewRect`

https://github.com/clauderic/dnd-kit/blob/master/packages/core/src/modifiers/types.ts#L8
https://github.com/clauderic/dnd-kit/blob/master/packages/modifiers/src/utilities/restrictToBoundingRect.ts#L6

But it has type `ClientRect` in `DndContext`
https://github.com/clauderic/dnd-kit/blob/master/packages/core/src/components/DndContext/DndContext.tsx#L246

**Comment by clauderic** [comment]
Fixed by #518
