### ISSUE TITLE
Support for cross-window drag and drop?

### ISSUE THREAD

**Issue by FezVrasta** [clauderic/dnd-kit#394]
Hi, I can't find in your docs if this library supports drag and drop between different windows (of the same app), may you shed some light please?

**Comment by clauderic** [comment]
This isn't supported and there are no plans to support it a the moment. That type of use-case is only achievable via the HTML5 Drag and Drop API. Refer to https://github.com/clauderic/dnd-kit/discussions/306#discussioncomment-848803
