### ISSUE TITLE
DragOverlay drop animation problem (when using scale)

### ISSUE THREAD

**Issue by julianpetriv** [clauderic/dnd-kit#398]
Hi! I noticed a problem with drop animation when using `transform: scale()` on DragOverlay child element. So when you drag scaled DragOverlay item it drops aligning by left and top edges.

https://user-images.githubusercontent.com/36206907/128185946-31e20b49-bc84-4ae7-8711-55b9b6b4b1a5.mp4

Here is [codesandbox](https://codesandbox.io/s/dnd-kit-drop-animation-problem-q8tbl) that demonstrates an issue.
However, your [example](https://5fc05e08a4a65d0021ae0bf2-mdsmdaavqx.chromatic.com/?path=/story/presets-sortable-grid--basic-setup) where you also perform scale works OK, probably because you are using another wrapper element between DragOverlay and Item.

Would be grateful if you investigate this issue.
Thanks in advance

**Comment by clauderic** [comment]
You'll be able to customize the keyframes of the drop animation in the next major version, refer to the release notes here #657

**Comment by Anishali2** [comment]
i have the same issue and i realize that the issue is moving the DragOverLay outside of the condition

instead of doing this 
```
      {activeId ? (
                <DragOverlay adjustScale={adjustScale} dropAnimation={dropAnimation}>
                    <SortableItem id={activeId} activeId={selectedId} />
                </DragOverlay>
          ) : null} 
```



i have to do this
      
 ```
 <DragOverlay adjustScale={adjustScale} dropAnimation={dropAnimation}>
      {activeId ? (
          <SortableItem id={activeId} activeId={selectedId} />
       ) : null}
 </DragOverlay>
          
```
