### ISSUE TITLE
Support for tolerance in DistanceConstraint

### ISSUE THREAD

**Issue by supersebh** [clauderic/dnd-kit#400]
Hi there!

Thank you for all your great work with this amazing library!

We needed to support horizontal drag-n-drop from a vertically scrollable container using touch. We added support for optionally specifying `tolerance` in `DistanceConstraint` so that the drag operation will not be started if the user drags more than `tolerance`. For our use case we specify
```typescript
{
  distance: { x: 8 },
  tolerance: { y: 16 },
}
```
as `activationConstraint` so that the drag operation isn't started if you drag more than 16px vertically, because we want to continue the scrolling in that case.

Please consider merging our PR https://github.com/clauderic/dnd-kit/pull/399. :)

**Comment by clauderic** [comment]
Fixed by https://github.com/clauderic/dnd-kit/pull/399
