### ISSUE TITLE
Positioning issue when scrolling an item in a list that is taller than the viewport of the window

### ISSUE THREAD

**Issue by chrisamador** [clauderic/dnd-kit#404]
First, thanks for all the work you have put into dnd-kit. I think it is a great library so far. 

I'm using the `@dnd-kit/sortable` preset and I'm running into an issue when I scroll an item in a list that is taller than the viewport of the window (See video below).

I read in the [documentation](https://docs.dndkit.com/presets/sortable#drag-overlay) that it is recommend to use the DragOverlay but I would like to not use it. Since it is just a recommendation shouldn't this still work as intended? Meaning the position of the item being sorted follows the cursor? 

https://user-images.githubusercontent.com/5768458/128590226-7b8dc219-f4a9-4a07-8d23-3912c1758790.mov

I've recreated the issue in this [codesandbox](https://codesandbox.io/s/festive-cherry-2edmb?file=/src/App.tsx) if it helps. Am I missing something? Thanks in advance.

**Comment by infernalmaster** [comment]
Looks like `useDraggable` has error in `transform` calculation when it's inside scrollable container
https://codesandbox.io/s/naughty-sanne-j065b?file=/src/App.tsx

**Comment by infernalmaster** [comment]
The funny think is that examples with drag overlay render 50 items but the one without it renders only 5 items. So it this hides problem in normal screens
https://github.com/clauderic/dnd-kit/blob/ad4a26f1ba9b01ea8f6050bcfc21c12125063dc3/stories/2%20-%20Presets/Sortable/1-Vertical.story.tsx#L29

**Comment by infernalmaster** [comment]
And as I understand this is expected behaviour (known bug)
https://docs.dndkit.com/api-documentation/draggable/drag-overlay#when-should-i-use-a-drag-overlay
> If your draggable item is within a scrollable container, we also recommend you use a <DragOverlay>, otherwise you'll need to set the draggable element to position: fixed yourself so the item isn't restricted to the overflow and stacking context of its scroll container, and can move without being affected by the scroll position of its container.

**Comment by ShamansCoding** [comment]
Hello! First of all, I want to thank clauderic for such an amazing library!

I've hit the same kind of issue with DragOverlay, but in my case positioning is broken, when overflowY of the window is more than 0. The closest scrollable parent of the draggable element in sortable is working properly and DragOverlay seems to be displayed correctly relative to the parent element scroll position. As a workaround, I came with the solution below:

```javascript
  const {
    attributes,
    listeners: { onPointerDown, onTouchStart },
    setNodeRef,
    transform,
    transition,
  } = useSortable({
    id
  });

  /** @param {React.PointerEvent<HTMLDivElement>} event */
  function onPointerDownModified(event) {
    window.scrollTo(0, 0);
    onPointerDown(event);
  }

  /** @param {React.TouchEvent<HTMLDivElement>} event */
  function onTouchStartModified(event) {
    window.scrollTo(0, 0);
    onTouchStart(event);
  }

  const draggableStyle = transform
    ? {
        transform: CSS.Transform.toString(transform),
        transition,
      }
    : undefined;

  return (
    <div
      ref={setNodeRef}
      onPointerDown={onPointerDownModified}
      onTouchStart={onTouchStartModified}
      {...attributes}
      style={{ outline: "none", ...draggableStyle }}
      aria-label="Draggable"
    >
      {children}
    </div>
  )
```

**Comment by infernalmaster** [comment]
I found another solution that doesn't require big changes
Looks like it's possible to position dragged item with `position: 'fixed'` but you need to put some dummy contained (in my example: <ItemPlug>) with same size on it's place

```
const Sortable = styled('div')`
  position: relative;

  &.isDragging {
    z-index: 2;
  }
`

const ItemPlug = styled('div')``


const useAdvancedSortable = (options) => {
  const sortable = useSortable(options)
  const dndContext = useDndContext()

  let itemStyle = {
    style: {
      transform: CSS.Translate.toString(sortable.transform),
      transition: sortable.transition,
    }
  }
  let plugStyle = null

  if (sortable.isDragging && sortable.transform) {
    itemStyle = {
      style: {
        width: dndContext.activeNodeRect.width,
        height: dndContext.activeNodeRect.height,
        top: dndContext.activeNodeRect.top + sortable.transform.y,
        left: dndContext.activeNodeRect.left + sortable.transform.x,
        position: 'fixed'
      }
    }
    plugStyle = {
      style: {
        width: dndContext.activeNodeRect.width,
        height: dndContext.activeNodeRect.height
      }
    }
  }

  return {
    sortable,
    dndContext,
    itemStyle,
    plugStyle
  }
}

export const SortableItemContainer = ({ id, children }) => {
  const {
    sortable: {
      isDragging,
      attributes,
      listeners,
      setNodeRef
    },
    itemStyle,
    plugStyle
  } = useAdvancedSortable({ id })

  return (
    <>
      {plugStyle && <ItemPlug {...plugStyle} />}
      <Sortable ref={setNodeRef} {...attributes} {...listeners} isDragging={isDragging} {...itemStyle}>
        {children}
      </Sortable>
    </>
  )
}

// now wrap every item inside <SortableItemContainer>
<DndContext ....>
  <SortableContext ....>
    {items.map(item => (
      <SortableItemContainer id={item.id} key={item.id}>
        {item.id}
      </SortableItemContainer>
    ))}
....
```

**Comment by clauderic** [comment]
This isn't a bug. If you choose not to use `<DragOverlay>`, you need to manually replicate some of the functionality that it provides for you.

As outlined in the documentation, if your draggable item is within a scrollable container, you'll need to set the draggable element to `position: fixed` yourself so the item isn't restricted to the overflow and stacking context of its scroll container, and can move without being affected by the scroll position of its container.

**Comment by ShamansCoding** [comment]
Is it possible to provide а detailed example in the documentation or in the Storybook? It seems that this case is not obvious to handle it only with current information from documentaion.

**Comment by GoranRibic** [comment]
> Is it possible to provide а detailed example in the documentation or in the Storybook? It seems that this case is not obvious to handle it only with current information from documentaion.
> 
> The documentation says that "If your draggable item is within a scrollable container, we also recommend you use a DragOverlay, otherwise you'll need to set the draggable element to position: fixed yourself."
> 
> I'm using DragOverlay but still facing issues with scrollable containers. Especially when container size is changing while dragging an element. As an example: when the tree node is opening and deeper level content is shown inside a draggable menu.

Any solution to this?
