### ISSUE TITLE
Sortable's DragOverlay preview gets size mixed up.

### ISSUE THREAD

**Issue by c4lliope** [clauderic/dnd-kit#406]
See issue demonstration here; https://i9e6e.csb.app/, and drag the `1` on top of the `9`.

![size](https://user-images.githubusercontent.com/30454698/128760349-d3f3e3db-f184-4413-9113-ca6d66d846c8.gif)

Sandbox: https://codesandbox.io/s/heuristic-khayyam-i9e6e?file=/src/Item.js

Proper behavior should be that the preview of the DragOverlay retains the size of the `1` box,
instead of making the bad assumption that all boxes are of the same dimensions.

**Comment by irek-teo** [comment]
Same issue here. In my case it's the height that gets mixed up.

**Comment by clauderic** [comment]
@c4lliope the codesandbox you linked does not seem to work, are you sure you linked the correct sandbox?

**Comment by c4lliope** [comment]
@clauderic good catch, thank you. My sandbox hadn't saved my changes.
I updated the sandbox so those links should be functioning properly now.

**Comment by ekawatani** [comment]
Any updates on this? In my case, I have a list of expandable components so the height of each item is dynamic.
![dragging](https://user-images.githubusercontent.com/61330990/133906457-7dfefef2-067c-40af-91ef-3ba339b8d277.gif)

**Comment by clauderic** [comment]
@ekawatani the issue you're facing is unrelated. You are most likely using `CSS.Transform.toString()` instead of `CSS.Translate.toString()`.

**Comment by ekawatani** [comment]
@clauderic Thanks, it works better, but do you know why the item goes behind other items if I drag it from the above to below? Dragging an item from below to above works fine. IMO, this should have just worked. I looked through the doc, but couldn't really find any info on this.

![dragging2](https://user-images.githubusercontent.com/61330990/133944129-826b38e3-b854-4007-a989-21b94357ce4f.gif)

**Comment by clauderic** [comment]
@ekawatani You have to set the `z-index` of the item currently being dragged higher. If you want something that just works with no manual setup, use `<DragOverlay>`.

**Comment by 321ckatz123** [comment]
@ekawatani by any chance, could you share the code (or at least the relevant parts) to get from your first image to your second? I have literally the same issue and @clauderic unfortunately wasn't sufficient for me to understand what to do (as translate the CSS property and translate the transform property are equivalent. It's clearly the scale causing it, but those are still coming from the useSortable hook)

**Comment by 321ckatz123** [comment]
If anyone runs into this issue as I did, in addition to not scaling the item (either via the helpers provided, or manually), change the strategy to `verticalListSortingStrategy`. I was using the default `rectSortingStrategy` and that causes a similar issue to what was shown above.
