### ISSUE TITLE
Resized dragged item loses position from cursor

### ISSUE THREAD

**Issue by KenanYusuf** [clauderic/dnd-kit#41]
I am trying to recreate the [sortable grid with a large first tile](https://5fc05e08a4a65d0021ae0bf2-czytjnikoc.chromatic.com/iframe.html?id=presets-sortable-grid--large-first-tile&viewMode=story) example from Storybook and seeing an issue with dragging to and from the first item's position. It looks like the transform position of the dragged item is incorrect in relation to the user's cursor (see video below).

## Example
See the code here:
https://codesandbox.io/s/ecstatic-pine-zs8nj?file=/src/SortableItem.jsx

https://user-images.githubusercontent.com/9557798/103904933-dc68d700-50f5-11eb-92d7-d97aa8c7ba91.mp4

Thanks for making such an intuitive drag and drop library, really excited to see this project progress!

**Comment by clauderic** [comment]
Hey @KenanYusuf, currently variable sized grid only works well when using a [`<DragOverlay/>`](https://docs.dndkit.com/api-documentation/draggable/drag-overlay)

**Comment by KenanYusuf** [comment]
@clauderic thank you, I've managed to get the desired effect with DragOverlay!

For anyone interested in a working version of this: https://codesandbox.io/s/vigorous-sanderson-hdysk

**Comment by clauderic** [comment]
This looks great, thanks for sharing back with the community @KenanYusuf ❤️ 

**Made a few minor tweaks:**
- Using presentational components to get a better separation of concerns between sortable and non-sortable componeents https://docs.dndkit.com/api-documentation/draggable/drag-overlay#presentational-components
- Added handling of `onDragCancel` event
- Added `Grid` component

https://codesandbox.io/s/dndkit-sortable-image-grid-py6ve
