### ISSUE TITLE
Transition element order after external state update

### ISSUE THREAD

**Issue by devinhalladay** [clauderic/dnd-kit#410]
Hi! I'm using dnd-kit to power a prototype that allows users to rank many items based on their interdependencies. Users can drag the list on the right to re-order them, or draw lines between items on the circle to rank them by output count:
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/1934813/128945433-f07b14ca-206d-4cc6-a35c-7a58443a6004.png">

The problem is that I'd like to use the Sortable component in a controlled way, transitioning components in the list when they are re-ordered by another component (for example, by drawing a new line on the circle). That way, when a user draws a line, the sortable list reorders with the expected transition. Does dnd-kit (or the sortable extension) export a helper I could use to accomplish this?

**Comment by clauderic** [comment]
Assuming you are using a version of @dnd-kit tagged with `@next` on npm, you should be able to achieve this by passing the following configuration to `useSortable`:

```ts
function animateLayoutChanges({isSorting, wasSorting}) {
  if (isSorting || wasSorting) {
    return false;
  }

  return true;
}
```

```ts
useSortable({
  id,
  animateLayoutChanges,
});
```

You will also need to update the `measuring` prop of `<DndContext>`. If you're using an older version of @dnd-kit, this  prop used to be called `layoutMeasuring`.

```tsx
import {MeasuringStrategy} from '@dnd-kit/core';

const measuringConfig = {
  droppable: {
    strategy: MeasuringStrategy.Always,
  },
};

<DndContext measuring={measuringConfig} />
```
