### ISSUE TITLE
Mouse point collision detection algorithm

### ISSUE THREAD

**Issue by kirillgalushko** [clauderic/dnd-kit#412]
Thank you for such a great library!

**Issue:**
I'm currently working on drag and drop behavior like on the Finder app in macOS.
One of the points is to make the droppable areas active when the mouse is over the droppable element, not when draggable and droppable elements collide. So it should work like a simple hover effect.

I've tried to make my own collision detection algorithm, but there is no `mousemove` event in it, and it's impossible to get mouse position without it (as I know).

https://user-images.githubusercontent.com/41288070/129035419-be64db12-7458-4884-a9fe-c727d350f324.mov

Is there a way to achieve that?

**Comment by lukesmurray** [comment]
@clauderic this actually feels like a common enough collision algorithm that it could be worth including. I'm using dndkit to build a tiling layout similar to vscode and have had to replicate this functionality as well.


https://user-images.githubusercontent.com/34020210/130330829-b5d49339-9904-455b-8ad4-a633e8df587e.mp4
