### ISSUE TITLE
When I drag items to other containers it stops

### ISSUE THREAD

**Issue by Jean45612** [clauderic/dnd-kit#416]
Hi, my problem is When I drag items to another containers it stops and the item returns to its position.

This is my repository: https://github.com/Jean45612/equipo_futbol
The branch es dndKit

https://user-images.githubusercontent.com/58889580/129294301-028df0cb-89bd-4687-a79b-6ee2843bb974.mp4

**Comment by jfulse** [comment]
Did you figure this out?  have the same issue with @dnd-kit/sortable
