### ISSUE TITLE
[Bug/Sortable] Active element is not visible when sorting strategy is not verticalListSortingStrategy

### ISSUE THREAD

**Issue by Thebarda** [clauderic/dnd-kit#42]
Hello !

When the sorting strategy is not verticalListSortingStrategy, the active element is not visible and the others elements does not move while the active element hovers them.
But when releasing the mouse, elements are correctly sorted !

Here is a video that show the error : https://www.loom.com/share/897f0d5e80e04514a2ef4ca7ef049914
Here is a repro code : https://codesandbox.io/s/suspicious-neumann-7s5rm?file=/src/App.js:240-267

Did I miss something ?

**Comment by clauderic** [comment]
This isn't a bug with the library. You're using `span` elements as wrappers, which are not transformable elements. Refer to https://drafts.csswg.org/css-transforms-1/#transformable-element

See also https://stackoverflow.com/questions/14883250/css-transform-doesnt-work-on-inline-elements

Make sure you use an element that is transformable, such as `div`, `button`, `li`, etc.

Updated sandbox:
https://codesandbox.io/s/adoring-fire-fs3m0?file=/src/SortableItem.js

**Comment by Thebarda** [comment]
Thank you @clauderic for the tip 👍
