### ISSUE TITLE
onDragOver is called right after onDragStart so user will never hear onDragStart announcements

### ISSUE THREAD

**Issue by infernalmaster** [clauderic/dnd-kit#424]
If you open example [Sortable / vertical / Basic setup](https://5fc05e08a4a65d0021ae0bf2-mdsmdaavqx.chromatic.com/?path=/story/presets-sortable-vertical--basic-setup), focus first item and press `space` then you will see announcements "Sortable item 1 was moved into position 1 of 50".  

So looks like user will never see this one https://github.com/clauderic/dnd-kit/blob/ad4a26f1ba9b01ea8f6050bcfc21c12125063dc3/packages/core/src/components/Accessibility/defaults.ts#L13

<img width="1299" alt="Screenshot 2021-08-17 at 22 05 40" src="https://user-images.githubusercontent.com/1155618/129787875-fc747b26-1ef3-49d0-8b49-0c4ea568a5d5.png">

So right now I'm doing this
```
    onDragOver(id, overId) {
      if (id === overId) {
        return this.onDragStart(id)
      }
      ....
    }
```

As I understand `onDragOver` is always called independently from user interaction
https://github.com/clauderic/dnd-kit/blob/master/packages/core/src/components/DndContext/DndContext.tsx#L507-L530

**Comment by infernalmaster** [comment]
I found another solution
```
export const defaultAnnouncements: Announcements = {
  onDragStart(id) {
    return `Picked up draggable item ${id}.`;
  },
  onDragMove(id, overId) { // add this with code from onDragOver 
    if (overId) {
      return `Draggable item ${id} was moved over droppable area ${overId}.`;
    }

    return `Draggable item ${id} is no longer over a droppable area.`;
  },
  onDragOver() { // just return null there
    return null
  },
  onDragEnd(id, overId) {
    if (overId) {
      return `Draggable item ${id} was dropped over droppable area ${overId}`;
    }

    return `Draggable item ${id} was dropped.`;
  },
  onDragCancel(id) {
    return `Dragging was cancelled. Draggable item ${id} was dropped.`;
  },
};
```

**Comment by clauderic** [comment]
This isn't something that @dnd-kit can easily fix for consumers, because it's largely dependent on the use-case.

In the sortable examples, the `onDragOver` event happens immediately after the `onDragStart` event, because the picked up item is directly over its original position when lifted, so the first `onDragOver` event happens without user input and is redundant.

I fixed this for the sortable stories by skipping the first `onDragOver` event since it is redundant https://github.com/clauderic/dnd-kit/commit/8844cc719aaafea7f78d36d7a35698696a6853c0

**Comment by sherman89** [comment]
@infernalmaster The problem with this workaround is that if you drag the item with the mouse without going over any other item, the screen reader still reads the drag over text. @clauderic solution works correctly :)
