### ISSUE TITLE
Dragging with PointerSensor does not work well on touch devices

### ISSUE THREAD

**Issue by srmagura** [clauderic/dnd-kit#435]
Please consider the following examples which render a single draggable element. The desired behavior is for dragging to be smooth on both desktop and mobile.

See discussion #434 for additional context - `PointerSensor` is supposed to work on mobile.

## [CodeSandbox 1](https://codesandbox.io/s/dndkit-touch-with-touch-sensor-9ztdb?file=/src/App.tsx)
Uses `MouseSensor`, `KeyboardSensor`, and `TouchSensor`.
* **Dragging on desktop** - perfect
* **Dragging on mobile** - perfect in Chrome DevTools (responsive mode), a bit laggy but totally usable on Chrome on Android 11

## [CodeSandbox 2](https://codesandbox.io/s/dndkit-touch-6vrwi?file=/src/App.tsx)
Uses default sensors (`PointerSensor` and `KeyboardSensor`).
* **Dragging on desktop** - perfect
* **Dragging on mobile** - unusable in both Chrome DevTools (responsive mode) and Chrome on Android 11

**Comment by osmancalikoglu** [comment]
> You need to specify `touch-action: none;` on the draggable item, refer to https://docs.dndkit.com/api-documentation/sensors/pointer#touch-action

Thanks @clauderic and @srmagura but your fixes incorrect. If you have a container and fulled by full width draggable items, specifying `touch-action: none; ` on the draggable item turns off all touch actions and you cannot able to scroll container from anywhere. Please do not inject `touch-action: none;` to project.

I solved this issue by simply detecting device and determining one of `PointerSensor` or `TouchSensor`. If user comes from web, I use `PointerSensor` and if user comes from mobile, I use `TouchSensor`.

<img width="515" alt="image" src="https://github.com/clauderic/dnd-kit/assets/27975582/16edd12f-f12d-4ced-b258-aa0ef30ea8f9">

**Comment by patrick-y-pokeratlas** [comment]
@osmancalikoglu I have a use case that requires functionality for both touch and pointer events (laptop w/ touchscreen). I'm not sure if there's a solution for this.

**Comment by davidko5** [comment]
For those who use Tailwind - specify  touchAction: 'none' on style attribute and NOT on className attribute using the Tailwind syntax. I'am not sure why, but that was my issue that I wasn't able to locate for a long time.

**Comment by M-kabeer-47** [comment]
@osmancalikoglu Thanks buddy, your approach worked fine for me, spend a lot of time on AI tools, but they couldn't fix it haha

**Comment by tolgamorf** [comment]
@osmancalikoglu thank you for the solution. Below is `TypeScript` safe version, should anyone needs it:

```ts
const detectSensor = JSON.parse(sessionStorage.getItem("isWebEntry") ?? "true") ? PointerSensor : TouchSensor;

const pointerSensor = useSensor(detectSensor, {
    // Additional sensor options
    activationConstraint: {
        distance: 8,
    },
});
```
