### ISSUE TITLE
Droppable is not being detected when draggable is over it. 

### ISSUE THREAD

**Issue by WillenOLeal** [clauderic/dnd-kit#439]
Hi guys, 

First  things first, thank you for this library, I am new to dnds and it has made it quite easy to learn! I am working on adding a few vertically aligned containers each with horizontal lists, however, the issue I am running into is that when I drag an item from one container to another if the active draggable is not close to the other items inside the destination container, the destination container will not detect that the draggable is over it.  Here is[ the codesandbox link ](https://codesandbox.io/s/dnd-kit-multi-containers-forked-4bn6t). To reproduce, try dragging from the second container from the top down, to the one above it, draggable will still be on the old container. Thanks in advance :-)

**Comment by clauderic** [comment]
You were using extremely old versions of `@dnd-kit` in that CodeSandbox, I took the liberty of updating them to the latest version and fixing breaking changes https://codesandbox.io/s/dnd-kit-multi-containers-forked-m2jge?file=/src/app.js

Seems to work fine to me
