### ISSUE TITLE
Draggable item loses mouse position when container scrolls

### ISSUE THREAD

**Issue by julio-werner** [clauderic/dnd-kit#440]
Dragging to scroll in div loses cursor position.

Opened a codesandbox with dnd-kit and beautficul dnd comparison.
Demo: https://codesandbox.io/s/loving-boyd-pu9fe?file=/src/dnd-kit.js

The red div is the active dragging.

![image](https://user-images.githubusercontent.com/53458125/131523212-5c512249-d468-4172-b456-c12d36d4d4d2.png)

**Comment by clauderic** [comment]
Please read the documentation carefully around when to use `DragOverlay`:

> If your draggable item is within a scrollable container, we also recommend you use a <DragOverlay>, otherwise you'll need to set the draggable element to position: fixed yourself so the item isn't restricted to the overflow and stacking context of its scroll container, and can move without being affected by the scroll position of its container.

https://docs.dndkit.com/api-documentation/draggable/drag-overlay#when-should-i-use-a-drag-overlay
