### ISSUE TITLE
Maximum update depth exceeded error when container is scrollable and nouse is used

### ISSUE THREAD

**Issue by Dm1Korneev** [clauderic/dnd-kit#442]
Hello! We get an errors when sortable items container has a scrollbar.

There is example: https://codesandbox.io/s/smoosh-fast-y17ye
We have an error only with mouse.

Just take an element and move it outside of the container.

https://user-images.githubusercontent.com/7955306/131701811-a6411a84-da29-4250-8d11-53825afca776.mov

**Comment by clauderic** [comment]
I believe this is fixed in the `next` versions of `@dnd-kit` (npm releases tagged with `next`). Feel free to re-open if not 

https://codesandbox.io/s/sleepy-zhukovsky-53tve

**Comment by chestozo** [comment]
will it be available in v.3? or in v.4 only?

**Comment by clauderic** [comment]
@chestozo `@dnd-kit/core@4.0.0` and up only.
