### ISSUE TITLE
Transform styles are not applied when the id variable being passed is not specifically named "id".

### ISSUE THREAD

**Issue by Blankeos** [clauderic/dnd-kit#452]
This is an bug I found with the Sortable Preset `@dnd-kit/sortable`

When I pass an object with an id property named anything other than "id" like "_id" to a Sortable Item, it doesn't seem to apply the transform styles.

For instance:
```jsx
// if item = {_id: "A", ...}

<SortableItem key={item._id} id={item._id}/>
```

Not sure if this is a silly error on my end but I tried recreating the bug several times and it really just happens when I don't name the id variable being passed as `id`.

I made a Sandbox that demonstrates this bug. I pretty much just copied the [Getting Started Section for the Sortable Preset](https://docs.dndkit.com/presets/sortable). I only changed the data structure for `items` and the `handleDragEnd` callback.
https://codesandbox.io/s/sweet-heyrovsky-vgwt6?file=/src/App.js

**Comment by clauderic** [comment]
The problem is that you need to pass an array of unique identifiers to the `items` prop of `<SortableContext>`:

```diff
- <SortableContext items={items}
+ <SortableContext items={items.map((item) => item._id)}
```

This woks fine in your `WorkingExample` component because by default, `@dnd-kit` looks for an `id` property when passed an array of objects.

https://codesandbox.io/s/dank-cache-hyko3?file=/src/BrokenExample.jsx

**Comment by Blankeos** [comment]
Facepalming so hard haha 😅. Must've skimmed through that part in the docs. I thought the `items` prop just contained the actual array of items. Thanks for this! 🚀
