### ISSUE TITLE
Item-dragging stops working after container has been dragged

### ISSUE THREAD

**Issue by mvpindev** [clauderic/dnd-kit#455]
Hey, 

im trying to implement the drag&drop functionality with containers (groups) and items.

Unfortunately, every time i drag a group, its items can't be dragged anymore.

I created a codesandbox that showcases my problem: 
https://codesandbox.io/s/sharp-wing-tuerj

And here is a gif:
![Alt Text](https://pouch.jumpshare.com/preview/cF7R0wf4VWRSmlm36WfvBNRyPG2bI_qhkRD922Cx68vUUzePMon7zPrCF8AQg-ebWx65c5qQScA0rX3O6SqJKhA1jQB_zmxltR5bgJ1-nls)

**Comment by clauderic** [comment]
The problem is that you are using components that use `useSortable` (which uses `useDroppable` and `useDraggable` under the hood) within your `<DragOverlay>`, which is not allowed.

Check the render method of your `<Group>` component, it renders `<SortableItem>`

**Comment by mvpindev** [comment]
Thanks, for everyone that also stumbles across here, the codesandbox has been updated.
