### ISSUE TITLE
Some weird result when import useDroppable in next.js

### ISSUE THREAD

**Issue by EiffelFly** [clauderic/dnd-kit#462]
## How to reproduce

1. Setup CodeSandbox official Next.js env
2. install dndkit/core
3. import useDroppable
4. error!

![截圖 2021-09-25 下午5 12 57](https://user-images.githubusercontent.com/57251712/134766308-bdbd59f8-1bf2-42a2-a8f4-356b28bf1c3c.png)

**Comment by musakurel** [comment]
I don't has this issue. Can you reload package?
