### ISSUE TITLE
Transformed SortableContext yields an offset drag overlay

### ISSUE THREAD

**Issue by ranbena** [clauderic/dnd-kit#464]
When offsetting a SortableContext with css transform (for instance, when an open sidebar pushes it sideways), the drag overlay gets wrongly positioned.

<img width="469" alt="Screen Shot 2021-09-30 at 9 31 28" src="https://user-images.githubusercontent.com/486954/135399585-4b863509-b633-4668-87cd-1780e820ab1a.png">

Sandbox demo https://codesandbox.io/s/dnd-kit-offset-b2744

_Originally posted by @ranbena in https://github.com/clauderic/dnd-kit/issues/205#issuecomment-830186486_

**Comment by ranbena** [comment]
Here's a demonstration:

https://user-images.githubusercontent.com/486954/116719759-1da62f00-a9e4-11eb-8e9b-08d079c2e643.mov

**Comment by ranbena** [comment]
https://github.com/clauderic/dnd-kit/pull/379 allows consumers to configure how to measure the draggable node, so I gave it a shot:

```tsx
const measuringConfig = {
  draggable: {
    measure: (element) => {
      return {
        ...getBoundingClientRect(element),
        left: getViewportLayoutRect(element).left
      };
    }
  }
};
```

The result is better - there is no offset during drag 🎉
BUT the drop animation sends the overlay to an offset position.
Sandbox code: https://codesandbox.io/s/dnd-kit-offset-with-measuringconfig-6ujp6?file=/src/App.js

https://user-images.githubusercontent.com/486954/135401065-73783a0d-afcf-4202-87a2-6048994c0114.mov

**Comment by ranbena** [comment]
@clauderic in my original post I provided a reproducible sandbox demo.
I now upgraded the dependencies in the demo to `@next` but the issue doesn't seem to be fixed - actually even more offset.
Am I missing something?

-----------------------

Current: https://b2744.csb.app/
Upgraded: https://fzcdy.csb.app/

**Comment by clauderic** [comment]
Hey @ranbena,

The problem with your sandbox is that you're also rendering the `DragOverlay` component in the same transformed container, so it too is offset by `135px` when we measure it.

It's generally recommended that you try to render the `DragOverlay` in a portal higher up in the tree.

Here's a forked sandbox where that is the only change I made, everything seems to be working: https://codesandbox.io/s/dnd-kit-offset-forked-hbtwb?file=/src/App.js

**Comment by ranbena** [comment]
Understood. I'll try that 👍

**Comment by ranbena** [comment]
Works! 🎉

**Comment by riledigital** [comment]
This was really helpful! I had the same exact problem that was caused by some combination of flexbox layout containers. I'll see if I have time to PR a note about this being a good use case for React Portal in the dndkit docs.

**Comment by RahulRana0707** [comment]
@clauderic what if the same issue of @ranbena occurs inside a modal of mui. As I am implementing dnd-kit inside the modal.
If we createProtal the dragoverlay stays behind mui modal is their any solution for it?

**Comment by fmukaba** [comment]
@RahulRana0707 Did you figure something out? 
I am facing the same issue with using dnd kit in a React Modal - the overlay shows up behind the Modal
