### ISSUE TITLE
iOS 11/12 drag not working

### ISSUE THREAD

**Issue by fredbeast** [clauderic/dnd-kit#467]
Couldn't get it to drag, scrolled the page instead. I checked Storybook and some of the examples are working, most weren't.
eg. Multiple Containers & the Basic Setup Draggable options worked, Droppable Basic Setup doesn't work.

Saw this commit 1fe9b5c9d34237aae6ab22d54478c419d44a079a and may be linked. 
(In MultipleContainers.tsx PointerSensor is removed, with Touch and Mouse used instead.)
 
Setting these sensors seems to have fixed the problem for us:

```
const sensors = useSensors(
        useSensor(MouseSensor),
        useSensor(TouchSensor),
        useSensor(KeyboardSensor)
)
```

```                   
<DndContext sensors={sensors}>
...
</DndContext>
```

**Comment by clauderic** [comment]
Refer to the documentation for PointerSensor and TouchSensor:

https://docs.dndkit.com/api-documentation/sensors/pointer#touch-action

https://docs.dndkit.com/api-documentation/sensors/touch#touch-action
