### ISSUE TITLE
Are we still in beta?

### ISSUE THREAD

**Issue by cncolder** [clauderic/dnd-kit#472]
### Are we still in beta even [4.0 has been released](https://github.com/clauderic/dnd-kit/releases/tag/%40dnd-kit%2Fcore%404.0.0) 😄 

![](https://raw.githubusercontent.com/clauderic/dnd-kit/master/.github/assets/dnd-kit-hero.png)

**Comment by clauderic** [comment]
Refer to https://github.com/clauderic/dnd-kit/discussions/418#discussioncomment-1209563
