### ISSUE TITLE
How do I prevent draggable on input and btns

### ISSUE THREAD

**Issue by AsasinCree** [clauderic/dnd-kit#477]
I have some operations **btns and input** inside the draggable area. I can't select text by moving mouse in input but **triggering the drag** event.

Although I can set "**DelayConstraint**" by sensors, but it's not a perfect solution while I need to balance the drag delay and operations in input.

I want to know is there a config for disable the part of "white" content from dragging but keep dragging on "red" area

![image](https://user-images.githubusercontent.com/18276301/137868034-a94ba1c5-2ed5-448d-9a35-d3656aed2b8c.png)

**Comment by HelKyle** [comment]
For someone who may have the same issue. Just add `data-no-dnd="true"` to the parent node and all the descendant nodes will not handle the dnd events.

```ts
import type { MouseEvent, KeyboardEvent } from 'react'
import {
  MouseSensor as LibMouseSensor,
  KeyboardSensor as LibKeyboardSensor
} from '@dnd-kit/core'

export class MouseSensor extends LibMouseSensor {
  static activators = [
    {
      eventName: 'onMouseDown' as const,
      handler: ({ nativeEvent: event }: MouseEvent) => {
        return shouldHandleEvent(event.target as HTMLElement)
      }
    }
  ]
}

export class KeyboardSensor extends LibKeyboardSensor {
  static activators = [
    {
      eventName: 'onKeyDown' as const,
      handler: ({ nativeEvent: event }: KeyboardEvent<Element>) => {
        return shouldHandleEvent(event.target as HTMLElement)
      }
    }
  ]
}

function shouldHandleEvent(element: HTMLElement | null) {
  let cur = element

  while (cur) {
    if (cur.dataset && cur.dataset.noDnd) {
      return false
    }
    cur = cur.parentElement
  }

  return true
}
```

**Comment by JANEKKO** [comment]
> ```ts
> as LibMouseSensor
> ```
when i use CustomMouseSensor, i got this error, how can i use CustomMouseSensor?
`TypeError: Class constructor MouseSensor cannot be invoked without 'new'`
here's my code:
`const sensors = useSensors(
    useSensor(CustomMouseSensor, {
      activationConstraint: {
        distance: 5,
      },
    }))
   `

**Comment by DjVreditel** [comment]
> For someone who may have the same issue. Just add `data-no-dnd="true"` to the parent node and all the descendant nodes will not handle the dnd events.
> 
> ```ts
> import type { MouseEvent, KeyboardEvent } from 'react'
> import {
>   MouseSensor as LibMouseSensor,
>   KeyboardSensor as LibKeyboardSensor
> } from '@dnd-kit/core'
> 
> export class MouseSensor extends LibMouseSensor {
>   static activators = [
>     {
>       eventName: 'onMouseDown' as const,
>       handler: ({ nativeEvent: event }: MouseEvent) => {
>         return shouldHandleEvent(event.target as HTMLElement)
>       }
>     }
>   ]
> }
> 
> export class KeyboardSensor extends LibKeyboardSensor {
>   static activators = [
>     {
>       eventName: 'onKeyDown' as const,
>       handler: ({ nativeEvent: event }: KeyboardEvent<Element>) => {
>         return shouldHandleEvent(event.target as HTMLElement)
>       }
>     }
>   ]
> }
> 
> function shouldHandleEvent(element: HTMLElement | null) {
>   let cur = element
> 
>   while (cur) {
>     if (cur.dataset && cur.dataset.noDnd) {
>       return false
>     }
>     cur = cur.parentElement
>   }
> 
>   return true
> }
> ```

Thanks!

This is TypeScript version example for the MouseSensor:

```ts
export class MouseSensor extends LibMouseSensor {
    static activators = [
        {
            eventName: 'onMouseDown',
            handler: ({ nativeEvent: event }) => shouldHandleEvent(event.target as HTMLElement),
        },
    ] as typeof LibMouseSensor['activators'];
}

**Comment by JANEKKO** [comment]
【自动回复】已收到邮件。

**Comment by RafaelCENG** [comment]
Hello everyone, I tried this approach but for some reason my didnt work.
I have a very similar approach with this sandbox.
https://codesandbox.io/p/sandbox/dnd-kit-form-builder-fii0zh?file=%2Fsrc%2Fstyles.css
![image](https://github.com/clauderic/dnd-kit/assets/45431116/62db8879-f134-4c93-8f98-2a6da2107922)
I want to make it draggable only from the dots and being able to expand my component,click on the fields etc.
I added the sensors the data-no-dnd="true" to my parent but nothing..

**Comment by JANEKKO** [comment]
【自动回复】已收到邮件。

**Comment by JonathanMEdwards** [comment]
These solutions don't work for me. They prevent my input control from being dragged but clicks are still not being delivered to it.

**Comment by JANEKKO** [comment]
【自动回复】已收到邮件。

**Comment by HyungwonJang0327** [comment]
> Hello everyone, I tried this approach but for some reason my didnt work. I have a very similar approach with this sandbox. https://codesandbox.io/p/sandbox/dnd-kit-form-builder-fii0zh?file=%2Fsrc%2Fstyles.css ![image](https://private-user-images.githubusercontent.com/45431116/299388450-62db8879-f134-4c93-8f98-2a6da2107922.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTE1OTMsIm5iZiI6MTcxNTU5MTI5MywicGF0aCI6Ii80NTQzMTExNi8yOTkzODg0NTAtNjJkYjg4NzktZjEzNC00YzkzLThmOTgtMmE2ZGEyMTA3OTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA5MDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NTIzZDQ2MjA2NmIwMmRiOTFkODk3MjBhNTY1MjA4YjgxMDc1NDJlZGI5ZGFjOGViNzM4MTJhNWNjOGI1YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A8zk82rx6H5r3_G5dcvoeyc-21Ac3ZswyG9luKk70vc) I want to make it draggable only from the dots and being able to expand my component,click on the fields etc. I added the sensors the data-no-dnd="true" to my parent but nothing..

I'm experiencing the same problem.
I think it'll work if I don't spread the listeners of useSortable to children, but I don't know how to stop it.

**Comment by JANEKKO** [comment]
【自动回复】已收到邮件。

**Comment by tom-leamon** [comment]
This seems very fundamental, I think the proposed solution should either be added to the docs or built into the library behind a prop like "allowEventPropagation" that does it behind the scenes.

**Comment by paddu1246** [comment]
Hi All,

in Dnd kit library input tag onchage event not fired, I was tried above approve, i didn't get any luck.   could please help me out this problem. 

Thank you in advance

**Comment by JANEKKO** [comment]
【自动回复】已收到邮件。

**Comment by ChTiSh** [comment]
@DjVreditel your solution worked beautifully, thank you. Post this as when I saw the recent comments regarding solutions not working I lost some faith wondering if some recent updates caused changes, but I shouldn't.

**Comment by JANEKKO** [comment]
【自动回复】已收到邮件。

**Comment by mikalai-sauchanka** [comment]
The suggested approach doesn't work in the latest version. I ended up replacing the activators (since it's a static prop, can be done once). Also canStartDrag can be anything you want.

```typescript
const FORBID_DRAG_ON = ["INPUT", "TEXTAREA"];
const canStartDrag = () => {
  if (document.activeElement) {
    const tagName = (document.activeElement as HTMLElement).tagName;
    if (
      FORBID_DRAG_ON.includes(tagName) ||
      (tagName === "DIV" && (document.activeElement as HTMLDivElement).contentEditable === "true")
    ) {
      return false;
    }
  }

  return true;
};

const patchActivator = <T extends SensorOptions>(activators: Activators<T>, eventName: string): Activators<T> => {
  const originalActivatorIndex = activators.findIndex((x) => x.eventName === eventName);
  const originalActivator = activators[originalActivatorIndex];

  activators[originalActivatorIndex] = {
    eventName: originalActivator.eventName,
    handler(...args) {
      return canStartDrag() && originalActivator.handler(...args);
    }
  };
  return activators;
};

patchActivator(KeyboardSensor.activators, "onKeyDown");
patchActivator(PointerSensor.activators, "onPointerDown");
```

**Comment by JANEKKO** [comment]
【自动回复】已收到邮件。

**Comment by 1used23** [comment]
More beautiful solution in my opinion, if you get "TypeError: Class constructor MouseSensor cannot be invoked without 'new'" with previous solutions:

`
import type { MouseEvent, TouchEvent } from 'react';
import { MouseSensor, TouchSensor } from '@dnd-kit/core';

const IGNORE_TAGS = ['BUTTON'];

// Block Dnd, if IGNORE_TAGS include elements tag or has data-no-dnd attribute
const customHandleEvent = (element: HTMLElement | null) => {
  let cur = element;

  while (cur) {
    if (IGNORE_TAGS.includes(cur.tagName) || cur.dataset.noDnd) {
      return false;
    }
    cur = cur.parentElement;
  }

  return true;
};

MouseSensor.activators = [
  {
    eventName: 'onMouseDown',
    handler: ({ nativeEvent: event }: MouseEvent) => customHandleEvent(event.target as HTMLElement),
  },
];

TouchSensor.activators = [
  {
    eventName: 'onTouchStart',
    handler: ({ nativeEvent: event }: TouchEvent) => customHandleEvent(event.target as HTMLElement),
  },
];`

**Comment by JANEKKO** [comment]
【自动回复】已收到邮件。

**Comment by benjamin-andersen** [comment]
In case anyone else stumbles on this issue like I did...

I was having issues with this solution https://github.com/clauderic/dnd-kit/issues/477#issuecomment-1713536492 not working very well when rendering a shadcn/ui Sheet (or Popover/Dialog etc.) within the draggable element. Clicking anywhere within the Sheet would bubble the event up to the draggable element and start dragging the element.

Stopping propagation of `pointerdown` and `keydown` events would prevent the Sheet from closing, so that had me stuck without any way to fix this using the custom sensor solution.

I was able to solve this without adding a visual drag handle by using a trick like this:

```tsx
<div className="relative">
  {/* this should be the first child, so the siblings can be clickable */}
  <button className="absolute inset-0" {...attributes} {...listeners} ref={setActivatorNodeRef}/>

  {/* ... rest of the interactable UI ... */}
  <button>look ma, no dragging</button>
</div>
```

Essentially you can have the handle positioned in a way so it fills the parent element by giving it an absolute position. If you can't make it the first child of the parent, then you could probably get away with messing with z-index on the children elements so the interactable elements (buttons, inputs, etc.) can be clicked without dragging.

The `pointerdown` and `keydown` events in the Sheet won't propagate to the `<button>` and start dragging because it's not an ancestor of the `<Sheet>` component.

You also don't need to create custom sensors and set data attributes on interactable elements.

**Comment by JANEKKO** [comment]
【自动回复】已收到邮件。
