### ISSUE TITLE
Css modules using scss should be renamed to *.module.scss

### ISSUE THREAD

**Issue by JamesGelok** [clauderic/dnd-kit#48]
Inside the components folder for stories, `Item.module.css` (and other css modules using scss) should be renamed to `Item.module.scss` to accurately reflect their contents.

**Comment by clauderic** [comment]
The files are not `scss`, they are PostCSS files with support for nesting and variables so technically a more accurate name would actually be `pcss`. 

Would happily accept a PR to change that, but for now going to close this issue as it is more of a nitpick with file nomenclature than an actual issue with the library.

**Comment by JamesGelok** [comment]
Gotcha, understandable. I had misunderstood bc it looked like scss and renaming worked to get it working on [codesandbox](https://codesandbox.io/s/wip-nested-virtualized-79vxm). 👍
