### ISSUE TITLE
Droppable area detect if sortable item dropped over

### ISSUE THREAD

**Issue by ruben00001** [clauderic/dnd-kit#49]
The docs state: "Use the useDroppable hook to set up DOM nodes as droppable areas that draggable elements can be dropped over."

I'm wandering if it's possible for droppable areas to detect if sortable elements are dropped over them?

Apologies in advance if I've missed something. It was straightforward to create a working example of a droppable area working with a draggable element. I've tried to have a droppable area inside and outside the SortableContext.

**Comment by ruben00001** [comment]
I may have jumped the gun here. Somehow it seems to be somewhat working when I tried to reproduce the issue in a sandbox. I'll close this issue for now.

**Comment by imwillhang** [comment]
Hey @ruben00001, how'd you figure this one out?

**Comment by ranbena** [comment]
Shouldn't be a problem as long as the Sortable and the Droppable are both nested within the same DndContext.
