### ISSUE TITLE
'Maximum update depth exceeded' error with Sortable

### ISSUE THREAD

**Issue by Dm1Korneev** [clauderic/dnd-kit#496]
Here is an example:
https://codesandbox.io/s/dnd-kit-issue-eq952

https://user-images.githubusercontent.com/7955306/139406591-7a542b60-c578-485f-9058-8abe8f376e5b.mov

The problem is because of items filtering. But if we remove it we get empty space when move item out of the container

`const filteredItems =
    activeId && isOutOfContainer
      ? items.filter((item) => item !== activeId)
      : items;`

https://user-images.githubusercontent.com/7955306/139406934-653e5071-a45e-42fd-9d45-5c52222f8017.mov

**Comment by thewaver** [comment]
Memoize your objects, so you don't pass a new ref every time, which causes the DOM tree to refresh.

```jsx
const filteredItems = useMemo(() => activeId && isOutOfContainer ? items.filter((item) => item !== activeId) : items, [items, activeId, isOutOfContainer]);
```

This is a problem throughout the code. For instance, you are also creating a new Object, and therefore passing a new ref, every time you compute your props.

**Comment by Dm1Korneev** [comment]
Thank you @thewaver 
But I got the same result with `useMemo`
Have updated the sandbox

**Comment by osamasaeed** [comment]
Hi, I also have the same issue with Sortable and useDroppable

**Comment by clauderic** [comment]
@Dm1Korneev this does not seem reproducible with the latest version of @dnd-kit. Here's a forked sandbox where all I did was upgrade the @dnd-kit dependencies to the latest versions https://codesandbox.io/s/dnd-kit-issue-forked-9iy42?file=/src/App.js

@osamasaeed feel free to re-open a new issue with a link to a CodeSandbox replicating the issue you are facing.

**Comment by Dm1Korneev** [comment]
Hey, @clauderic 
I still have the error at your link
Plise check it.
https://user-images.githubusercontent.com/7955306/148953660-4b38083c-bc09-463e-9daf-37625f3ca0b8.mov

**Comment by exah** [comment]
@Dm1Korneev @clauderic  I can confirm. 

I'm also experience `Maximum update depth exceeded` in the [forked codesandbox project](https://codesandbox.io/s/dnd-kit-issue-forked-9iy42?file=/src/App.js).

There is also error in `Accessibility` component: 

```log
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at DndContext (https://9iy42.csb.app/node_modules/@dnd-kit/core/dist/core.esm.js:1823:67)
    at App (https://9iy42.csb.app/src/App.js:111:61)
```

**Comment by jevakallio** [comment]
Can confirm this issue still persists with latest versions of dnd-kit 
```
    "@dnd-kit/core": "^5.0.1",
    "@dnd-kit/sortable": "^6.0.0",
```

In our case this issue is particularly hard to track down, because it only happens in minified production build of the app, and not in local dev. It's also rarer to reproduce in production builds with a debugger attached, leading me to think it's a timing-related issue.

**Comment by mvpindev** [comment]
I checked the forked sandbox aswell and was able to replicate it.
Imo this should be opened again.

**Comment by Android789515** [comment]
Getting the same issue; same error with <Accessibility>.

**Comment by giovannipds** [comment]
^ Me too

**Comment by abcghy** [comment]
I first use React 18 and the latest `createRoot` new API instead of render. And I found out that there are some issue with it (May be the concurrent mode?). So I remain the React 18 but used the deprecated api `render`. 
But then it keeps telling me `Maximum update depth exceeded`, I was confused. But then I think if the new API `createRoot` is wrong. Why can't the React 18 is wrong? So I downgrade it to React 17.0.2. And the error message is gone.

**Comment by wdj82** [comment]
Getting the same error

**Comment by darren10201** [comment]
same issue here as well

**Comment by ajmar3** [comment]
+1

**Comment by jelizarovas** [comment]
+1

**Comment by giovannipds** [comment]
Prolly this issue shouldn't be closed then

**Comment by IainAndrew** [comment]
+1

**Comment by allego0227** [comment]
me too

**Comment by heomeco2014** [comment]
Same on this one

**Comment by FindAPattern** [comment]
I ran into this issue with the standard nested container example. Calling `setState` inside of `onDragOver` was causing the nested state updates to exceed the stack limit. Moving the `setState` calls in `onDragOver` into the next animation frame stopped the error from happening, but I've probably broken some law of the universe. This probably isn't the correct solution, but hopefully it helps someone get through until the repo gets updated. 

(On that note, if someone smarter than me thinks there isn't an issue with doing this, I'd be happy to submit a PR.)

**Comment by heomeco2014** [comment]
> I ran into this issue with the standard nested container example. Calling `setState` inside of `onDragOver` was causing the nested state updates to exceed the stack limit. Moving the `setState` calls in `onDragOver` into the next animation frame stopped the error from happening, but I've probably broken some law of the universe. This probably isn't the correct solution, but hopefully it helps someone get through until the repo gets updated.
> 
> (On that note, if someone smarter than me thinks there isn't an issue with doing this, I'd be happy to submit a PR.)

Can you elaborate more on this part: 
` Moving the setState calls in onDragOver into the next animation frame stopped the error from happening`
I got the same error and want to fix it like you

**Comment by FindAPattern** [comment]
Again, something about this seems horribly wrong, but the idea is that you break the recursion by delaying the call to `setState`. The same thing would probably work with `setImmediate` / `setTimeout(..., 0)`. 

Simple example of a component that would break due to exceeding the stack limit:
```
function Component() {
  const [number, setNumber] = useState(0);

  useMemo(() => {
    if (number >= 100000) return;
    setNumber(number => number + 1);
  }, [number]);

  return <>{number}</>;
}
```

You can break the recursion this way:
```
function Component() {
  const [number, setNumber] = useState(0);

  useMemo(() => {
    if (number < 100000) return;
    setTimeout(() => setNumber(number => number + 1), 0);
  }, [number]);

  return <>{number}</>;
}
```

Here's a quick CodePen to demonstrate: https://codepen.io/pattrn/pen/BaMzERM.

**Comment by unxok** [comment]
@FindAPattern your solution worked for me! I was getting this error when calling a state setter from a zustand store in my handler for `onDragOver`

**Comment by timreach** [comment]
It seems that overriding the collision detection fixes this without having to use timeouts

https://github.com/clauderic/dnd-kit/issues/900#issuecomment-1879870810

**Comment by AmirhoseinHesami** [comment]
> @FindAPattern your solution worked for me! I was getting this error when calling a state setter from a zustand store in my handler for `onDragOver`

Hi! can you help me on this?
cause I have some problems with the example above I am not sure where to put this inside my onDragOver event
tnx

**Comment by hsavit1** [comment]
is this fixed on the next branch? I cant see an error being thrown on this example https://experimental--5fc05e08a4a65d0021ae0bf2.chromatic.com/iframe.html?args=&id=react-sortable-multiple-lists--grid&viewMode=story

code is here https://github.dev/clauderic/dnd-kit/blob/experimental/apps/stories/stories/react/components/Grid/Grid.tsx

**Comment by OmarAlSeddik** [comment]
> Again, something about this seems horribly wrong, but the idea is that you break the recursion by delaying the call to `setState`. The same thing would probably work with `setImmediate` / `setTimeout(..., 0)`.

What black magic is this? All I needed to fix this issue is to wrap my setState function inside a setTimeout function with a 0ms delay? I understand why it works but... Wow. Thank you!

**Comment by Artem-Arutunyan** [comment]
> Again, something about this seems horribly wrong, but the idea is that you break the recursion by delaying the call to `setState`. The same thing would probably work with `setImmediate` / `setTimeout(..., 0)`.
> 
> Simple example of a component that would break due to exceeding the stack limit:
> 
> ```
> function Component() {
>   const [number, setNumber] = useState(0);
> 
>   useEffect(() => {
>     if (number >= 100000) return;
>     setNumber(number => number + 1);
>   }, [number]);
> 
>   return <>{number}</>;
> }
> ```
> 
> You can break the recursion this way:
> 
> ```
> function Component() {
>   const [number, setNumber] = useState(0);
> 
>   useEffect(() => {
>     if (number >= 100000) return;
>     setTimeout(() => setNumber(number => number + 1), 0);
>   }, [number]);
> 
>   return <>{number}</>;
> }
> ```
> 
> Here's a quick CodePen to demonstrate: https://codepen.io/pattrn/pen/BaMzERM.
> 
> It's difficult for me to give an exact example from the documentation, since I ported everything over to MobX and did significant refactoring, so there's no longer an easy one-to-one comparison.

Dude, thank you so much!! 
I struggled for 3 days to find a solution.

**Comment by NishanBangera** [comment]
> Again, something about this seems horribly wrong, but the idea is that you break the recursion by delaying the call to `setState`. The same thing would probably work with `setImmediate` / `setTimeout(..., 0)`.
> 
> Simple example of a component that would break due to exceeding the stack limit:
> 
> ```
> function Component() {
>   const [number, setNumber] = useState(0);
> 
>   useEffect(() => {
>     if (number >= 100000) return;
>     setNumber(number => number + 1);
>   }, [number]);
> 
>   return <>{number}</>;
> }
> ```
> 
> You can break the recursion this way:
> 
> ```
> function Component() {
>   const [number, setNumber] = useState(0);
> 
>   useEffect(() => {
>     if (number >= 100000) return;
>     setTimeout(() => setNumber(number => number + 1), 0);
>   }, [number]);
> 
>   return <>{number}</>;
> }
> ```
> 
> Here's a quick CodePen to demonstrate: https://codepen.io/pattrn/pen/BaMzERM.
> 
> It's difficult for me to give an exact example from the documentation, since I ported everything over to MobX and did significant refactoring, so there's no longer an easy one-to-one comparison.

Thank you brother it has worked, this issue still persist in latest version of dnd-kit. What exactly is going wrong and what made it to work flawlessly?
