### ISSUE TITLE
Ensure higher zIndex for currently dragged item.

### ISSUE THREAD

**Issue by thewaver** [clauderic/dnd-kit#503]
I'm using someone else's example code for this (with some minor alterations).

https://codesandbox.io/s/vzx2s?file=/src/SortableItem.jsx

It appears that the `z-index` of the dragged item is not higher by default, causing the item to sometimes render below and sometimes above its sibling elements.

In fact, even manually setting the `z-index` appears to have no effect.

Is it a problem with the code in the example or with the framework?

**Comment by nikkizol** [comment]
Have the same issue! Is there any updates on it?

**Comment by clauderic** [comment]
This is because your element is not **positioned**.

Refer to https://developer.mozilla.org/en-US/docs/Web/CSS/z-index:

> The z-index CSS property sets the z-order of a **positioned** element and its descendants or flex items.

Set the `position` property of your elements to `relative` to make them positioned. Positioned elements are any value of `position` other than the default value of `static`.

**Comment by nikkizol** [comment]
@clauderic could you please show it on this example: https://codesandbox.io/s/dnd-kit-sortable-forked-2uk6v

**Comment by clauderic** [comment]
https://codesandbox.io/s/dnd-kit-sortable-forked-thc79?file=/src/SortableItem.jsx
