### ISSUE TITLE
Moving elements on pointer like in jQuery

### ISSUE THREAD

**Issue by Kuzry** [clauderic/dnd-kit#505]
Is there a way to get the effect of moving elements like in [jQuery Sortable](https://api.jqueryui.com/sortable/#option-tolerance) with the option set: tolerance: pointer?

**Comment by clauderic** [comment]
There are no collision detection strategies that work this way out of the box, but it should be fairly straightforward to author one yourself to replicate this behaviour. Refer to https://docs.dndkit.com/api-documentation/context-provider/collision-detection-algorithms#building-custom-collision-detection-algorithms
