### ISSUE TITLE
Multiple rows of the items with different sizes

### ISSUE THREAD

**Issue by nikkizol** [clauderic/dnd-kit#507]
I have multiple rows of the items with different sizes and they get mixed up while dragging.
When I use horizontalListSortingStrategy and move items on the same row - all good, but when I move item to a different row - then it gets mixed..

https://user-images.githubusercontent.com/45672257/142225483-1362b10b-ceda-4cbd-a230-eb6bc3ab7afb.mov

When I use rectSortingStrategy it also gets mixed.

https://user-images.githubusercontent.com/45672257/142225624-5405729c-02ba-4f6f-ac58-87abc44ccb33.mov

https://codesandbox.io/s/dnd-kit-sortable-forked-ie018?file=/src/App.jsx:270-289

**Comment by nikkizol** [comment]
I found this one https://github.com/clauderic/dnd-kit/issues/44#issuecomment-757312037 but is it possible to get this result without DragOverlay? Because if I don't use it I get this :

https://user-images.githubusercontent.com/45672257/142246399-9ace8053-e31b-4a4a-8c96-46df44304c7a.mov

**Comment by clauderic** [comment]
This use-case is exactly the same problem as what I outline in https://github.com/clauderic/dnd-kit/issues/44#issuecomment-757312037 yes.

What's the reason why you don't want to use `DragOverlay`?

**Comment by nikkizol** [comment]
@clauderic because in my case items are components with api calls and if I am using DragOverlay it takes few sec to render it.

**Comment by clauderic** [comment]
Separate your API calls from the presentational components.
