### ISSUE TITLE
Allow passing custom measuring function to `DragOverlay`

### ISSUE THREAD

**Issue by migueloller** [clauderic/dnd-kit#515]
We use dnd-kit to create sortable lists and sometimes these sortable lists are inside a popup menu. We use Popper.js to position these popup menus, which means that the draggable nodes have a CSS transform applied to them. Since `useDropAnimation` has a hard-coded `getViewRect`, it can't get the proper visual position of the draggable nodes. Changing this to `getBoundingClientRect` would fix this. Here's a video demonstrating the issue:

https://user-images.githubusercontent.com/5677929/142497431-fa4cf9d2-3a3d-415e-bc1f-8b907ea76465.mov

Here's the relevant line of code:

https://github.com/clauderic/dnd-kit/blob/1c6369e24ff338760adfb806c3017c72f3194726/packages/core/src/components/DragOverlay/hooks/useDropAnimation.ts#L57

Happy to open a PR that adds the `measuring` prop to `DragOverlay` similar to `DndContext` that can then pass it through to `useDropAnimation` so that instead of having `getViewRect` hard-coded one could pass in `getBoundingClientRect`. If this wouldn't be the desired API, happy to take a stab at alternatives.

**Comment by clauderic** [comment]
Hey @migueloller, I actually have a PR in progress that does just that. Should land soon, will also fix https://github.com/clauderic/dnd-kit/issues/464

**Comment by migueloller** [comment]
Awesome! Thanks @clauderic
