### ISSUE TITLE
Not displaying preview of the dragging item when in a virtualized list

### ISSUE THREAD

**Issue by danglduy** [clauderic/dnd-kit#526]
I'm having an issue of displaying the preview of a dragging item in a virtualized list.

It's when I removed this line https://github.com/clauderic/dnd-kit/blob/05d6a78a17cbaacd8dffed685dfea5a6ea3d38a8/stories/2%20-%20Presets/Sortable/5-Virtualized.story.tsx#L91
After dragging and scrolling passes the initial view, the preview of the dragging item will be disappeared.

I am using latest versions:
- @dnd-kit/core 4.0.3
- @dnd-kit/sortable 5.1.0

Demo

https://user-images.githubusercontent.com/38782010/143559073-465d3219-ec12-4233-9d36-fe2bf3bf158b.mp4

**Comment by clauderic** [comment]
This isn't a bug with @dnd-kit, this is just how virtualized lists work. When items scroll out of view, they get unmounted by the virtual list component.

If you're using [react-tiny-virtual-list](https://github.com/clauderic/react-tiny-virtual-list), you can use the `stickyIndices` prop to prevent the item from unmounting when it goes off screen:

```tsx
<VirtualList
  stickyIndices={activeId ? [items.indexOf(activeId)] : undefined}
```

**Comment by hanmaker-s1** [comment]
> 这不是一个错误@dnd-kit，这就是虚拟化列表的工作方式。当项目滚动出视图时，它们会被虚拟列表组件卸载。
> 
> 如果您使用的是[react-tiny-virtual-list](https://github.com/clauderic/react-tiny-virtual-list)，则可以使用`stickyIndices`prop 来防止项目在离开屏幕时卸载：
> 
> ```tsx
> <VirtualList
>   stickyIndices={activeId ? [items.indexOf(activeId)] : undefined}
> ```
If using another virtual library such as react-virtuoso, is there a solution for @dnd-kit?

**Comment by hanmaker-s1** [comment]
> This isn't a bug with @dnd-kit, this is just how virtualized lists work. When items scroll out of view, they get unmounted by the virtual list component.
> 
> If you're using [react-tiny-virtual-list](https://github.com/clauderic/react-tiny-virtual-list), you can use the `stickyIndices` prop to prevent the item from unmounting when it goes off screen:
> 
> ```tsx
> <VirtualList
>   stickyIndices={activeId ? [items.indexOf(activeId)] : undefined}
> ```

If using another virtual library such as react-virtuoso, is there a solution for https://github.com/dnd-kit?
