### ISSUE TITLE
DragOverlay doesn't take child (mui grid) size

### ISSUE THREAD

**Issue by nikkizol** [clauderic/dnd-kit#527]
I have Material UI Grid layout, and my items are wrapped in Grid mui elements, so when I drag grid item DragOverlay doesn't take size of that item. 

https://user-images.githubusercontent.com/45672257/143618375-ac4a6d4c-b0ca-4c96-a37d-d68a889992bc.mov

link to the sandbox - https://codesandbox.io/s/dnd-kit-sortable-forked-x5ou9?file=/src/SortableItem.jsx

Any suggestions?

**Comment by clauderic** [comment]
https://codesandbox.io/s/dnd-kit-sortable-forked-yg63p?file=/src/Item.jsx
