### ISSUE TITLE
TypeError `.getOwnerDocument` when clicking element - v4.0.3

### ISSUE THREAD

**Issue by kevinreber** [clauderic/dnd-kit#530]
Using `v4.0.3`, I'm getting a `TypeError: .getOwnerDocument` when attempting to click on an element

```
(0 , $csb___dnd_kit_utilities.getOwnerDocument) is not a function
browser
```

<div align="center">
<img src="https://user-images.githubusercontent.com/42260999/143925010-c284f91d-b78d-4830-a3b7-06250ec5a5cc.png" alt="screenshot" width="700" />
</div>

Deprecating down to `v1.0.1` works fine, but the most recent version(`v4.0.3`) doesn't allow me to drag and drop any elements.

[DND Kit - CodeSandbox Demo (Deprecated v1.01)](https://codesandbox.io/s/yt4rv?file=/src/SortableCard.jsx)
[DND Kit - CodeSandbox Demo (Updated v4.0.3)](https://codesandbox.io/s/billowing-wood-hxi05?file=/src/SortableCard.tsx)

**Comment by umutcanbolat** [comment]
Got the same error when experimenting with dnd-kit on codesandbox today. 

"@dnd-kit/core": "4.0.3",
"@dnd-kit/sortable": "5.1.0"

**Comment by umutcanbolat** [comment]
I was trying to code in the OVerview section here:
https://docs.dndkit.com/presets/sortable#overview

**Comment by drborges** [comment]
Same here:

```
"@dnd-kit/core": "4.0.3",
"@dnd-kit/sortable": "5.1.0"
```

I get the same error on CodeSandbox. I can confirm though, that downgrading `@dnd-kit/core` to `4.0.2` works like a charm.

**Comment by igordanchenko** [comment]
Adding `@dnd-kit/utilities` as a dependency seems to resolve this issue.

**Comment by clauderic** [comment]
Most likely mismatched versions of @dnd-kit packages installed. Make sure all packages are updated to the latest versions.
