### ISSUE TITLE
ie11 exception on drag 800a025e

### ISSUE THREAD

**Issue by cherepanov** [clauderic/dnd-kit#534]
I have custom sortable setup with dnd-kit. First tests with IE11 failed with exception raised here

```
private removeTextSelection() {
    this.document.getSelection()?.removeAllRanges();
}
```

Must be checked for non-empty selection before calling ```removeAllRanges()```
This should fix it

```
  private removeTextSelection() {
    const sel = this.document.getSelection();

    if (
      sel &&
      sel.rangeCount > 0 &&
      sel.getRangeAt(0).getClientRects().length > 0
    ) {
      sel.removeAllRanges();
    }
  }
```

BTW: to make it work under ie11 it also required to add WebAnimations polyfill

**Comment by Olegramm** [comment]
у меня тоже

**Comment by clauderic** [comment]
Feel free to open a pull request
