### ISSUE TITLE
Droppable area "shrinks" when scrolling list of draggable items

### ISSUE THREAD

**Issue by LorenzoScebba** [clauderic/dnd-kit#542]
Hello,

I'm having a problem using draggable items in an "overflowY: auto" list.

It seems like the droppable area shrinks when scrolling the list down, as seen in the example below:

![https://res.cloudinary.com/lorenzoscebba/video/upload/v1639391933/things/dndkit%20issue.gif](https://res.cloudinary.com/lorenzoscebba/video/upload/v1639391933/things/dndkit%20issue.gif)

This seems to be happening both in the version we are using (3.1.1) and in the latest version (4.0.3 at the time of writing).

A sandbox is available here: https://codesandbox.io/s/dndkit-overflowy-changesdroppableheight-6vqg3

Is there any way to tackle this problem?

Many thanks,
Lorenzo

**Comment by HelKyle** [comment]
Duplicate of [#483](https://github.com/clauderic/dnd-kit/issues/483)

**Comment by LorenzoScebba** [comment]
https://github.com/clauderic/dnd-kit/issues/483#issuecomment-985196079 fixes the problem. Thanks!
