### ISSUE TITLE
Droppable and Draggable at the same time

### ISSUE THREAD

**Issue by jguillaumesio** [clauderic/dnd-kit#545]
Hi all,
I've a quite simple problematic but I don't know which is the best solution to achieve it !
Actually i've an object that is draggable but also droppable, I've implemented draggable successfuly, but still impossible to wrap this to be droppable

`<div className={'wrapper'} ref={ref}>
            <div ref={childSetNodeRef}>
                <div ref={setNodeRef}
             style={{...style}}
             {...listeners}
             {...attributes}>
                <Stack>
                    {item.name}
                </Stack>
            </div>
            </div>
        </div>`

**Comment by clauderic** [comment]
Refer to how the `useSortable` hook work, which combines the `useDraggable` and `useDroppable` hooks.

The trick is to combine both the `useDraggable` and `useDroppable` refs https://github.com/clauderic/dnd-kit/blob/master/packages/sortable/src/hooks/useSortable.ts#L79
