### ISSUE TITLE
Could there be a MeasuringStrategy related to sortable that measures after sort?

### ISSUE THREAD

**Issue by jamwise** [clauderic/dnd-kit#546]
Currently the sortable feature does not work with elements of various sizes. The documentation and examples are a bit misleading in that they show a sortable experience where the position at which blocks find themselves can be of various sizes, but the content of the blocks themselves can't because it would require a remeasuring after they've flowed to their new layout. This is true for anything that doesn't have a fixed size.

So could there be a new MeasuringStrategy introduced which is triggered on drag start but also as soon as a sort operation completes? This seems like it would fix the issue unless I'm missing something.

**Comment by clauderic** [comment]
Seems to me like you're describing `MeasuringStrategy.Always`. Feel free to re-open if I'm misunderstanding your request.

**Comment by jamwise** [comment]
@clauderic unfortunately I'm not, I've tried that. The issue I'm describing is when sorting a list or grid with items that are of different size. As in their size is based on their contents not position in the list. Here's an example of what this might look like:

```
|‾‾‾‾‾|   |‾‾‾‾‾|
|  a  |   |  d  |
|_____|   |     |
          |_____|
|‾‾‾‾‾|
|     |   |‾‾‾‾‾|
|  b  |   |     |
|     |   |  e  |
|_____|   |     |
          |     |
|‾‾‾‾‾|   |_____|
|  c  | 
|_____|   |‾‾‾‾‾|
          |  f  |
          |_____|
```

Other libraries use a technique to achieve this called the FLIP technique. As soon as the elements on the page are sorted the new positions of the elements are calculated and then a css transform is applied to each one that puts it back at it's original position and animates their movement from the previous position to the new one.

This is what I meant by "is triggered on drag start but also as soon as a sort operation completes". In other words, could the flip technique be used to allow dnd-kit to re-calculate based on the actual positions the DOM elements will end up instead of just moving them to the same x/y position of the element they're being sorted with?
