### ISSUE TITLE
Question: How to know which input method was used on drag end?

### ISSUE THREAD

**Issue by pastur** [clauderic/dnd-kit#547]
`react-sortable-hoc` provides the native event on the `onSortEnd` callback, that makes it trivial to know which kind of input method was used. 

How can we tell from the `onDragEnd` handler if a drag/sort was performed using the keyboard, mouse, or touch?

**Comment by JuAn-Kang** [comment]
+1 -- would like to know as well. Do we have any way of knowing which input fired the DragEvents?

**Comment by omril1** [comment]
I have a requirement to make drag and drop that can also copy when a modifier key (command/ctrl) is pressed during the drag end, right now I'm using it during the drag start (onActivation or activationEvent) which is not ideal.

Do you mind if I make a PR for it?
