### ISSUE TITLE
dnd-kit/core package does not include or declare its license

### ISSUE THREAD

**Issue by jamin-aws-ospo** [clauderic/dnd-kit#55]
The NPM package format provides support for declaring a package's license:
https://docs.npmjs.com/cli/v6/configuring-npm/package-json#license

The above does not appear to be used by at least the `dnd-kit/core` package.  Haven't check others.

Additionally, while the repository has a [LICENSE](https://github.com/clauderic/dnd-kit/blob/master/LICENSE) file, it does not appear to be included in with the package build.

**Comment by clauderic** [comment]
Good callout, this was definitely an oversight, thanks for pointing this out.

Will be resolved in https://github.com/clauderic/dnd-kit/pull/56
