### ISSUE TITLE
Sortable does not swap items while dragging fast

### ISSUE THREAD

**Issue by crossjs** [clauderic/dnd-kit#554]
https://5fc05e08a4a65d0021ae0bf2-unebtvimdp.chromatic.com/?path=/story/presets-sortable-vertical--variable-heights

While dragging fast with tree fingers on Mac Trackpad, and the same on Windows with Mouse.

https://user-images.githubusercontent.com/1201028/147942765-4b6e166f-1ba4-4b95-b32f-919a4f4ce1f6.mov

**Comment by moxxuk** [comment]
This is a duplicate of #470

**Comment by crossjs** [comment]
close as duplicate
