### ISSUE TITLE
Live update of npm version?

### ISSUE THREAD

**Issue by StringKe** [clauderic/dnd-kit#559]
I found some issues that have been committed `commit` or `pull request` but no automated `Action` releases any `canary` or `beta` versions, and I can't test within my project to see if these are fixed in the new version.

**Comment by clauderic** [comment]
Can you elaborate? I'm not sure I understand

**Comment by StringKe** [comment]
use `Github Action` to automatically publish test versions when you merge code or commit code.

**Comment by clauderic** [comment]
This is already the case, @dnd-kit packages are released under the `next` tag on npm anytime a commit is merged to the master branch.
