### ISSUE TITLE
[Sortable] No animation present when not using DragOverlay

### ISSUE THREAD

**Issue by riosn-n** [clauderic/dnd-kit#565]
If a sortable element is dropped in an empty area there is no animation to return the item to its original position. The animation seems to be present when the DragOverlay is used, or when the drag operation is cancelled (as opposed to dropping the item).

Without DragOverlay (item immediately reappears in its original position):
![no animation sortable](https://user-images.githubusercontent.com/33673026/148624256-9ef08113-d75e-4131-9e64-8cca88323c76.gif)

With DragOverlay (item is returned to its original position smoothly):
![animation sortable](https://user-images.githubusercontent.com/33673026/148624264-7172c5f9-2c4b-4c02-89b0-f962ae04ecd8.gif)

**Comment by clauderic** [comment]
This isn't really a bug. The drop animation is a feature of `<DragOverlay>`. If you only use `useDraggable` or `useSortable`, you have to implement the drop animation yourself (for example, by adding a transition when not dragging).

**Comment by riosn-n** [comment]
Shouldn't that behavior be part of the library? It seems that, even without a `DragOverlay`, an animation is already present when the drag operation is cancelled.

![cancelling drag operation](https://user-images.githubusercontent.com/33673026/148627908-90402f42-bd9b-4f3b-8681-83c62bc23bca.gif)

**Comment by jmcannon** [comment]
> This isn't really a bug. The drop animation is a feature of `<DragOverlay>`. If you only use `useDraggable` or `useSortable`, you have to implement the drop animation yourself (for example, by adding a transition when not dragging).

Hi @clauderic, I tried to do this (setting a transition when isDragging is false), but am getting jumpy behavior when I release the SortableItem. Assuming this is a really quick implementation, would you mind providing a quick code snippet, or nudging me in the right direction? Do I need to transition anything besides 'transform'?
