### ISSUE TITLE
ResizeObserver issues with Server Side Rendering and older browsers

### ISSUE THREAD

**Issue by Manduro** [clauderic/dnd-kit#572]
The new `ResizeObserver` features cause some issues when using Server Side Rendering or older browsers, as it does not exist in those environments.

One use can be manually disabled using the `resizeObserverConfig`, but this one can not:
https://github.com/clauderic/dnd-kit/blob/eb6d4c95227631d8e05bfb31685886458f995c93/packages/core/src/hooks/utilities/useDragOverlayMeasuring.ts#L34

It can likely be solved by checking if the ResizeObserver is supported before using it.

This affects `@dnd-kit/core@5.0.0`

**Comment by igordanchenko** [comment]
Experiencing the same issue here with the latest `@dnd-kit`

Next.js build is failing both locally and on Vercel:
```
Error occurred prerendering page "/examples/sortable". Read more: https://nextjs.org/docs/messages/prerender-error
--
15:31:28.965 | ReferenceError: ResizeObserver is not defined
15:31:28.965 | at /vercel/path0/node_modules/@dnd-kit/core/dist/core.cjs.production.min.js:1:21433
15:31:28.966 | at Object.Ja [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:27:240)


```

**Comment by clauderic** [comment]
Working on it, will ship a patch release

**Comment by clauderic** [comment]
@igordanchenko / @Manduro, can either of you test out that the fix shipped in #573 and report back here as to whether it resolves the issue?

You can test it out before I ship the official `5.0.1` patch release by installing the version of `@dnd-kit/core` tagged with `next` on npm:

```
npm install @dnd-kit/core@next
```

Or by manually adding to your `package.json`:

```
`"@dnd-kit/core": "5.0.1-next-2022010212452"`
```

**Comment by igordanchenko** [comment]
@clauderic, `5.0.1-next-2022010212452` worked like a charm! 

Here is a live Next.js page with the latest `@dnd-kit/core` - https://react-photo-album.com/examples/sortable

**Comment by Manduro** [comment]
Works great, thanks @clauderic

**Comment by clauderic** [comment]
Released https://github.com/clauderic/dnd-kit/releases/tag/%40dnd-kit/core%405.0.1
