### ISSUE TITLE
On the IOS Systme 12, dragging will report an error

### ISSUE THREAD

**Issue by jclrie** [clauderic/dnd-kit#583]
![24093e62266e4470d2b6e242](https://user-images.githubusercontent.com/41005089/149449042-183f5f53-1065-4a8d-83e5-886b848df490.jpg)

**Comment by clauderic** [comment]
This library uses the [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API/Using_the_Web_Animations_API). Refer to [browser support](https://caniuse.com/web-animation). Add a polyfill if you need to expand browser support https://github.com/web-animations/web-animations-js
