### ISSUE TITLE
Why im getting this type error??

### ISSUE THREAD

**Issue by pradhuman01** [clauderic/dnd-kit#586]
![Screenshot 2022-01-15 at 10 05 45 PM](https://user-images.githubusercontent.com/24241624/149630113-c0dc9e84-2385-4487-a15b-c40a563ee18f.png)

Im using NextJS with Typescript and its showing me this error..!!

**Comment by clauderic** [comment]
What version of TypeScript are you using?

Works fine in versions 3.8.3 and above https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwK4GcCmBlaMCGAjAGzQF84AzKCEOAcgAEATAOwYFoBrYGAehW3yI0A3ACgRZJEwDGMYBCZwAKmhQwAFAEpEIuLtSZ+hNGoTAGALlowVMGsQ2jiQA

**Comment by anttikaikkonen** [comment]
I got the same error but it fixed after restarting vscode. I think this happens when you install `@dnd-kit/sortable` before installing `@dnd-kit/core`.
