### ISSUE TITLE
Is there any way we can see storybook code ??

### ISSUE THREAD

**Issue by pradhuman01** [clauderic/dnd-kit#587]
I want to create same example feature in my app. How can i see the story code ? Please help here.. 
https://5fc05e08a4a65d0021ae0bf2-goamnjvxea.chromatic.com/?path=/docs/presets-sortable-vertical--without-drag-overlay

**Comment by WuJiY** [comment]
you can find it from https://github.com/clauderic/dnd-kit/tree/master/stories/2%20-%20Presets/Sortable
