### ISSUE TITLE
is it possible to get overId and activeId on dndcontext modifiers ? 

### ISSUE THREAD

**Issue by idhard** [clauderic/dnd-kit#59]
hey, awesome library! really smooth transitions   

is it possible to get the overId and activeId on a custom modifier context ? I would like to apply custom restrictions based on the type of the element i'm dragging rather than its position. 

thanks

**Comment by clauderic** [comment]
Hey, not currently, but this would be a fairly straightforward change. If you'd like to and have time to do so, PRs are welcome 🙏

**Comment by leon-marzahn** [comment]
This would be cool to have!

**Comment by clauderic** [comment]
Added in this PR #207
