### ISSUE TITLE
Overlay transitions to wrong position when updating state via useDndMonitor

### ISSUE THREAD

**Issue by joshjg** [clauderic/dnd-kit#593]
The overlay appears to move back to the original position, rather than the new position. I'm guessing this is because the `onDragEnd` listener in `useDndMonitor` gets called after an additional render when compared with the `onDragEnd` prop on `DndContext`.

I also noticed the same issue when my list order state resides in Apollo Client cache, and I trigger a cache update from `onDragEnd` (even when using the prop version). Again I think this is due to one or more renders before the change is reflected.

Reproduction: https://codesandbox.io/s/gracious-dhawan-uv9b1?file=/src/App.js

The animation was better in the previous major version (4.x), although there is some strangeness in the movement of the other items: https://codesandbox.io/s/confident-saha-egfvy?file=/src/App.js

**Comment by dontsave** [comment]
i'm having the same issue with both `useDndMonitor` and the apollo cache. maybe there is a way to prevent the animation for a tick or two?

**Comment by KatFishSnake** [comment]
Same here, can anyone take a look at this 🥺
