### ISSUE TITLE
Animations after moving 

### ISSUE THREAD

**Issue by atomcorp** [clauderic/dnd-kit#615]
Hello, nice work on dnd-kit!

Noticed a subtle issue with the animations, it's easy to reproduce on the [Removable items storybook example](https://5fc05e08a4a65d0021ae0bf2-goamnjvxea.chromatic.com/?path=/docs/presets-sortable-vertical--removable-items), simply resize the screen and delete an item - the animation will transition from the position before the resize.

I haven't found a way to force dnd-kit to refresh to update the positions. Is there a workaround for this?

Thank you 🙏

https://user-images.githubusercontent.com/3504434/152524716-d6f5fea2-3f73-4d39-ad2c-71ec5c7615cc.mov

**Comment by clauderic** [comment]
@atomcorp you can force @dnd-kit to re-measure items like so:

```ts
import {useDndContext} from '@dnd-kit/core';

function MeasureOnWindowResize() {
  const {measureDroppableContainers} = useDndContext();

  useEffect(() => {
    function handleResize() {
      measureDroppableContainers();
    }
    
    window.addEventListener('resize', handleResize);
    
    return () => window.removeEventListener('resize', handleResize);
  }, [measureDroppableContainers]);
}

function App() {
  return (
    <DndContext>
      {...}
      <MeasureOnWindowResize />
    </DndContext>
  );
}
```

For the moment, because layout animations are an experimental feature, there are no plans to do this by default.

**Comment by clauderic** [comment]
For layout animations to work, you need to update the `measuring` configuration of `<DndContext>` and also set the `animateLayoutChanges` prop on `useSortable`.

Did you do both of these things?

Refer to:

https://github.com/clauderic/dnd-kit/blob/master/stories/2%20-%20Presets/Sortable/1-Vertical.story.tsx#L152-L161

**Comment by atomcorp** [comment]
Thank you, yes I have those. Animations in general work great. It was just invoking measureDroppableContainers(); didn't seem to have an effect.
