### ISSUE TITLE
custom collision algorithm docs outdated?

### ISSUE THREAD

**Issue by patricktyndall** [clauderic/dnd-kit#616]
Hi, I'm trying to implement a custom collision detection per the docs (exact use case of a sortable list w/ trash). https://docs.dndkit.com/api-documentation/context-provider/collision-detection-algorithms

I implemented the below code and provided it to the `collisionDetection` prop.

```
import {closestCorners, rectIntersection} from '@dnd-kit/core';

function customCollisionDetectionStrategy(rects, rect) {
  const trashRect = rects.filter(([id]) => id === 'trash');
  const intersectingTrashRect = rectIntersection(trashRect, rect);

  if (intersectingTrashRect) {
    return intersectingTrashRect;
  }

  const otherRects = rects.filter(([id]) => id !== 'trash');
  
  return closestCorners(otherRects, rect);
};
```

When I do this, the arguments passed in are a completely different shape than what it is in the docs (the code above obv does not work).

Are there up to date docs somewhere, or am I using this incorrectly? I am on ` "@dnd-kit/core": "^5.0.1",`

**Comment by danglduy** [comment]
@patricktyndall I'm not sure if you have solved the issue, but anyway hope this can help you.
The docs is outdated as it was written for the package's previous version. However, the package's author gives a working example as you can check here:
https://github.com/clauderic/dnd-kit/blob/master/stories/2%20-%20Presets/Sortable/MultipleContainers.tsx#L188
