### ISSUE TITLE
Scrolling disabled when using bootstrap

### ISSUE THREAD

**Issue by PaddyWitzigmann** [clauderic/dnd-kit#617]
Hey guys,

first, thanks for this incredible library! I love using it!
Currently I'm having a problem that I can't get rid of when using the library together with bootstrap. 

When I import bootstrap into the project the window isn't scrolling anymore when I am dragging an element up or down. 
Here is a sandbox illustrating the problem: https://codesandbox.io/s/dnd-kit-bootstrap-scrolling-bug-u3jg2?file=/src/index.js
Comment out the bootstrap import in the index.js file in line 3 to see the difference.

Do you have any idea how I can solve this?

I know this isn't a dnd-kit specific problem, but I can imagine that many people would like to use dnd-kit together with bootstrap in one project. 

Thanks a lot for your help!

**Comment by JasonHenson** [comment]
This should really be noted somewhere for bootstrap users because it took me awhile of troubleshooting to find this answer.
