### ISSUE TITLE
No way to fully disable useSortable/SortableContext

### ISSUE THREAD

**Issue by SashaSirotkin** [clauderic/dnd-kit#618]
## Use-case

You want to conditionally prevent a card from being moved to an entire column.

## Why this happens

If you have the following code:
```js
useSortable({
  id: 'example',
  disabled: true,
});
```

[This will disable dragging the card](https://github.com/clauderic/dnd-kit/blob/1ade2f34403ba1d5a87cbd3ce1cff62860860501/packages/sortable/src/hooks/useSortable.ts#L92) , but it will still be a drop location since [`disabled` is not applied in useDroppable within useSortable](https://github.com/clauderic/dnd-kit/blob/1ade2f34403ba1d5a87cbd3ce1cff62860860501/packages/sortable/src/hooks/useSortable.ts#L67).

This is fine in situations when you want, for example, to prevent a card from being moved in a column but still want to be able to place cards above or below it.

## Current workaround

Conditionally re-render the card without the `useSortable` props if the card needs to be fully disabled. Custom logic needed is to handle the situation when SortableContext itself is the drop target.

## Proposed solution

Naively, there are there are ways to solve this problem:

1.  Allow the `useSortable`'s  `disabled` property to accept a boolean (for the current behaviour) an object in the form of `{ draggable: boolean, droppable: boolean}`. If you use the object version of `disabled`, you can decide to what extent the Sortable becomes disabled.
2. Add `disabled` as a prop to `SortableContext` which will fully disable it and all of its children Sortables.

**Comment by clauderic** [comment]
This will be resolved by https://github.com/clauderic/dnd-kit/pull/754
