### ISSUE TITLE
Incorrect detection of over container with a long scrolling container

### ISSUE THREAD

**Issue by ZipBrandon** [clauderic/dnd-kit#62]
I am dragging from one Droppable container to another Droppable/Sortable container. If the source Droppable has many items in it and the the destination Droppable does not have as many items, the over container still registers the source container even though I am over of the destination.  Curiously, the source container will scroll until it reaches some threshold and then it correctly detects the correct over container.

https://user-images.githubusercontent.com/68867795/104829826-ab02b080-5845-11eb-8791-d9a6b043c838.mp4

**Comment by siggirh** [comment]
@ZipBrandon Did you ever solve your problem here?

**Comment by clauderic** [comment]
This should no longer be an issue with the latest versions of @dnd-kit (version @dnd-kit/core^5.0.0), it was fixed by #518 

Feel free to re-open a new issue if you run into other problems with the latest version, along with a CodeSandbox replicating the issue.

**Comment by siggirh** [comment]
Ahh, I just installed the library a couple days ago, didn't notice there was a new version.

It's definitely fixed in latest. Thank you very much @clauderic!
