### ISSUE TITLE
Moving Grid Item to first column in previous row triggers undesirable scroll

### ISSUE THREAD

**Issue by bobbyshaw** [clauderic/dnd-kit#625]
**Steps to reproduce:**

1. Use Grid Layout
2. Move item from second row to first column of first row

**Expected result:**

Item moves without the scroll position changing

**Actual result:**

Scroll position is reset

 (this is not experienced when dragging item to any other column of first row)

**Reproduction environment:**

I can reproduce this on one of your examples: https://5fc05e08a4a65d0021ae0bf2-goamnjvxea.chromatic.com/iframe.html?id=examples-pages-layout--grid&args=&viewMode=story

https://user-images.githubusercontent.com/553566/154319259-e2188062-3901-43ca-8816-885449440123.mp4

**Additional information**

The problem doesn't seem to occur on some other sandbox implementations, e.g. https://codesandbox.io/s/silly-chebyshev-x1yu46

I should add that this is most notable in my use case where my cards have a "move to top" button. This causes a pretty disruptive experience when moving multiple items from the end of the list to the start of the list as the user has to repeatedly scroll back down. 

I'm not sure if this is a problem within the library or a side-effect of something else but any advice would be appreciated. 

Many thanks for a fantastic library.

**Comment by vassbence** [comment]
I think this is caused by the same thing that's causing #601

**Comment by bobbyshaw** [comment]
Hi @vassbence. I did wonder the same. However, I disabled auto-scroll and the problem still existed so I'm not sure. The problem also occurs even when changing the sortable items array which confused me somewhat.

**Comment by clauderic** [comment]
Hey @bobbyshaw, the issue you're seeing has nothing to do with @dnd-kit, in fact, you could replicate the issue without using @dnd-kit at all and simply modifying the order of the items array.

The behaviour you're seeing is a featured called scroll anchoring, which is a feature that is enabled by default in most browsers to try to minimize layout shifts. You can disable this functionality by setting the [`overflow-anchor`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor) CSS property to `none` on the scrolling element (in this case, the document body)

**Comment by bobbyshaw** [comment]
@clauderic Woh, thanks! I wasn't convinced it was an issue with the library but thanks for confirming & teaching me something new 🙇‍♂️
