### ISSUE TITLE
Scroll behavior smooth on keyboard sensor

### ISSUE THREAD

**Issue by lispz1610** [clauderic/dnd-kit#627]
When you press and keep the arrow keys, the scroll ends up stopping.

Here's an [example](https://5fc05e08a4a65d0021ae0bf2-goamnjvxea.chromatic.com/?path=/story/presets-sortable-horizontal--scroll-container) of this happening in one of the examples oft the lib
And here's a [video](https://youtu.be/X7XvCXE2TUU) showing the problem above occurring

The unique way I'm able to fix it, it was changing the default to 
```
useSensor(KeyboardSensor, {
  coordinateGetter: sortableKeyboardCoordinates,
  scrollBehavior: 'auto'
}),
```

**Comment by victordiogo** [comment]
I have the same problem.

**Comment by clauderic** [comment]
This is a bug in Chrome, you can replicate it without @dnd-kit with the following-code:

```js
document.addEventListener('keydown', () => window.scrollBy({left: 100}));
```

You can also replicate the bug with an interval:
```js
setInterval(() => window.scrollBy({left: 100}, 15);
```

Refer to the Chromium bug for updates:
https://bugs.chromium.org/p/chromium/issues/detail?id=1289304&q=smooth&can=2
