### ISSUE TITLE
Sortable elements in multiple containers do not receive 'transform' property

### ISSUE THREAD

**Issue by soplanstudio** [clauderic/dnd-kit#63]
Hello, based on the documentation, I am trying to create sortable elements in multiple containers, however, when dragging the elements in the same container, no return in "transform".

I'm a beginner in react, and I'm confused if this could be a bug, or if I'm missing some information.

I reproduced what I'm trying to do here:
https://codesandbox.io/s/friendly-glitter-5jlpf

Thanks for the library and attention.

**Comment by clauderic** [comment]
Hey @soplanstudio,

The only issue with the code above is how you're currently passing `items` to `<SortableContext>`; it expects a sorted array of unique identifier strings, but you're passing it an array of objects:

```jsx
// Bad
<SortableContext items={[{id: 'A1'}, {id: 'A2'}, {id: 'A3'}]} />

// Good
<SortableContext items={['A1', 'A2', 'A3']} />
```

To fix this in your case:
```jsx
<SortableContext items={items[gallery].map(({id}) => id)} />
```
