### ISSUE TITLE
useDndMonitor() hook always re-renders the component instead of firing callbacks

### ISSUE THREAD

**Issue by saravanan10393** [clauderic/dnd-kit#636]
Doc says
```
The `useDndMonitor` hook can be used within components wrapped in a DndContext provider to monitor the different drag and drop events that happen for that DndContext
```
Example:
```
  useDndMonitor({
    onDrop: () => {
      // this callback will get call when the drop occurs
    }
  });
```

From the above signature, My understanding was that, onDrop will be called when user drop item on the droppable.

But it re-renders the component on each mouse move. 
It should not re-renders the component. It should only call the callback. 

Here is demo Link
[https://codesandbox.io/s/dndkit-issue-demo-m5xc7j?file=/src/App.js](https://codesandbox.io/s/dndkit-issue-demo-m5xc7j?file=/src/App.js)

This makes this hook un-usable since it re-renders always regardless of an event i wish to get notify.

**Comment by saravanan10393** [comment]
@clauderic can the Monitor logic can be implemented using some sort of event emitting method instead of relaying on the react context?

**Comment by clauderic** [comment]
> Can the Monitor logic can be implemented using some sort of event emitting method instead of relaying on the react context?

This would be ideal yes, as it would also be synchronous rather than the current asynchronous approach. Unfortunately this isn't something I have time to into at the moment as there are higher priority issues for me to focus on. If this is something you need, I would gladly accept a PR where we can discuss this further.

**Comment by saravanan10393** [comment]
@clauderic i have solved the issue outside of this package using the principle of `use-context-selector` package. 
Here is the code:

[https://codesandbox.io/s/dndkit-issue-demo-m5xc7j?file=/src/dndmonitor.js](https://codesandbox.io/s/dndkit-issue-demo-m5xc7j?file=/src/dndmonitor.js)

if this is fine, we can change the MonitorContext inside the src code.

**Comment by Brian-McBride** [comment]
Hrm, I bet this might be related to the #623 issue. 
Inside the `SortableContext` provider component is `useDndContext`

**Comment by saravanan10393** [comment]
Might be. But In this case, `useDndMonitor` is a external hook to listen to events happening inside `usedndcontext`. I feel Re-rendering UI instead of only firing callback is not something  right.
