### ISSUE TITLE
Console error when unmounting a DndContext

### ISSUE THREAD

**Issue by cantoniriccardo** [clauderic/dnd-kit#637]
Hi, great work with dnd-kit, I really like it.

I'm experiencing the console error "Can't perform a React state update on an unmounted component" every time I unmount a DndContex containing a SortableContext with some items. I don't know if I'm missing something or if it is a DndContex issue.

I created a siple app to reproduce the bug: [https://codesandbox.io/s/dnd-kit-unmount-issue-2kmpjw?file=/src/App.js](https://codesandbox.io/s/dnd-kit-unmount-issue-2kmpjw?file=/src/App.js)

Thanks!

**Comment by Manganumapp** [comment]
I have the same problem.

**Comment by kiselyou** [comment]
Somebody have any ideas to fix it?

**Comment by yankovichv** [comment]
Me too, please fix it!

**Comment by sawadyecma** [comment]
Hi !

I have the same problem.

It is reproduced without SortableContext.

I created a app to reproduce: https://codesandbox.io/s/dnd-kit-unmount-issue-forked-rm0p7u

**Comment by skyliwq** [comment]
+++

**Comment by sawadyecma** [comment]
I could prevent that error by putting `DndContext` outside the unmounted component.

This is an example app.

https://codesandbox.io/s/trusting-chandrasekhar-1sn9fe

I'm going to try it with using SortableContext.

**Comment by sawadyecma** [comment]
I found that only `useDraggable` reproduce the error while unmounting.

https://codesandbox.io/s/xenodochial-volhard-ldy93r

So it might be required to fix `useDroppable`.

**Comment by clauderic** [comment]
This is fixed as of `@dnd-kit/core^5.0.3`
