### ISSUE TITLE
Dragged items don't stay with mouse when zoomed in or out

### ISSUE THREAD

**Issue by KevinMusgrave** [clauderic/dnd-kit#638]
I'm using dnd-kit within [react-flow](https://github.com/wbkd/react-flow), which provides a zoomable map environment.

At the default zoom level, dragging works fine. When zoomed in, the dragged item moves more than the mouse pointer. When zoomed out, the dragged item moves less than the mouse pointer.

Here's a sandbox where you can reproduce the issue: https://codesandbox.io/s/dnd-kit-react-flow-tcfed8

And here's a gif to illustrate:
![brave_UswXKzaRQs](https://user-images.githubusercontent.com/2314891/156040329-7eb1cd77-52ae-4d7e-a075-9e8a88ef451b.gif)

Any suggestions for how to fix this? Would react-flow's [internal transform state (pan and zoom values)](https://github.com/wbkd/react-flow/blob/main/src/store/index.ts) be useful in this case?

**Comment by efossvold** [comment]
I am also experience this issue, is there a fix or workaround for it?

**Comment by efossvold** [comment]
I solved by using a modifier.

Hook to create the modifier (takes zoom/scale as an arg):
```
  export const useDragWithZoomModifier =
  (zoom: number): import('@dnd-kit/core').Modifier =>
  args => {
    const { transform } = args
    return {
      ...transform,
      x: transform.x / zoom,
      y: transform.y / zoom,
    }
  }
```

Then apply the modifier in the DndContext:
```
  ...
  const zoom = useZoom() // your own implementation to get zoom
  const transformer = useDragWithZoomModifier(zoom)

  useEffect(() => {
    setCanvasOffset([canvas.x, canvas.y])
  }, [canvas.x, canvas.y])

  return (
    <DndContext modifiers={[transformer]}>
   ...
```

**Comment by KevinMusgrave** [comment]
Thanks @efossvold that works! The only problem is that the other elements not being dragged don't seem to get this modifier applied. So the element being dragged follows the mouse now, but the other items getting re-arranged are still moving as if we're at the original zoom level.

**Comment by KevinMusgrave** [comment]
This worked:

```javascript
  function transformWithZoom(transform) {
    if (transform) {
      return {
        ...transform,
        x: transform.x / zoom,
        y: transform.y / zoom,
      };
    }
    return transform;
  }

  const { attributes, listeners, setNodeRef, transform, transition } = useSortable({id});

  const scaledTransform = transformWithZoom(transform);

  const style = {
    transform: CSS.Transform.toString(scaledTransform),
    transition,
  };
```

**Comment by SreedharAvvari** [comment]
> The only problem is that the other elements not being dragged don't seem to get this modifier applied. So the element being dragged follows the mouse now, but the other items getting re-arranged are still moving as if we're at the original zoom level.

@KevinMusgrave I'm still seeing the above problem you mentioned & trying to troubleshoot this; Did you had to do anything else apart from the changes in https://github.com/clauderic/dnd-kit/issues/638#issuecomment-1133514510
Also it would be helpful if you can share how you are getting reactflow zoom level?
