### ISSUE TITLE
Unwanted animation in sortable list when moving between multiple containers

### ISSUE THREAD

**Issue by vkammerer** [clauderic/dnd-kit#64]
Hello and thank you for the great library,

I noticed unwanted artefacts in my implementation of a dnd between multiple containers of sortable items, which was an adaptation of your `<MultipleContainers />` component demoed [in the story](https://github.com/clauderic/dnd-kit/blob/d13d28471ec7716f08e211647cad89ae3c11dd06/stories/2%20-%20Presets/Sortable/MultipleContainers.tsx).

After a while debugging it, I realised the same visual glitch is present in the story itself.   
In order to reproduce it, you can:
- go to the story at https://5fc05e08a4a65d0021ae0bf2-fseheekyit.chromatic.com/?path=/story/presets-sortable-multiple-containers--vertical
- drag the first item of the first container (A1) from its position to the bottom of its list (under A5)
- up to that point, all is well: the other items in the list (A2, A3, A4 and A5) have been properly animated to be positioned to their desired position (= at the beginning of the list)
- now keep dragging A1 to the B list: you'll notice that **A2, A3, A4 and A5 are animated again** from their original position to their desired position

That's for the bug itself. Regarding the functionality's API (dragging items from a list to another): do you think users should implement the low level transferring from one list to another themselves, as [visible in the current story](https://github.com/clauderic/dnd-kit/blob/d13d28471ec7716f08e211647cad89ae3c11dd06/stories/2%20-%20Presets/Sortable/MultipleContainers.tsx#L179-L214), or do you think the library should include an easier solution?

**Comment by clauderic** [comment]
Hey @vkammerer, sounds like a bug. Could you record a video of the issue to help me visualize it?

**Comment by vkammerer** [comment]
sure, here it is:
- I drag A1 under A5 and all is correctly animated and positioned
- look at the A column when A1 is drag onto the B list: the A items are animated again (even though they should remain still)

https://user-images.githubusercontent.com/1177483/105116382-894c4680-5b2f-11eb-8f2d-313ead755f87.mov

**Comment by yuri-scarbaci-lenio** [comment]
is it a bug tho?
in the video what is happening is that you are resizing the container to fit the new list which has 1 less item then before, as in the list A is not re-animating, it's just re-sizing ?

**Comment by reverie** [comment]
@yuri-scarbaci-lenio I think the bug isn't that the container resizes, but that A2-A5 "jump" a little when A1 leaves the container. If you remove the last item from a container, and the container shrinks, there should normally be no need to reposition the remaining items.
