### ISSUE TITLE
Button within sortable component?

### ISSUE THREAD

**Issue by BenRauzi** [clauderic/dnd-kit#640]
~~Is there a way to have a clickable button within the sortable? For me this causes the drag action unless I spam click 3-4 times.~~

~~Not quite sure, some examples I've seen have this working fine but in my case (possibly due to button styling?) it breaks when adding listeners to the sortable.~~

Buttons inside of sortable components are broken in newer versions. `onClick` action is not performed

**Comment by clauderic** [comment]
This is by design. If you want to have interactive elements with a draggable element, use activation constraints such as `delay` or `distance`

https://docs.dndkit.com/api-documentation/sensors/pointer#activation-constraints

Alternatively, use a drag handle.
