### ISSUE TITLE
The position of the dropped item has been calculated incorrectly when using virtualized list with variable sized items

### ISSUE THREAD

**Issue by ccpu** [clauderic/dnd-kit#641]
I am using 'react-window' to handle virtualized variable sized list items (`VariableSizeList`).

It appears that `dnd-kit` is not able to calculate the drop position of an item correctly if the position of the list items are `absolute` with variable sizes:

[![Edit on CodeSandbox](https://user-images.githubusercontent.com/4041334/156525026-4a5adac9-7b1b-4da8-a151-b0a7bdcfe83e.gif)]

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dnd-kit-virtualized-variable-size-list-oxr3ty?file=/src/App.tsx:206-222)

**Comment by clauderic** [comment]
This is actually not a bug with @dnd-kit. You need to reset the cached data of `react-window` on drop:
https://codesandbox.io/s/dnd-kit-virtualized-variable-size-list-forked-uzhkc6?file=/src/App.tsx

<img width="641" alt="Screen Shot 2022-03-03 at 11 00 04 AM" src="https://user-images.githubusercontent.com/1416436/156602362-264e7ae4-a7af-4bbb-8f6f-36193a929998.png">
