### ISSUE TITLE
Is it possible: implementing a sortable, vertical list with swipe (left/right) gestures

### ISSUE THREAD

**Issue by Sorgrum** [clauderic/dnd-kit#643]
Hi, I'm currently using `useSortable` to create a sortable vertical list. This works perfectly. 

My sensor has a 250ms delay.
```typescript
useSensor(PointerSensor, {
  activationConstraint: {
    delay: 250,
    tolerance: 5,
  },
}),
```

Would it be possible to additionally add more sensors to recognize a swipe gesture (horizontal) which moves the item to reveal an action? If the horizontal swipe gesture is active it would have to disable the original `PointerSensor` for the vertical list sorting.

<img width="284" alt="image" src="https://user-images.githubusercontent.com/3497076/157162414-520725a3-bdbd-42d8-b991-e2f408e69610.png">

**Comment by clauderic** [comment]
Hey @Sorgrum, at the moment this is out of the scope of what @dnd-kit aims to facilitate. This isn't to say this couldn't one day be supported, but the library is primarily focused on empowering use-cases that require the use of both draggable elements and droppable regions.

Having that said, @dnd-kit shouldn't get in the way of you being able to achieve this use-case. You should be able to attach additional pointer listeners to the items to handle swipe gestures.

**Comment by Sorgrum** [comment]
Hi @clauderic, 

Thanks for the reply and the wonderful lib. 

For anyone investigating something like this in the future, after trying a bunch of different methods, I found `framer-motion` supports this use-case very well. 

When rendering a list for `dnd-kit`, the child can be a motion.div that supports dragging. 

```typescript
const x = useMotionValue(0);

return (
  <motion.div
    drag="x"
    style={{ x }}
    dragConstraints={{ left: 0, right: 0 }}
    onDragEnd={handleDragEnd}
  >
    {children} 
  </motion.div>
)
```

Since the `dnd-kit` sensor has a delay before activating, the user can drag side-to-side so the sensor will never activate, and `framer-motion` can handle the side-to-side dragging instead.
``` typescript
useSensor(PointerSensor, {
  activationConstraint: {
    delay: 250,
    tolerance: 5,
  },
}),
```
