### ISSUE TITLE
would be nice to export the attributes type so they could be easily typed in props

### ISSUE THREAD

**Issue by lukesmurray** [clauderic/dnd-kit#645]
Sometimes we want to pass listeners and attributes into components so they can be used in drag handles. ([see flexibility](https://docs.dndkit.com/api-documentation/draggable/usedraggable#flexibility))

https://github.com/clauderic/dnd-kit/blob/6f307806c09d4a1147073bf04f7cd15b7de721fc/packages/core/src/hooks/useDraggable.ts#L18-L22

Listeners has an exposed type `DraggableSyntheticListeners` but attributes does not.
It would be nice if attributes was exposed as a public type.

**Comment by clauderic** [comment]
Would gladly accept a PR to that effect 👍
