### ISSUE TITLE
fixed index dividers in variable size sortable list

### ISSUE THREAD

**Issue by michaelplotke-goodtime** [clauderic/dnd-kit#655]
I am trying to, as I say in the title, have fixed index dividers in variable size sortable list. While the index of the divider must remain fixed, the position of the divider should shift to accommodate the mid-rearranging spacing changes or items of various sizes.

Here is an example. https://stackblitz.com/edit/react-ts-zykekg?file=index.tsx

The above is just a minimal case to illustrate the challenge. I've tried various hacks to get this working with as yet no success.

**Comment by clauderic** [comment]
The most logical way I can think of to do this would probably be to have each group implemented as a `SortableContext`, assuming I'm understanding what you're trying to achieve correctly.

Something like this... https://stackblitz.com/edit/react-ts-c6eysc?file=index.tsx
