### ISSUE TITLE
Drag with scrol view

### ISSUE THREAD

**Issue by centotaure** [clauderic/dnd-kit#664]
Hello,

I have a problem with your wonderfull lib.

I have 2 columns .

The first is a scrol div with many dragable item

and the second is the droppable container

when i drag an element on top of with scrol view no problem 

But When i drag an element of the bottom on my scrol view ( i scrol so )

when i get inside my droppable container the position of dragable keep the Y of the scrool view

How can i fix this ?

Thx for your reply 

Have a nice day

**Comment by clauderic** [comment]
Please provide a CodeSandbox replicating the issue you are facing if you want me to be able to assist you

**Comment by flashtheman** [comment]
I assume you're not on the latest version of the library.

**Comment by centotaure** [comment]
All right your the boss dud.

I just update and its work :)

great job 

enjoy your weekend
