### ISSUE TITLE
disabled dragging not working correctly on touch screen?

### ISSUE THREAD

**Issue by thijsdegaaij** [clauderic/dnd-kit#666]
'To unable draggable' not possible on touch screen?

When I set myDragElement.disabled = true, it works on screen. But on touch screen text turns grey, but element is still draggable!

Can anyone help?

<img width="335" alt="Screenshot 2022-03-21 at 13 00 54" src="https://user-images.githubusercontent.com/27547868/159257006-90b86a9c-02f2-40f0-805d-1e90df2157fa.png">

**Comment by clauderic** [comment]
Pass the `disabled` argument to the `useDraggable` hook:

```diff
const {attributes, listeners, setNodeRef, transform} = useDraggable({
    id: 'draggable',
+   disabled: true,
})
