### ISSUE TITLE
Items repositioning does not happen unless the sortable was dragged at least once

### ISSUE THREAD

**Issue by 0xF013** [clauderic/dnd-kit#669]
I am trying to make it so that a list animates the items to a new position on a button click. It seems that no animation happens unless one of the items in the list has been dragged already. 

Codesandbox: https://codesandbox.io/s/dnd-kit-sortable-forked-443to2?file=/src/SortableItem.jsx
The button handler simply moves the current item to position 3.

https://user-images.githubusercontent.com/1038822/159349765-20f8909f-6ff6-42f7-8d3b-c8cf11f278a3.mov

**Comment by clauderic** [comment]
Hey @0xF013, the issue you're seeing is happening because the default measuring strategy for droppable nodes is to only measure while dragging. You can update the measuring strategy to `MeasuringStrategy.Always` to force @dnd-kit to measure elements before, while and after dragging.

```ts
import {MeasuringStrategy} from '@dnd-kit/core';

const measuringConfig = {
  droppable: {
    strategy: MeasuringStrategy.Always,
  },
};

<DndContext measuring={measuringConfig} />
```
