### ISSUE TITLE
Memoize attributes returned from useDraggable unless they change

### ISSUE THREAD

**Issue by Pustelto** [clauderic/dnd-kit#67]
Hi @clauderic, thanks for great DnD Library.

I'm trying to create sortable nested tree with it. I'm almost done, but since we have quite a lot of items in the tree and so far I couldn't found virtualization library that would support nested structures. So I'm trying to get as much perf as possible through other means (mainly useMemo hooks and React.memo). However I have noticed that `attributes` object returned from `useDraggable` is always a new object, even when the data don't change. It would be greate to memoize this in order to make use of memoization on the items.

Sorry if the description is a little short. I may have a look into this and create PR if necessary.

**Comment by clauderic** [comment]
Should be a fairly straightforward change, feel free to submit a PR for this
