### ISSUE TITLE
Flicker after re-dragging an item

### ISSUE THREAD

**Issue by camachomarco** [clauderic/dnd-kit#671]
Hello @clauderic ,

Thanks for this very useful library!

Here's an issue I haven't been able to solve. I am using Next.

Whenever I re-drag an item, the item on its side flickers as if I had move the dragged item over it. 

I use the mouse sensor and I noticed that if I delete its activationConstraint (distance), and just use "useSensor(MouseSensor)", the issue is no more. However, if I do that, I can't click on each item which are all links (next/link) that all lead to a different page.

`  const sensors = useSensors(
    useSensor(MouseSensor, {
      activationConstraint: {
        distance: 2,
      },
    })
  );`

I have also tried removing/changing all the props of DndContext and SortableContext, but to no avail.

Does anyone have any ideas?

Thanks! :)

https://user-images.githubusercontent.com/88408622/159357336-f0ab940e-acdf-413f-986a-e3aea62ad264.mp4

**Comment by clauderic** [comment]
Please provide a CodeSandbox replicating the issue you are facing if you want me to be able to assist you.

**Comment by camachomarco** [comment]
Hey @clauderic  for sure here's a CodeSandbox. It is not behaving exactly how it was behaving inside my repo (doesnt have transitions), but I'm trying to see why that is. I will keep you updated once it is at back to its initial behavior.

Cheers.

https://codesandbox.io/s/gallant-elgamal-wbpody

**Comment by camachomarco** [comment]
Here's a more relevant CodeSandbox which uses Next just like I did in my own project. It seems like everything works but I cannot see any transition from the sortable items for some reason...

https://codesandbox.io/s/gallant-wozniak-5lscly?file=/pages/_app.js

* You can see the issue if you go to the path "/dashboard/library"

**Comment by clauderic** [comment]
Hey @camachomarco, I'm not really able to use either of those sandboxes, but I was able to look at the code. I believe the issue you're seeing is possibly related to the fact that you are using numbers instead of strings for the `id` properties of the `items`.

```diff
  const [folders, setFolders] = useState([
    {
-    id: 1, 
+    id: '1',
      name: "Random Name" 
    },
    { 
-      id: 2, 
+      id: '2', 
      name: "this is another item!!!" 
    },
  ]);
```

Feel free to re-open this issue if that wasn't the problem.
