### ISSUE TITLE
Get The coordinate point on intersection of draggable and  droppable

### ISSUE THREAD

**Issue by centotaure** [clauderic/dnd-kit#673]
Hello,

how can i get the coordinate point for intersect between draggable and droppable ?

I use the lastest version and i thinks it's with the rect properties.

i try but i failed.

Thx if you can solve my answer ?

Have a nice day

**Comment by clauderic** [comment]
Why do you need this?

**Comment by centotaure** [comment]
If someone ask the same question :)


in the drag end method of dndcontext

let newX = (positionElementDraggable.x + over.rect.width + delta.x) - over.rect.rect.left;
let newY = (positionElementDraggable.y + delta.y) - over.rect.rect.top;

positionElementDraggable is the position of the dragable element on dragstart, 
i just get x, y of node = node.current.getBoundingClientRect()

Anyway thanks more for this kit :)
