### ISSUE TITLE
drop animation animates to the wrong rect

### ISSUE THREAD

**Issue by lukesmurray** [clauderic/dnd-kit#681]
https://github.com/clauderic/dnd-kit/blob/dbf95b8d3ad8d4c5bb1740257d6cd44fd6e879fd/packages/core/src/components/DragOverlay/hooks/useDropAnimation.ts#L62

The drop animation should use `measuring?.draggable?.measure ?? getTransformAgnosticClientRect` from the `DnDContext`.

I'm implementing a virtualized list and positioning elements using transform, so the position of the rectangles is not transform agnostic. When I pass in `measure` most things seem to be working but on drop the elements animate to the wrong place. I believe its because of the line I linked but I may be wrong

**Comment by KatFishSnake** [comment]
@lukesmurray can you make a codepen to demonstrate the issue?, and possibly a PR to see it being fixed 🙏

**Comment by lukesmurray** [comment]
@KatFishSnake sure here is a demonstration

https://codesandbox.io/s/incorrect-drop-animation-example-iufb0s?file=/src/App.tsx

![incorrect-drag-example](https://user-images.githubusercontent.com/34020210/160906658-03831658-3c0f-49ec-bd83-96c1834e0e3b.gif)

Before I submit a PR could I get confirmation from someone that it would be a welcome change?

**Comment by lukesmurray** [comment]
the code in the sandbox is from a larger experiment I was doing so it isn't a minimal reproduction but the fundamental problem seems fairly obviously. basically the drag overlay is animating to the `transformAgnostic` position of the element, but my elements are positioned using their transform. 

The transform agnostic position of the row is at the top because all of the rows are given position absolute so without the transform they would by default render at the very top of the screen.

Hope that explains everything!

**Comment by clauderic** [comment]
Hey @lukesmurray, I'm currently working on refactoring the internals of the drop animation and will get this fixed (essentially making sure that the drop animation uses `measuring?.dragOverlay?.measure` and `measuring?.draggable?.measure`)

**Comment by th3fallen** [comment]
Awesome to hear! i'm running into this as well since the drop takes a second for the data to catch up after (promises) so that'll be nice
