### ISSUE TITLE
Are there plans to support touch events?

### ISSUE THREAD

**Issue by tsaockham** [clauderic/dnd-kit#69]
Hello,

This library seems very useful.  Are there any plans to support touch events in the future?  I think that would really help the adoption if you were able to support both HTML5 and touch seamlessly.

Cool library, looking forward to playing around with it.

Thanks,
-Todd

**Comment by clauderic** [comment]
This is already supported, refer to the [Sensor](https://docs.dndkit.com/api-documentation/sensors) and [TouchSensor](https://docs.dndkit.com/api-documentation/sensors/touch) docs.
