### ISSUE TITLE
Expose `getTransformAgnosticClientRect` from utilities in `index.ts` in the core package

### ISSUE THREAD

**Issue by mayakoneval** [clauderic/dnd-kit#692]
`getTransformAgnosticClientRect` is used in the defaultConfig for measuring. For my use case, on `DndContext` I want to pass a custom `measuring` prop for `droppable`. The only change I want to make is from the default is to measure the parent element, instead of the element that is being measured. It would be super helpful to have this function available to use instead of copy & pasting this function & the functions it calls. 

Thanks!

**Comment by clauderic** [comment]
Hey @mayakoneval,

The `getTransformAgnosticClientRect` function calls `getClientRect` with a pre-populated options argument.

While `getTransformAgnosticClientRect` isn't exported, `getClientRect` is exported which feels sufficient. For the use-case you're describing, would something like this work?

```ts
import {getClientRect} from '@dnd-kit/core';

function customGetClientRect(element: HTMLElement) {
  return getClientRect(element.parentElement, {
    ignoreTransform: true,
  });
}
```

**Comment by mayakoneval** [comment]
Hi yes! Thank you thank you
