### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by rsdrsd** [clauderic/dnd-kit#693]

**Comment by clauderic** [comment]
Have you tried updating the order of the items in `onDragOver`?

**Comment by rsdrsd** [comment]
Sorry for my late reply. I was on a holiday. I'd forgotten to mention the example I was talking about. I'ts the Sortable -> Grid -> Swappable example.

https://5fc05e08a4a65d0021ae0bf2-ipdskkittb.chromatic.com/?path=/story/presets-sortable-grid--swappable
