### ISSUE TITLE
Sortable: preventing onclick of child. Sorting down works, up doesn't

### ISSUE THREAD

**Issue by JuAn-Kang** [clauderic/dnd-kit#697]
https://codesandbox.io/s/dnd-kit-prevent-click-from-firing-preview-forked-17bw0d?file=/src/Card.jsx

As you can see in the example, it seems like there is no problem while sorting down but I see the alert in the child's onClick when sorting up. Can this be addressed, or is there an existing workaround for this? Thank you.

**Comment by clauderic** [comment]
Add a `distance` or `delay` activation constraint if you need to handle click events on the draggable items. 

Refer to https://docs.dndkit.com/api-documentation/sensors/pointer#activation-constraints

**Comment by JuAn-Kang** [comment]
I already have tried either methods. What I hope is available is that dragging & letting go would click through the react-dom link that I do not wish to click unless it's a click instead of a drag. seems like DragOverlay sort of addresses the issue, although not 100%.

**Comment by clauderic** [comment]
You're using a really old version of @dnd-kit packages in your CodeSandbox, the issue has been fixed for a while in more recent packages https://codesandbox.io/s/dnd-kit-prevent-click-from-firing-preview-forked-6fsxuv

**Comment by jeffal** [comment]
I am experiencing this exact issue. The link does not get clicked when sorting down, but does get clicked when sorting up!

See: https://codesandbox.io/s/dnd-kit-prevent-click-from-firing-preview-forked-h0wihz

![Dec-06-2022 16-08-00](https://user-images.githubusercontent.com/2325629/206034043-b4ddd7fb-452f-44e4-8777-72783ff9108d.gif)

Any ideas?

**Comment by jeffal** [comment]
Looks like I am able to workaround any links being clicked using a combination of `pointerEvents: none` and an `activationConstraint`, but this behavior does seem odd.
