### ISSUE TITLE
cannot drag subsequent instances of one item from one droppable to another

### ISSUE THREAD

**Issue by j-sup** [clauderic/dnd-kit#698]
sandbox: https://codesandbox.io/s/dnd-sample-yhdmeb?file=/src/App.tsx

I have multiple droppables. one of them is a kiosk; where if I drag an item from it to another droppable, a copy is made and inserted into the target droppable; the originally dragged item remains in this kiosk.

the problem: when I try to drag the same item again, the context freezes, but the react app is still running

repro steps:
- drag "Image" from Kiosk to Container A
- expect "Image" to be inserted into Container A and Kiosk to keep its own "Image"
- attempt to drag "Image" from Kiosk again
- expect "Image" nor any other draggable in Kiosk or other Containers to move

**Comment by clauderic** [comment]
It looks to me like when you clone `Image` from the kiosk into one of the containers, you're not creating a new unique identifier for the newly added cloned item.

This causes a collision between two items in @dnd-kit that have the same unique identifier, which is causing the issues you're seeing.

You have to treat the `kiosk` as a vending machine for new items, where each time you drop over a new container, you generate a new unique id on the fly.

For example, if you use the `uuid` library:

```js
import {v4 as uuid} from 'uuid';

const newUniqueIdentifier = `image-${uuid()}`;
```

**Comment by j-sup** [comment]
indeed, you can see this project uses the UUID library for that purpose.

we are creating and assigning a newUUID to the object; see line 65 of [dragEndHandler()](https://codesandbox.io/s/dnd-sample-yhdmeb?file=/src/lib/drag-end-handler.ts)

I also made sure that the id of the list of SortableItem should be the id property of each item; see line 275 of [WidgetContainer](https://codesandbox.io/s/dnd-sample-yhdmeb?file=/src/components/WidgetContainer.tsx)

**Comment by j-sup** [comment]
moreover, I updated the item style to display the unique UUID, which proves that it's generated:
![image](https://user-images.githubusercontent.com/86330208/163396700-599dc85d-a846-42a2-afb5-c96a5a31a7ba.png)

can you please take another look?

**Comment by paulisloud** [comment]
I'm experiencing something similar here, and can verify that the first comment from @clauderic did not address.
