### ISSUE TITLE
Using object array instead of a string array for id?

### ISSUE THREAD

**Issue by 10000multiplier** [clauderic/dnd-kit#70]
My sortable item has several props exposed such as title, category and image.

So instead of

```
[items, setItems] = useState(['1', '2', '3']);
```
My sortable item looks like:

```
[items, setItems] = useState([
{id: '1', title: 'x', category: 'y'},
{id: '2', title: 'z', category: 'w'}
...])
```

I am not sure how I can make this work.

Any help would be appreciated!

**Comment by TheUrbina20** [comment]
@10000multiplier 
In your `SortableContext` you can have something this:

```
<SortableContext
  items={items.map((item) => item.id)}
  strategy={verticalListSortingStrategy}
>
{/*  */}
</SortableContext>
```

And for your sortable elements:
`{items.map((item) => <SortableElement key={item.id} id={item.id} /> )}`

**Comment by clauderic** [comment]
As mentioned by @TheUrbina20, the solution is to map the items to their corresponding unique identifiers.

You may want to memoize to avoid needless re-renders of the SortableContext:

```js
const [items, setItems] = useState([
  {id: '1', title: 'x', category: 'y'},
  {id: '2', title: 'z', category: 'w'},
  ...
])
const sortedItemIds = useMemo(() => items.map((item) => item.id), [items]);

<SortableContext
  items={sortedItemIds}
>
  {...}
</SortableContext>
```

**Comment by 10000multiplier** [comment]
Awesome.

Using 'sortedItemIds', how would you reconfigure the handleDragEnd function?

`function handleDragEnd(event) {
    const {active, over} = event;
    
    if (active.id !== over.id) {
      setItems((items) => {
        const oldIndex = items.indexOf(active.id);
        const newIndex = items.indexOf(over.id);
        
        return arrayMove(items, oldIndex, newIndex);
      });
    }
  }`
 
 Simply replacing 'items' by 'items.id' does not seem to work :(

**Comment by 10000multiplier** [comment]
> Awesome.
> 
> Using 'sortedItemIds', how would you reconfigure the handleDragEnd function?
> 
> ```
> 
> function handleDragEnd(event) {
>     const {active, over} = event;
>     
>     if (active.id !== over.id) {
>       setItems((items) => {
>         const oldIndex = items.indexOf(active.id);
>         const newIndex = items.indexOf(over.id);
>         
>         return arrayMove(items, oldIndex, newIndex);
>       });
>     }
>   }
> ```
> 
> Replacing 'items' by 'items.id' does not seem to work.

fixed it with following code:

```
const oldIndex = items.map((item) => item.id).indexOf(active.id);
            const newIndex = items.map((item) => item.id).indexOf(over.id);
```

**Comment by 10000multiplier** [comment]
How would you go about setting up the DragOverlay?

```
<DragOverlay>
                    {activeId ? <Item
                                title={}
                                category={}
                                image={}
                                id={activeId}
                            /> : null}
                </DragOverlay>
```

Any help would be appreciated.

**Comment by 10000multiplier** [comment]
Found the solution that worked!

`const index = items.map((item) => item.id).indexOf(activeId);`

```
<DragOverlay>
      {activeId ? <Item
                  title={items.map((item) => item.title)[index]}
                  category={items.map((item) => item.category)[index]}
                  image={items.map((item) => item.image)[index]}
                  id={activeId}
              /> : null}
</DragOverlay>
