### ISSUE TITLE
SSR issue: server side state

### ISSUE THREAD

**Issue by chris-kruining** [clauderic/dnd-kit#701]
I am encountering a small issue with your lib when used with Remix

https://github.com/clauderic/dnd-kit/blob/56d11cceec27fe5a03dc74a802b4f4be3e59b2f6/packages/utilities/src/hooks/useUniqueId.ts#L3 this variable "survives" refreshes on the server, which results in the ids just keeping counting up. Whilst the client always starts from scratch. This results in the following error from react-dom: `Warning: Prop `aria-describedby` did not match. Server: "DndDescribedBy-13" Client: "DndDescribedBy-0"`

this can be solved by not using any level of global variable (neither in modules nor app-wide).
I don't really know how to patch this and therefor I have no PR for you, obviously you do need to store the ids state, just not as a global.

**Comment by daniel-a-marshall** [comment]
I was able to get this to work by switching from using a global variable to using a ref inside of the hook. I tested this on my end and it is working but not sure if it would cause any other issues. I can submit a PR if this seems like a reasonable solution.

```tsx
import {useMemo, useRef} from 'react';

export function useUniqueId(prefix: string, value?: string) {
  const ids = useRef<Record<string, number>>({})   
  
  return useMemo(() => {
    if (value) {
      return value;
    }

    const id = ids.current[prefix] == null ? 0 : ids.current[prefix] + 1;
    ids.current[prefix] = id;

    return `${prefix}-${id}`;
  }, [prefix, value]);
}

```

**Comment by tconroy** [comment]
Also running into this issue. The solution posted by @daniel-a-marshall seems like a solid one. Any possibility of getting this merged into core, @clauderic?

**Comment by JSRossiter** [comment]
Passing an id prop to the DndContext as suggested in this previous issue appears to have resolved this same issue for me.
https://github.com/clauderic/dnd-kit/issues/285#issuecomment-853974128
