### ISSUE TITLE
cannot drag subsequent instances of one item from one droppable to another (redux)

### ISSUE THREAD

**Issue by j-sup** [clauderic/dnd-kit#704]
sandbox: https://codesandbox.io/s/dnd-sample-yhdmeb?file=/src/App.tsx

please refer [issue 698](https://github.com/clauderic/dnd-kit/issues/698) for the original post

the issue was closed by @clauderic with this response:

> It looks to me like when you clone Image from the kiosk into one of the containers, you're not creating a new unique identifier for the newly added cloned item.
> 
> This causes a collision between two items in https://github.com/dnd-kit that have the same unique identifier, which is causing the issues you're seeing.
> 
> You have to treat the kiosk as a vending machine for new items, where each time you drop over a new container, you generate a new unique id on the fly for the newly inserted item.

but this is already accounted for per my reply:

> indeed, you can see this project uses the UUID library for that purpose.
> 
> we are creating and assigning a newUUID to the object; see line 65 of [dragEndHandler()](https://codesandbox.io/s/dnd-sample-yhdmeb?file=/src/lib/drag-end-handler.ts)
> 
> I also made sure that the id of the list of SortableItem should be the id property of each item; see line 275 of [WidgetContainer](https://codesandbox.io/s/dnd-sample-yhdmeb?file=/src/components/WidgetContainer.tsx)

**Comment by j-sup** [comment]
hi @clauderic I cleaned up code, and along the way, unfortunately, did not find an answer.

here's the updated sandbox: https://codesandbox.io/s/dnd-sample-redux-uzll4i

we assign the UUID in lines 35-54 of drag-end-handler.tsx

**Comment by clauderic** [comment]
Hey @j-sup, you have to assign the new UUID in `onDragOver`, not `onDragEnd`, otherwise you have two items with the same id simultaneously rendered:

<img width="717" alt="Screen Shot 2022-05-05 at 6 30 11 PM" src="https://user-images.githubusercontent.com/1416436/167035612-1465c75c-2b77-40b7-8551-8ee9bdbea48b.png">

Refer to the above screenshots, there are two instances of `headline` rendered simultaneously
