### ISSUE TITLE
IE11 Permanent freeze

### ISSUE THREAD

**Issue by krau5** [clauderic/dnd-kit#705]
In IE11 `useDropAnimation` is triggered and I got the following error:
```
__proto__: [object Error] { ... },
description: "Object doesn't support property or method 'animate'",
message: "Object doesn't support property or method 'animate'",
name: "TypeError"
```
Is is possible to fix? Polyfill?

**Comment by clauderic** [comment]
Either include the [Web Animations API polyfill](https://github.com/web-animations/web-animations-js) or disable the drop animation on IE 11:

```tsx
<DragOverlay dropAnimation={null}>
```
