### ISSUE TITLE
Console error when unmounting a SortableContext

### ISSUE THREAD

**Issue by kiselyou** [clauderic/dnd-kit#709]
Hi guys! 
Some weeks ago we discuss problem "[Console error when unmounting a DndContext](https://github.com/clauderic/dnd-kit/issues/637)" #637 and solution will be found. Nevertheless i got the same problem in SortableContext. 

Steps to play:
1. start drag item
2. end drag item
3. when animation is playing return back - destroy tree component

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`

**Comment by yankovichv** [comment]
+1

**Comment by kiselyou** [comment]
[Look at video to reproduce](https://monosnap.com/file/AVYoHULzkZVJcrXchrFt1BlVV8mfRH)
If destroy tree component before back animation is completed you will get console error.

**Comment by kiselyou** [comment]
The problem is gone.
My current version:
```
    "@dnd-kit/core": "^6.0.3",
    "@dnd-kit/sortable": "^7.0.0",
    "@dnd-kit/utilities": "^3.2.0",
```
Thanks!
