### ISSUE TITLE
Module parse failed: Unexpected token. You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by pantelispanayiotou** [clauderic/dnd-kit#715]
Just installed the latest version of dnd kit amd i am receiving the error:

Module parse failed: Unexpected token. You may need an appropriate loader to handle this file type, @dnd-kit/core/dist/core.cjs.development.js

I am using the package on electronjs with node v.12.20.0 and typescript 4.0.5. Is there a chance that dnd kit is using newer versions that are not backward compatible with my current stack? 

```
ERROR in ../core/node_modules/@dnd-kit/core/dist/core.esm.js
Module parse failed: Unexpected token (142:15)
You may need an appropriate loader to handle this file type.
|   switch (action.type) {
|     case Action.DragStart:
|       return { ...state,
|         draggable: { ...state.draggable,
|           initialCoordinates: action.initialCoordinates,

ERROR in node_modules/@dnd-kit/utilities/dist/utilities.esm.js
Module parse failed: Unexpected token (166:9)
You may need an appropriate loader to handle this file type.
| 
|       return accumulator;
|     }, { ...object
|     });
|   };

ERROR in .node_modules/@dnd-kit/sortable/dist/sortable.esm.js
Module parse failed: Unexpected token (72:6)
You may need an appropriate loader to handle this file type.
|       x: activeIndex < overIndex ? newIndexRect.left + newIndexRect.width - (activeNodeRect.left + activeNodeRect.width) : newIndexRect.left - activeNodeRect.left,
|       y: 0,
|       ...defaultScale
|     };
|   }
```

Maybe similar to #506

**Comment by clauderic** [comment]
Seems like your project is not set up to support the spread syntax (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)

**Comment by FarzadKarkhani** [comment]
I have the same issue, my setup supports the spread syntax but not for inside of /node_modules/

**Comment by pantelispanayiotou** [comment]
@clauderic i am using other packages as well that use the spread operator without any problems. Only on dndkit it throws an error. Please take the time to have a look before closing an issue since there other people as well that have the same problem.
