### ISSUE TITLE
Item loses animation when dragging across containers

### ISSUE THREAD

**Issue by JeremyLion** [clauderic/dnd-kit#718]
For some reason my items are losing the animation of dragging when trying to drag the items across the container. I am not sure whats causing it. The state updates just fine but it kinda just disappears and doesnt even snap when dragging into another container.

Here is a demo of the problem.
https://codesandbox.io/s/sparkling-dream-uvtq38?file=/src/App.js

**Comment by DoctorRyner** [comment]
I'm having the same problem; the draggable item simply snaps out of its initial container

**Comment by DoctorRyner** [comment]
This behaviour changes when we use a DragOverlay

**Comment by DoctorRyner** [comment]
By commenting out onDrag* in this https://codesandbox.io/s/lknfe?file=/src/app.js:1670-1681 example, you will see how to fix the issue. It seems that you need to properly handle them handler

**Comment by clauderic** [comment]
You should use the `<DragOverlay>` component for use-cases that require dragging between multiple containers

https://docs.dndkit.com/api-documentation/draggable/drag-overlay

**Comment by DoctorRyner** [comment]
@clauderic would be neat if it could be documented in some way, currently it's confusing
