### ISSUE TITLE
Containers transitions when an item is added or removed?

### ISSUE THREAD

**Issue by Arkellys** [clauderic/dnd-kit#719]
Hello, thank you for this great library!

I was wondering if it was possible to get size transitions on containers when an item is added or removed?
Currently, there is no transition on the examples from storybook:

![pkKGuUiq57](https://user-images.githubusercontent.com/32762018/166650858-42d5c622-fcf0-4219-8a4c-66f726d4c958.gif)

**Comment by sbesh91** [comment]
Previously, I've used framer-motion's layout animation to do this.  https://www.framer.com/docs/component/##layout-animation

**Comment by clauderic** [comment]
This is beyond the scope of what @dnd-kit aims to facilitate out of the box, but as mentioned by @sbesh91, you could use a library like framer-motion to do this, or write a component that animates when its computed height changes using ResizeObserver.
