### ISSUE TITLE
Pinning a particular element is not possible as far as I see in the docs 

### ISSUE THREAD

**Issue by jackcrack3110** [clauderic/dnd-kit#721]
Basically I am migrating from **react-beautiful-dnd** to **dnd-kit** which does not have customization to pin a particular HTML element and the others we can drag and drop.

**Comment by jackcrack3110** [comment]
![image](https://user-images.githubusercontent.com/42385988/166867581-089e8bdc-d924-4d40-a984-4cc5a4e1f977.png)
Like in the above image I the Drag Me Item 2 can't go above Pinned Item 1.

**Comment by jackcrack3110** [comment]
![image](https://user-images.githubusercontent.com/42385988/166867700-f1946f6a-a929-47c6-b0c1-2aeba556ed2a.png)
With **dnd-kit** we have a disabled example like above but we still can drag 2 above 1 despite 1 being disabled.

**Comment by clauderic** [comment]
The use case you're describing is one where there are multiple sortable lists, not a single one.

Refer to this discussion https://github.com/clauderic/dnd-kit/issues/655#issuecomment-1067514152

**Comment by jackcrack3110** [comment]
No @clauderic  I am actually saying that I want the Pinned Item 1 in the first image to remain fixed and it should not rearrange itself according to the other items if I drag them above it. It should always be at the 1st position.

**Comment by nzkks** [comment]
hey @jackcrack3110, create the item style wise similar to any other sortable item but add it outside (above) of the DndContext.

**Comment by RoyRao2333** [comment]
> ![image](https://user-images.githubusercontent.com/42385988/166867581-089e8bdc-d924-4d40-a984-4cc5a4e1f977.png)

@jackcrack3110 

Can you tell me how did you achieve this using `react-beautiful-dnd`? `dnd-kit` is a great framework but I don't want to limit myself to it if `react-beautiful-dnd` can do the thing. Thanks!
