### ISSUE TITLE
Pinning a particular element is not possible 

### ISSUE THREAD

**Issue by jackcrack3110** [clauderic/dnd-kit#723]
https://codesandbox.io/s/amazing-boyd-uwg2b2?file=/src/dnd-kit.js

In the above sandbox, I want to pin the card having **clauderic** text, I don't want the below cards having **Ayush** and **Elon** to go above that in any way. Please help me out with this.

**Comment by jackcrack3110** [comment]
https://stackblitz.com/edit/react-ts-xbakkv?file=index.tsx
So I pinned it like this but do you think its the correct like is there any prop like type='pinned' in dnd-kit like it was there in react-beautiful-dnd

**Comment by clauderic** [comment]
I don't believe the concept of `pinning` should be part of @dnd-kit. It's a loaded term that doesn't actually correlate to any particular concept of drag and drop.

If you want an element to not be draggable or sortable, then don't connect it to `useDraggable` / `useSortable`.

If you want to be able to have "pinned" items you can drag above and below, then set up two separate sortable groups above and below the pinned items (similar to https://5fc05e08a4a65d0021ae0bf2-ipdskkittb.chromatic.com/?path=/story/presets-sortable-multiple-containers--vertical)

**Comment by jackcrack3110** [comment]
Thanks a lot for this.
