### ISSUE TITLE
Drop animation regression in @dnd-kit/core@6.0.0

### ISSUE THREAD

**Issue by igordanchenko** [clauderic/dnd-kit#758]
Hi there!

I just tried upgrading to the latest release and noticed a regression in drop animation. When the drop animation finishes, the drag overlay flashes where it was before the item was released, and this flicker is quite noticeable.

https://user-images.githubusercontent.com/64441155/169637661-000139b3-0470-4cf6-8f8f-d104531908e9.mov

Codesandbox: https://codesandbox.io/s/condescending-mayer-kqm4to?file=/src/App.tsx

Codesandbox using @dnd-kit/core@5.0.3 that doesn't experience this issue: https://codesandbox.io/s/github/igordanchenko/react-photo-album/tree/main/examples/sortable-gallery

**Comment by MrSauceman** [comment]
I am experiencing the exact same issue after updating to latest and had to roll back to the previous version to fix it.

**Comment by clauderic** [comment]
Will release a fix in a patch release soon, thanks for the detailed report.

**Comment by igordanchenko** [comment]
Thanks! Looks good now.
