### ISSUE TITLE
Experiencing jumping/flickering of draggable items

### ISSUE THREAD

**Issue by pantelispanayiotou** [clauderic/dnd-kit#761]
I am trying to recreate the basic draggable with multiple draggables. My example works as expected, however the draggables seem to jump/flickering when releasing. It doesn't seem to happen consistently so i am not able to explain the reason it happens. Here's a codesandbox: https://codesandbox.io/s/bold-archimedes-g9prt0

**Comment by clauderic** [comment]
This is fixed by https://github.com/clauderic/dnd-kit/pull/750

Upgrade to `@dnd-kit/core^6.0.1`:

https://codesandbox.io/s/async-pine-4kzj01
