### ISSUE TITLE
Fake drag clientRect to match a custom DragOverlay

### ISSUE THREAD

**Issue by Jim-salies** [clauderic/dnd-kit#765]
First of all, thank you for this amazing Dnd library. Through my search I have been able to customize almost anything I wanted in my project.

I am currently searching a way to fake the clientRect of my draggable component. 

I would like to create something like a custom modifier which instead of modifing coordinates, would alter clientRect.

The aim would be to make Dnd interactions match with a custom preview through DragOverlay.

Would it be possible to do so?

**Comment by Jim-salies** [comment]
found a suitable solution for myself :

- added custom Partial<ClientRect> in data in useDraggable and useDroppable
- created a custom collision function passed to DnDContext
- customized collisionRect inside the custom collision function

I don't know if it is really clean but this way i can totally fake drag and droppable rects

**Comment by BrentFarese** [comment]
@clauderic just came across this issue as we were having problems using a custom preview and the collision detection working correctly.  I feel like this should be documented, no?  It's a relatively easy implementation to customize `rectIntersection` as an example, but developers don't really know to look for it.  Below is my implementation.

```
export const detectDragPreviewCollisions: CollisionDetection = args => {
  const dragEl = document.getElementById(domElIdCreators.fieldOverlayEl());
  if (!dragEl) return rectIntersection(args);

  const dragElPreviewRect = dragEl.getBoundingClientRect();
  return rectIntersection({ ...args, collisionRect: dragElPreviewRect });
};
```
