### ISSUE TITLE
Glitchy animation when dropping item

### ISSUE THREAD

**Issue by MTxx87** [clauderic/dnd-kit#767]
Hi, I am experiencing a weird animation when sorting a list of elements.
I cannot provide the exact codebase, but I have built it on top of the story `presets > sortable > multiple containers > many items`.

Here below you can see a video of the problem.
Notice how the`<DragOverlay />` falls correctly into place, while the remaining elements shifts up in a weird way.

https://user-images.githubusercontent.com/12138301/170713994-dcf7dbbc-0bea-4e37-b107-e7b51cef15a2.mov

I have spent quite some time trying to track down the problem, but with no result so far.
Anybody has idea of what could be the cause?

Thanks.

**Comment by ibbeyo** [comment]
Hey, i was having the same issues since upgrading to the new versions recently. 
In the end i just reverted to the following previous versions:

@dnd-kit/core@5.0.3
@dnd-kit/modifiers@5.0.0
@dnd-kit/sortable@6.0.1
@dnd-kit/utilities@3.2.0

Hope this helps!

**Comment by clauderic** [comment]
Are you using a custom `animateLayoutChanges` function? If so, what does it look like?

**Comment by MTxx87** [comment]
Hi @clauderic, 
thanks for answering!
I am not in fact using animateLayoutChanges anywhere in my codebase.

I should specify that I am on the following version.
 ```
   "@dnd-kit/core": "^6.0.1",
    "@dnd-kit/modifiers": "^6.0.0",
    "@dnd-kit/sortable": "^7.0.0",
    "@dnd-kit/utilities": "^3.2.0",
```

**Comment by MTxx87** [comment]
Hey @ibbeyo,
I tried to downgrade as you suggested, but it didn't solve the problem.
The result was that I got another (possibly worst...) issue with the animation (see below).

https://user-images.githubusercontent.com/12138301/170729938-c8c11e0b-509f-4cbd-b5f5-969602f1e761.mov

**Comment by clauderic** [comment]
Hey @MTxx87, could you share the code somewhere I can look at? The best way for me to help you is if you can create a CodeSandbox that replicates the issue.

**Comment by ibbeyo** [comment]
> Are you using a custom `animateLayoutChanges` function? If so, what does it look like?

Didn't know about this function, it worked for me with most recent versions by setting `animateLayoutChanges` in `useSortable` to `false` .


Thank you!

**Comment by narendra315** [comment]
Had the same issue. Got it fixed by reverting package to old version.
Thanks @MTxx87 and Thank you @clauderic for the wonderful library.

**Comment by clauderic** [comment]
@ibbeyo you shouldn't have to specify a custom `animateLayoutChanges`; I'm happy that solved the issue for you, but I would love if you could provide a replication case for the original issue you were facing so I can help investigate why the default wasn't working in your case.

**Comment by MTxx87** [comment]
Hi @clauderic, 
here is a CodeSandbox with the original issue.
https://codesandbox.io/s/bold-golick-qlhsbs

When sorting the items you should experience the same problem as in the video in my first post.
I tried both on Safari and Chrome, and it worked.

**Comment by clauderic** [comment]
@MTxx87 the problem in your case is that you are not using a stable `key` property. You are passing the `index` as the `key` property to your list items, which causes them to unmount and re-mount when the order of the list changes.

Use the unique `id` property of your items instead as the `key`:

https://codesandbox.io/s/rough-cookies-53w0rj?file=/src/Items.tsx

You can read more about using stable keys here:

https://reactjs.org/docs/lists-and-keys.html#keys

**Comment by clauderic** [comment]
@ibbeyo feel free to re-open a new issue if you need further assistance.

**Comment by MTxx87** [comment]
@clauderic It worked when adding the proper `key`.
Thank you!

**Comment by natan-fernandes** [comment]
> > Are you using a custom `animateLayoutChanges` function? If so, what does it look like?
> 
> Didn't know about this function, it worked for me with most recent versions by setting `animateLayoutChanges` in `useSortable` to `false` .
> 
> Thank you!

Thanks, it worked flawlessly with `animateLayoutChanges: () => false`
