### ISSUE TITLE
Scrolling not working after updating library

### ISSUE THREAD

**Issue by lukasjengo** [clauderic/dnd-kit#768]
Hey Claudéric,

Thanks for a great library.

I have noticed that after updating dnd kit to a new version, sortable scrolling in overflowing containers no longer works and restrictToFirstScrollableAncestor no longer works.

Updated:
"@dnd-kit/core": "5.0.3"  to "@dnd-kit/core": "6.0.0"
"@dnd-kit/modifiers": "5.0.0"  to  "@dnd-kit/modifiers": "6.0.0"
"@dnd-kit/sortable": "^6.0.1"  to  "@dnd-kit/sortable": "7.0.0"

Before update:
Scrolling works and restrictToFirstScrollableAncestor modifier works
[Video link](https://user-images.githubusercontent.com/38685058/170721154-ae560fa5-b7cb-4fbb-aa3c-0ce53fe45aea.mp4)

After update:
Scrolling no longer works and restrictToFirstScrollableAncestor modifier no longer works
Notice that an additional viewport vertical scrollbar appears on the right side of the screen as well
[Video link](https://user-images.githubusercontent.com/38685058/170725674-e585670e-cf78-44ca-99d0-df42ada4bb5a.mp4)

Things I have tried already that did not fix the issue:
1. Removing modifiers
2. Going through changelog and implementing needed code migrations - only defaultDropAnimationSideEffects applies in my case.

Do you have any idea what might be causing this issue?

**Comment by clauderic** [comment]
Hey @lukasjengo, could you create a small reproduction of the issue in CodeSandbox? Alternatively, is the code somewhere I could look at?

**Comment by lukasjengo** [comment]
Hey @clauderic sure thing. 
Here you go https://codesandbox.io/s/blazing-glade-qpdmxi

**Comment by clauderic** [comment]
Thanks for providing a replication case 🙌  Found the issue, will be shipping a patch release soon.

**Comment by clauderic** [comment]
https://codesandbox.io/s/compassionate-pare-pvs07v?file=/package.json

**Comment by lukasjengo** [comment]
Thank you!
