### ISSUE TITLE
How to change animation when movement success

### ISSUE THREAD

**Issue by kobe651jp** [clauderic/dnd-kit#773]
I'm trying to move an element between containers. If unsuccessful, the overlay will return to its original position, displaying an animation that disappears towards the target container when successful.

But in my case the animation always back to original position.

If the overlay disappeared to target container when the movement is success will be more intuitive.

Is it possible to handle the animation? any advice or sample will be very appreciate .

my code as following.
```
  const dropAnimation = {
    duration: 250,
    easing: 'cubic-bezier(0.1, 0.7, 1.0, 0.1)',
    sideEffects: defaultDropAnimationSideEffects({
      styles: {
        active: {
          opacity: '0',
        },
      },
    }),
  };
```
```
  <DndContext
    sensors={sensors}
    collisionDetection={customCollisionDetectionAlgorithm}
    onDragEnd={handleDragEnd}
  >
    <div className={`${gridClass} original-scroll pr-1`}>
    ...
    </div>
    {createPortal(
      <DragOverlay adjustScale={false} dropAnimation={dropAnimation}>
       <div style={{
          height:'40px',
          border: '2px dashed #5c6ac477',
       }}/>
      </DragOverlay>,
      document.body
    )}
  </DndContext>
```

https://user-images.githubusercontent.com/44263972/170852547-d3f6667c-ac9f-45ed-86d9-2df232fef275.mp4

**Comment by skrisztianidealap** [comment]
indeed, this seems relevant with React v18

**Comment by blackrabbit944** [comment]
i have the same issue , finnally i found it cause by i have not set unique_key in each ITEM.
you could set a key with a unique_key in each Item, but it cannot be the index of the list, like id in database or something

**Comment by kobe651jp** [comment]
Do you show the code how it works?
It's not working in my case.
My code as follows
```
  const {
    attributes,
    isDragging,
    listeners,
    setNodeRef,
    transform,
    transition,
  } = sortable;

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
  };

  return (
    <div
      ref={setNodeRef}
      style={style}
      key={`setNodeRef:${item.xinfo_uuid}`}
      {...attributes}
      {...listeners}
    >
      <DrawCard
        key={`drawcard:${item.xinfo_uuid}`}
        xshar_uuid={xinfo_parent}
        parent={parent}
        item={item}
        onClickActive={onClickActive}
        onComplete={onComplete}
        innerHeight={innerHeight}
        className={isDragging ? 'border-dashed-info-50' : ''}
      />
    </div>
  );
```

**Comment by skrisztianidealap** [comment]
the unique id suggestion was on the spot, i made it work. thanks a lot!
