### ISSUE TITLE
Double scrollbar issue after updating library

### ISSUE THREAD

**Issue by lukasjengo** [clauderic/dnd-kit#780]
Hey @clauderic,

This is ralated to a previous issue described in https://github.com/clauderic/dnd-kit/issues/768.

Notice how in this particular case after library update there are two horizontal scrollbars on the right side of the screen.
[Video link](https://user-images.githubusercontent.com/38685058/170725674-e585670e-cf78-44ca-99d0-df42ada4bb5a.mp4)

See AppWrapper.js in codesandbox [here](https://codesandbox.io/s/blazing-glade-qpdmxi?file=/src/AppWrapper.js).
When app is wrapped with this kind of container, double scroll starts appearing.
It looks like adding relative style to a root div seems to solve the issue of the double overflow/scroll.

I think it might be related to a container that has DnDLiveRegion id, which used to be a sibling of "root" div in previous version and is now a nested child.

**Comment by clauderic** [comment]
Hey @lukasjengo, this issue is fixed by #772. Bump `@dnd-kit/accessibility` to `3.0.1` and the issue should be fixed.

**Comment by lukasjengo** [comment]
Bumping @dnd-kit/accessibility did fix it, thanks!
