### ISSUE TITLE
Compatibility with React 18?

### ISSUE THREAD

**Issue by Arkellys** [clauderic/dnd-kit#784]
I just updated my app to React 18 and now I get an error on `DndContext`:
> Uncaught Error: Maximum update depth exceeded.

It seems that I only have it on sortable multiple containers when I move items between containers. Sometimes it works and sometimes I get the error.

I don't have this problem with React 17, is `dnd-kit` compatible with React 18?

**Comment by clauderic** [comment]
@dnd-kit is definitely compatible with React 18. The error you're seeing can happen when you use a collision detection algorithm that is quickly switching between two different values because of layout shifts. In that situation, I would recommend using the `PointerWithin` collision detection algorithm to avoid these types of situations.

I'm going to be closing this issue because there is already a few duplicate issues like this one.

**Comment by Arkellys** [comment]
Hello, thank you for your answer.

Do you mean replacing the my custom collision detection algorithm with `pointerWithin`? Because when I try that, the collisions go completely wild and I still have the error. I'm using pretty much the same collision detection as the example provided on the multiple containers story, except that I have adapted it to my data.

**Comment by clauderic** [comment]
Assuming you copied the [custom collision detection strategy in the Multiple Containers example](https://github.com/clauderic/dnd-kit/blob/master/stories/2%20-%20Presets/Sortable/MultipleContainers.tsx#L208-L212):

```diff
const collisionDetectionStrategy: CollisionDetection = useCallback(
  (args) => {
    if (activeId && activeId in items) {
      return closestCenter({
        ...args,
        droppableContainers: args.droppableContainers.filter(
          (container) => container.id in items
        ),
      });
    }

    // Start by finding any intersecting droppable
-   const pointerIntersections = pointerWithin(args);
+   const intersections = args.pointerCoordinates ? pointerWithin(args) : rectIntersection(args);
-   const intersections =
-     pointerIntersections.length > 0
-       ? // If there are droppables intersecting with the pointer, return those
-         pointerIntersections
-       : rectIntersection(args);
    let overId = getFirstCollision(intersections, 'id');
```

**Comment by Arkellys** [comment]
Your fix seems to work so far! Thank you very much. 😄

**Comment by darren10201** [comment]
> Assuming you copied the [custom collision detection strategy in the Multiple Containers example](https://github.com/clauderic/dnd-kit/blob/master/stories/2%20-%20Presets/Sortable/MultipleContainers.tsx#L208-L212):
> 
> ```diff
> const collisionDetectionStrategy: CollisionDetection = useCallback(
>   (args) => {
>     if (activeId && activeId in items) {
>       return closestCenter({
>         ...args,
>         droppableContainers: args.droppableContainers.filter(
>           (container) => container.id in items
>         ),
>       });
>     }
> 
>     // Start by finding any intersecting droppable
> -   const pointerIntersections = pointerWithin(args);
> +   const intersections = args.pointerCoordinates ? pointerWithin(args) : rectIntersection(args);
> -   const intersections =
> -     pointerIntersections.length > 0
> -       ? // If there are droppables intersecting with the pointer, return those
> -         pointerIntersections
> -       : rectIntersection(args);
>     let overId = getFirstCollision(intersections, 'id');
> ```

its still happening unexpectedly. especially when its between two containers. I have one horizontal list on top and a row of vertical lists. the error occurs sometimes when a draggable is near the horizontal .
