### ISSUE TITLE
<DragOverlay>'s position is not calculated properly when the origin is a right-absolutely-positioned element, but works if it's on the left.

### ISSUE THREAD

**Issue by growthwp** [clauderic/dnd-kit#785]
(CSB that replicates the bug: https://codesandbox.io/s/lucid-cookies-chyjiq?file=/src/App.js:724-747)

`Item`'s `dragHandle` div is the drag handle that I use to move the entire `Item` to somewhere. Unfortunately, when this handle uses `position: absolute` and it is on the right, the `DragOverlay` component doesn't know how to calculate its initial x coordinates and it starts from the left no matter what. Changing `dragHandle`'s CSS to `left: 0` instead of `right: 0` fixes the issue (you can even add some padding to the `body` to see that the library's able to correctly calculate where the `DragOverlay` should start from. This also works even if you had padding inside the `Item` component, so, clearly, it takes a lot of small things into account), but in my case, this isn't possible. The `DragOverlay` should appear from the right. If you check the `event` object that comes from `useSensor`'s `onActivation`, you can see that the `clientX` value is correct, so are others that I assume the library doesn't care about.

I've read that there are some weird interactions with `flexbox` and the `DragOverlay` being inside them and a comment recommending to just elevate `DragOverlay` using a portal, so I did. Unfortunately, that doesn't help.

Any ideas as to why this is happening, if it's not a bug?

**Comment by clauderic** [comment]
The `<DragOverlay>` component is always positioned relative to the element that receives the `setNodeRef` function returned by `useDraggable`. 

In your case, that's the `div` element with the class name `styles.item`: 
<img width="1089" alt="Screen Shot 2022-06-05 at 10 53 06 AM" src="https://user-images.githubusercontent.com/1416436/172056628-070116ad-aea4-4b67-86fe-d7f996c5c874.png">

If you want the `<DragOverlay>` to be positioned relative to the drag handle, you should set the `ref` on the drag handle instead:

<img width="1104" alt="Screen Shot 2022-06-05 at 10 53 25 AM" src="https://user-images.githubusercontent.com/1416436/172056648-4328fbc3-98bd-4d4d-82ca-170eb0620342.png"

https://codesandbox.io/s/cocky-agnesi-4okkoe?file=/src/Item.js
