### ISSUE TITLE
Any Idea of a Sortable TreeView Feature in future ?

### ISSUE THREAD

**Issue by mkharibalaji** [clauderic/dnd-kit#80]
It's a Awesome library and i would like to know whether there is any idea on a Sortable Treeview using dnd kit ?

**Comment by clauderic** [comment]
Actively working on this here https://github.com/clauderic/dnd-kit/pull/76

Still heavily work in progress, have not had time to implement the logic on drop or max depth, but should give you a good idea of how to do it.

https://5fc05e08a4a65d0021ae0bf2-tzokynfxpb.chromatic.com/?path=/story/presets-tree-vertical--basic-setup
