### ISSUE TITLE
Draggable are not detecting onClick Event

### ISSUE THREAD

**Issue by MuhammadHamzaChippa** [clauderic/dnd-kit#800]
I am using useSortable and I want to listen to onClick event handler as well, but it is not detecting the click (double click as well). I am just doing as simple as that. How to detect the double click event on draggable ?
 ?
```
<div
                ref={setNodeRef}
                {...attributes}
                {...listeners}
                style={style}
                onClick={(e) => {
                    if (e.detail == 2) {
                        console.log("Double Clicked")
                    }
                }}
            >
                Card
</div>
```

**Comment by clauderic** [comment]
Add a `delay` or `distance` [activation constraint](https://docs.dndkit.com/api-documentation/sensors/pointer#activation-constraints), or use a drag handle.

**Comment by bayerlse** [comment]
> Add a `delay` or `distance` [activation constraint](https://docs.dndkit.com/api-documentation/sensors/pointer#activation-constraints), or use a drag handle.

Hey there!

How does the actual implemention looks like for using delay?

Thanks,

Sebi

**Comment by HamzaFractl** [comment]
@bayerlse you can add the delay bt adding activeConstraint in the Pointer Sensor. 
 ```
const sensors = useSensors(
        useSensor(PointerSensor, {
            activationConstraint: { delay: 2 }
        }),)
```

**Comment by adrice727** [comment]
Using `{ delay: 100 }` is working well for me.

**Comment by jiazez** [comment]
You can try to do something in onDragEnd
`const onDragEnd = (event) => {
    const { active, over } = event;
    if (active?.id !== over?.id) {
      setPlanArrange((items) => {
        const oldIndex = items.findIndex(item => item?.id == active?.id);
        const newIndex = items.findIndex(item => item?.id == over?.id);
        if (newIndex) setCurrentIndex(newIndex);
        return arrayMove(items, oldIndex, newIndex);
      });
    } else {
      const index = planArrange.findIndex(item => item?.id == active?.id)
      if (index) setCurrentIndex(index);
    }
  };`

**Comment by ivanjeremic** [comment]
Add it above the listeners,

```js
<div
                ref={setNodeRef}
                onClick={(e) => {
                    if (e.detail == 2) {
                        console.log("Double Clicked")
                    }
                }}
                {...attributes}
                {...listeners}
                style={style}
            >
                Card
</div>
```

**Comment by milmaj** [comment]
`
const sensors = useSensors(
    useSensor(PointerSensor,
      {
        activationConstraint: { distance: 2 } // the fix to have both onClick and move, should be > 0
      }
    ),
// other sensors
  );
`

**Comment by diasraphael** [comment]
this is not working well, click event is not working well.

**Comment by dolutattoo** [comment]
Not sure if that can help but here is my "solution".

I logged the `onActivation` event from `MouseSensor` sensor:
```tsx
const sensors = useSensors(
  useSensor(MouseSensor, {
    onActivation: (event) => console.log("onActivation", event), // Here!
    activationConstraint: { distance: 5 },
}))
```

Then I saw that `event.srcElement` was pointing to the very last child div of my draggable component.
I then added `onMouseDown` on that div, and it just worked perfectly fine.

Note: I am also using the `onDragStart` prop of DndContext, but for different purpose. This is why you can see a distance activation constraint in the provided code. In case you don't use this prop, you could also use it to handle click, but Im not sure if this is a good practice.

**Comment by hitzvera** [comment]
useSensor(PointerSensor, {
      activationConstraint: {
        distance: 5
      }
    }),
    
    for me this one works pretty well

**Comment by hitzvera** [comment]
```javascript
const sensors = useSensor(PointerSensor, {
  activationConstraint: {
    distance: 5
  }
});
```

this one works pretty well for me

**Comment by Lekhan2004** [comment]
Did the issue resolve 
I am having the same issue

**Comment by an33k** [comment]
using a handle can detect onClick

**Comment by Vamdez** [comment]
Using it like this it worked
```
  const sensors = useSensors(
    useSensor(PointerSensor, {
      activationConstraint: {
        distance: 8,
      },
    })
  );
```

**Comment by yusuf-delvi** [comment]
> ```js
> const sensors = useSensor(PointerSensor, {
>   activationConstraint: {
>     distance: 5
>   }
> });
> ```

this worked for me too

**Comment by pppdns** [comment]
Both of these worked for me:

```
const sensors = useSensor(PointerSensor, {
  activationConstraint: {
    distance: 5
  }
});
```

```
const sensors = useSensor(PointerSensor, {
  activationConstraint: {
    delay: 100,
    tolerance: 5,
  },
});
```

**Comment by sucheth4101** [comment]
`  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 5 } }));`
Worked for me

**Comment by zhenzhenChange** [comment]
Re-emit the event. Attention should be paid to the element type as well as null value handling.

```tsx
const sensors = useSensors(
    useSensor(MouseSensor, {
      onActivation: (e) => {
        console.log(e)

        // Re-emit the event.
        e.event.target.click()
      },
    }),
    useSensor(TouchSensor, {
      onActivation: (e) => {
        console.log(e)

        e.event.target.click()
      },
    }),
    useSensor(PointerSensor, {
      onActivation: (e) => {
        console.log(e)

        e.event.target.click()
      },
    }),
  )
```

**Comment by MuhammadSami1** [comment]
> ` const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 5 } }));` Worked for me

work for me

**Comment by devrahuljourney** [comment]
`onPointerDown={(e) => e.stopPropagation()}` // use onPointerDown() instead of onClick().


Events travel from parent to child and then back up. If you stopPropagation on pointerDown inside a dnd-kit draggable item, you block the drag listeners from catching the event. onClick fails because dnd-kit uses pointerDown to detect drags, so the click never gets generated. Pointer events happen before click, so they have higher priority and always fire.

**Comment by devrahuljourney** [comment]
> I am using useSortable and I want to listen to onClick event handler as well, but it is not detecting the click (double click as well). I am just doing as simple as that. How to detect the double click event on draggable ? ?
> 
> ```
> <div
>                 ref={setNodeRef}
>                 {...attributes}
>                 {...listeners}
>                 style={style}
>                 onClick={(e) => {
>                     if (e.detail == 2) {
>                         console.log("Double Clicked")
>                     }
>                 }}
>             >
>                 Card
> </div>
> ```

`onPointerDown={(e) => e.stopPropagation()} // use onPointerDown() instead of onClick().`

Events travel from parent to child and then back up. If you stopPropagation on pointerDown inside a dnd-kit draggable item, you block the drag listeners from catching the event. onClick fails because dnd-kit uses pointerDown to detect drags, so the click never gets generated. Pointer events happen before click, so they have higher priority and always fire.
