### ISSUE TITLE
Use different field for sortable IDs

### ISSUE THREAD

**Issue by dasveloper** [clauderic/dnd-kit#807]
For sortable lists you need to pass unique identifiers under the objects `id` field. In my application, when you add an item to the sortable list, I generate a random ID on the frontend (Date.now), and when I save it to the backend I strip off that id so the database can generate a real CUID for the `id` field. When I want to edit a previously save list, I pull the data from the database, and their `id` properties are the DB generated CUIDs, and then if you add items they're frontend generated Date.nows. When I go to save that updated list, I need to go through the array to distinguish which items `ids` were already in the database so I can update them, and which were just generated on the frontend so I can create a new item. This is of course pretty messy.

This could all be solved if I could just choose a different unique property to pass to the Sortable, such as `key`. I could then drop all `keys` on the backend and rely on the `id` to know if the item exists already or not.

I could  change my database field to something other than `id`, but it's be a lot easier for me to just specify a different field on the frontend for this one specific piece.

It doesn't appear that this is something possible currently? It would be great to add this as a feature.

**Comment by clauderic** [comment]
I'm really not sure I'm following, @dnd-kit does not force your database to adhere to a particular schema or interface.

**Comment by Amareis** [comment]
You can just make so: `<SortableContext items={items.map(i => i.key)}>`

**Comment by bouncingbumble** [comment]
Oh my god I thought I was going fucking insane. `<SortableContext items={items.map(i => i.key)}>` or in my case `   items={items.map((i) => i._id)}` fixed it for me. I don't believe anywhere states that items prop is supposed to be an id list or identical objects.

**Comment by marwin1991** [comment]
same here

**Comment by ksi9302** [comment]
@Amareis Man you saved me

**Comment by laurencantlin** [comment]
> You can just make so: `<SortableContext items={items.map(i => i.key)}>` `items` is bad name for this prop, it should be named something like `itemsIds`, imho.

This was the perfect answer. Totally agree they should change the name of the prop and make that clearer in the documentation.

**Comment by pedrokuper** [comment]
This post helped me a lot! <3<3

My case:  I had an array with objects  like this and the animation wasn't triggering

```json
{
	_id: "60ded95674596800119a39ef",
	name: "some-name",
},
{
	_id: "611c440d25f23800114cfd4a",
	name: "some-name",
},
{
	_id: "60e5e5fb3097a20011bd481f",
	name: "some-name",
},   
```
After finding this issue i understood the docs in a more comprenhensive way.

I think that `items` leads to confusion too. Or that it should be used with a more complex example in the  docs to make people dumb as me understand.

Something like : 

```javascript
  const [items, setItems] = useState([{someid: 1, name: "somename"}, {someid: 2, name: "somename2"}]);

  return (
    <DndContext>
      <SortableContext items={items.map(item) =>  item.someid }>
        {/* ... */}
      </SortableContext>
    </DndContext>
  );
}

```

**Comment by albanyacademy** [comment]
If you don't actually care about making sure your arrays have a unique ID, this may be helpful:

https://github.com/clauderic/dnd-kit/issues/183#issuecomment-2050612127
