### ISSUE TITLE
feature request: collision detection for sibling `useDraggable`

### ISSUE THREAD

**Issue by chris-kruining** [clauderic/dnd-kit#810]
I am making a visual scripting where my nodes are draggable items. I would like to prevent items from laying on top of each other, so I would therefor like a method of detecting collisions between draggables. Would this be possible. Or is this already done in `Sortable`, and if so: how?

**Comment by clauderic** [comment]
You can detect collisions between sibling draggables by also connecting them to `useDroppable`, similar to how the `useSortable` hook works:

https://github.com/clauderic/dnd-kit/blob/master/packages/sortable/src/hooks/useSortable.ts#L103
