### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'x' in undefined

### ISSUE THREAD

**Issue by kobe651jp** [clauderic/dnd-kit#812]
When I try to use sensor with delay option,getting errors.

```
core.esm.js:936 Uncaught TypeError: Cannot use 'in' operator to search for 'x' in undefined
    at hasExceededDistance (core.esm.js:936:12)
    at MouseSensor.handleMove (core.esm.js:1265:13)

```
sample code as follows
https://codesandbox.io/s/staging-fast-8rrs0x

**Comment by zym-creaor** [comment]
useSensor(KeyboardSensor, {
            coordinateGetter: sortableKeyboardCoordinates,
            activationConstraint: {
                delay: 150, //Delay write dot
                tolerance: 5,
            },
        }),

**Comment by LieutenantCrunch** [comment]
Just ran into this same problem, turns out that the tolerance is required, not optional. You can set it to 0 and it should still work

**Comment by altsst** [comment]
> useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates, activationConstraint: { delay: 150, //Delay write dot tolerance: 5, }, }),

proper code formatting
```
useSensor(KeyboardSensor, {
  coordinateGetter: sortableKeyboardCoordinates,
  activationConstraint: {
    delay: 150, //Delay write dot
    tolerance: 5,
  },
}),
```

**Comment by altsst** [comment]
Solution: Don't forget to set the tolerance.

// CLOSED

**Comment by Pagebakers** [comment]
Just ran into this, it's not clear from th docs and the types are incorrect, this issue should be re-opened imho.
