### ISSUE TITLE
Key undefined

### ISSUE THREAD

**Issue by dnorrstrand** [clauderic/dnd-kit#815]
I am trying to implement a sortable list as follows:

```
 <DndContext
  sensors={sensors}
  collisionDetection={closestCenter}
  onDragStart={handleDragStart}
  onDragEnd={handleDragEnd}
>
    <SortableContext items={items} strategy={verticalListSortingStrategy}>
        {items.map((item) => (
            <SortableItem key={item.elementID + "L"} id={item.elementID + "L"} pane="left" item={item} />
        ))}
    </SortableContext>
    <DragOverlay>
        {activeId ? <TreeNodeLeft pane={props.pane} node={node.children[0]} id={activeId} /> : null}
    </DragOverlay>
</DndContext>
```

Each item is an object that looks roughly as follows:

```
{
    bindID: 8
    children: []
    elementID: "02_00000007_00000008_000000"
    icon: "FaCubes"
    iconLink: "position.ico"
    isDummy: false
    label: {Name: 'Position22', Code: null, Quantity: '1,00', Unit: '', backgroundColor: '#ffffff'}
    level: 2
    objectID: 7
    objectType: 2
    parentSequence: 1
    rightPaneData: (8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
    sequence: 4
    tenderID: 8650
    title: ""
}
```

I am console.logging the key and id since I cannot get the code to work and in the logs I see that the id looks OK with the value I am giving it yet the key is undefined:

```
Props in sortableItem 
{id: '02_00000007_00000008_000000L', pane: 'left', item: {…}}
id: "02_00000007_00000008_000000L"
item: {sequence: 4, parentSequence: 1, elementID: '02_00000007_00000008_000000', level: 2, tenderID: 8650, …}
pane: "left"
key: undefined
get key: ƒ ()
[[Prototype]]: Object
```
Is there something I am doing wrong and how can I get it to work? Thanks.

**Comment by clauderic** [comment]
The `key` prop is a reserved prop in React and is not available on the `props` that your component receives, it is reserved for internal use by React.

**Comment by dnorrstrand** [comment]
I cannot get the sorting algorithm to work with the setup above. [This](https://1drv.ms/v/s!AheIRjLGkVk_ifhvipdtic4z5sRWPw?e=eCRXit) is what I get. Is there any way to fix it?

**Comment by dnorrstrand** [comment]
What does the {value} refer to in this example?
[Screenshot](https://1drv.ms/u/s!AheIRjLGkVk_ifhw2DiUkDhBWWuQHw)

**Comment by clauderic** [comment]
>What does the {value} refer to in this example?
[Screenshot](https://1drv.ms/u/s!AheIRjLGkVk_ifhw2DiUkDhBWWuQHw)

That's a typo, it should be `{props.id}`

**Comment by dnorrstrand** [comment]
Thanks.
On another topic, is there a way to implement synchronous drag of two items together with the same sorting behaviour?
[Here](https://1drv.ms/u/s!AheIRjLGkVk_ifhxGsV1-jaSUdP3tg) is my setup.
