### ISSUE TITLE
Autoscroll not working with DragOverlay

### ISSUE THREAD

**Issue by jordand-stripe** [clauderic/dnd-kit#816]
First off, just wanted to say how much I've been enjoying using dnd-kit! It was a breeze integrating it with our application and I'm super impressed with the UX, performance, and clean APIs.

I'm running into an issue with `DragOverlay` that seems to prevent `autoScroll` from working. If I remove the `DragOverlay`, autoscroll works just fine. Here's a quick repro: https://codesandbox.io/s/dragoverlay-autoscroll-xet2sv

Thanks for all of your work on this library!

**Comment by clauderic** [comment]
I think this is a bug that was fixed a while back, I'm unable to replicate when using the latest version of all `@dnd-kit` packages.

https://codesandbox.io/s/dragoverlay-autoscroll-forked-bntv5e
