### ISSUE TITLE
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

### ISSUE THREAD

**Issue by MuhammadHamzaChippa** [clauderic/dnd-kit#822]
I am trying to implement the double nested list and getting this error. Codebase looks like this and whenever I change the container i.e. move the useSortable from one container to another. It crashes the app and onDragOver function is gets executed many times.
(For the sake of simplicty I am keeping the codebase as simple as possible)
const DoubleNestedList = () => {
const onDragStart = () => {
}

const onDragOvert = () => {
}

const onDragEnd = () => {
}

return (
<DndContext>
container.map(container => (
 <SortableContext items = {items[container]}>
{items[container].map(item => 
<DraggableCard item={item} key={item.id} />
)}
</SortableContext>
))
<DndContext>
)

 }

**Comment by MuhammadHamzaChippa** [comment]
Replacing closestCenter algorithm with pointer within solved the problem

**Comment by kelvin-binary** [comment]
@MuhammadHamzaChippa I am facing the issue as well, could you please show the sample code here? Thank you.

**Comment by aminghk** [comment]
@MuhammadHamzaChippa your solution works for me too, thanks

**Comment by hsavit1** [comment]
solution did not work for me

**Comment by cisc0disco** [comment]
@MuhammadHamzaChippa when having empty list and want to pass something inside it pointer within algo doesn't work and closestCenter crashes, spent already 10 hours fixing it :(
