### ISSUE TITLE
Can not drag a sortable Item into an empty container

### ISSUE THREAD

**Issue by ask-imran** [clauderic/dnd-kit#828]
I am running into a similar issue as #708 
I am trying to create a two column drag and drop layout, when one of the column is empty I am unable to move any items into it. 
Reproduce-able code: https://codesandbox.io/s/dnd-kit-multi-containers-forked-vqy7t0?file=/src/app.js:1771-1832

If I move `renderSortableContext` into its own component, it seems to be resolved. I am pretty sure I am missing something. Any help would be appreciated.! Thank you.!

**Comment by h1orz** [comment]
This is Context use problem. You should use useSortable in sub component. useSortable need DndContext instantiated.

**Comment by bannarisoftwares** [comment]
Hi @ask-imran , How you resolved this issue? Can you update please, I am also stuck :)

**Comment by wilayat8070** [comment]
I have the same issue, but making the container droppable worked for me.
