### ISSUE TITLE
onClick handler for DndContext

### ISSUE THREAD

**Issue by hhabakuk** [clauderic/dnd-kit#83]
Hi!

First of all, thanks for a great library!
I'm struggling with finding a good way to send onClick event to a draggable and sortable item - kind of works  if I remove "onDragStart" prop and use only "onDragMove" to handle dragging but in that case the click needs to be quite precise. Looking for a way to handle clicking with a bit more buffer between click and dragMove.

[Codesandbox](https://codesandbox.io/s/test-dnd-kit-forked-tqswe?file=/src/SortableItem.js) here.

**Comment by clauderic** [comment]
Hey @hhabakuk, you can set an [`activationConstraint`](https://docs.dndkit.com/api-documentation/sensors/pointer#activation-constraints) on the Pointer sensor to allow clicks to not be treated as qualified drag start events:

In this example I added a `distance` constraint, but you could also use a `delay` constraint.
https://codesandbox.io/s/test-dnd-kit-forked-qyjw2
