### ISSUE TITLE
Using flexbox, first draggable items goes behind latest items

### ISSUE THREAD

**Issue by MarcosCunhaLima** [clauderic/dnd-kit#831]
Hi

I have a simple example using DND using flexBox which I don't get right. Just 3  draggable/droppable items in a flexbox container.
When I drag first item into second or third, it goes behind them while dragging. When I drag third item into second or first item, it looks OK.

You could simulate this in: [https://codesandbox.io/s/fast-mountain-xt34l9?file=/src/App.js]( )

Do I have missing something?

**Comment by MarcosCunhaLima** [comment]
The problem was that each element has position=relative which creates a new "environment" in order to control zIndex for the element and its children.

**Comment by shoooe** [comment]
@MarcosCunhaLima So what solution would you recommend?
