### ISSUE TITLE
Multiple draggables within a sortable context

### ISSUE THREAD

**Issue by dnorrstrand** [clauderic/dnd-kit#843]
I haven't been able to find a word on this in the dox, so please point me in the right direction, if this has been addressed. I need to implement a multiple items selection feature  which would allow them to be dragged within their parent (sortable container) and have non-selected siblings sort themselves as if the selected draggables were a single draggable item. My current setup looks like this:

![Screenshot 2022-07-22 at 19 16 30](https://user-images.githubusercontent.com/73636189/180482716-80334996-b28f-437b-8982-1c95d4299a70.png)

Would this be possible?

**Comment by hexwit** [comment]
I am not a maintainer, but as I understood, you have to implement this manually. 
So you have to render appropriate overlay, and track selection to handle that in onDragEnd event, and move items appropriately.

**Comment by dnorrstrand** [comment]
> I am not a maintainer, but as I understood, you have to implement this manually. So you have to render appropriate overlay, and track selection to handle that in onDragEnd event, and move items appropriately.

Thanks a lot for the hint... I was hoping there would be some interface already available in DND Kit since there is an example [here](https://5fc05e08a4a65d0021ae0bf2-yivpqsvbcy.chromatic.com/?path=/story/presets-sortable-multiple-containers--multi-select)
