### ISSUE TITLE
Sortable not working with Array of Objects

### ISSUE THREAD

**Issue by ivanjeremic** [clauderic/dnd-kit#845]
I have here a [CodeSanbox ](https://codesandbox.io/s/lucid-yalow-77hh97?file=/src/App.tsx) to show the issue I have, One Grid is with an Array of Objects which have `id` & `title` but `handleDragEnd` does not work here for some reason and the items jump on drag end to the starting position back.

But when I use an Array with just numbers it works fine and `handleDragEnd` moves the Array correctly.

What am I missing here and doing wrong? Thanks

**Comment by KalenAnson** [comment]
Inside your `setItems()` function call inside of the `handleDragEnd()` handler, you are not correctly getting the index of the matching items.

Try the following instead:

    // const oldIndex = items.indexOf(active.id);
    const oldIndex = items.findIndex(item => item.id === active.id);
    //const newIndex = items.indexOf(over.id);
    const newIndex = items.findIndex(item => item.id === over.id);

**Comment by ivanjeremic** [comment]
Thanks you, it works now :) And Thank you for this library, hope the Examples will improve I will try to help where I can.

The next problem now is in my case the performance is very bad and the drag experience laggy, What I have in my app is an array of arrays each array is a page (Swiper) and each swiper page has it's own `DndContext` & `SortableContext`, I use `useMemo` where I can but somehow it feels like it just takes the lib too long to compare the id's, is there any way I can improve this? 
````ts
const { data } = useQuery([queryKey, { id }], getData);
// chunk the big array to get array of arrays for pagination
const pages = useMemo(() => chunk(data, perPage), [data]);

return (
 <Swiper>
          {pages?.map((page) => (
            <SwiperSlide
              key={JSON.stringify(page)}
              className={`grid auto-rows-[max-content] unset-slide-styles`}
            >
              <SortableStateContainer page={page}> // in this wrapper I set the items because it's paginated
                {(
                  items: any[],
                  handleDragEnd: ((event: DragEndEvent) => void) | undefined
                ) => (
                  <DndContext
                    collisionDetection={closestCenter}
                    onDragEnd={handleDragEnd}
                  >
                    <SortableContext items={page.map((i) => i.id)}>
                      {items?.map((item: any) => (
                        <SortableItem
                          key={item.id}
                          id={item.id}
                          title={item.title}
                          url={item.url}
                          context={context}
                        />
                      ))}
                    </SortableContext>
                  </DndContext>
                )}
              </SortableStateContainer>
            </SwiperSlide>
          ))}
        </Swiper>
)
```

**Comment by porkopek** [comment]
@ivanjeremic Use Virtualization for long lists, like https://virtuoso.dev/

**Comment by ivanjeremic** [comment]
> @ivanjeremic Use Virtualization for long lists, like https://virtuoso.dev/

I feel like this is not the issue because dnd-kit has nothing really expensive to do, I do the chunking upfront and the biggest array a single SortableContext gets is around 40 items which is not really a big thing. Hmm

**Comment by clauderic** [comment]
This can happen if your component is expensive to re-render. Try creating a separate presentational component that you are connecting to `useSortable` and memoize it using `React.memo` to avoid un-necessary re-renders.

Read more about this pattern here:
https://docs.dndkit.com/api-documentation/draggable/drag-overlay#presentational-components

**Comment by ivanjeremic** [comment]
> This can happen if your component is expensive to re-render. Try creating a separate presentational component that you are connecting to `useSortable` and memoize it using `React.memo` to avoid un-necessary re-renders.
> 
> Read more about this pattern here: https://docs.dndkit.com/api-documentation/draggable/drag-overlay#presentational-components

Browser devtools where the issue, when devtools are open then it becomes laggy. Thanks
