### ISSUE TITLE
Snapping to droppable

### ISSUE THREAD

**Issue by JSmajdor1997** [clauderic/dnd-kit#849]
Hi,

How can one achieve snapping dragged element to multiple drop areas? 

For example draggable is inside _droppable A_ and may be freely moved inside, once cursor leaves droppable _A_ draggable stays as if  _restrictToParentElement_ was used, but once cursor moves nearer to _droppable B_ than to _A_, draggable 'jumps' into _B_.

Obviously one could use either custom modifier (but it would require reacting to layout changes, calculating multiple properties, etc) or conditional rendering and reacting to _onDragMove_, but can this be solved better way?

**Comment by clauderic** [comment]
You would have to write a custom modifier to achieve behaviour https://docs.dndkit.com/api-documentation/modifiers#building-custom-modifiers

**Comment by JSmajdor1997** [comment]
@clauderic Thank you very much, I have already attempted implementing it this way and found out it's is actually quite clean solution, I have written custom modifier and custom collision detection (composed):

Collision detection algorithm:
`
const collisionDetection: CollisionDetection = (args) => {
    const pointerWithinCollisions = pointerWithin(args)

    if(pointerWithinCollisions.length != 0) {
        return pointerWithinCollisions
    } else {
        return closestCenter(args)
    }
}
`

Modifier:
`
const modifier: Modifier = (args) => {
    if(args.active == null) {
        return args.transform
    }

    const item = args.active.data.current as DragData

    const HORIZONTAL_GRID_SIZE = 20

    const {draggingNodeRect, transform} = args

    if (draggingNodeRect == null || args.over == null) {
        return transform;
    }

    return restrictToBoundingRect(transform, draggingNodeRect, args.over.rect)
}
`
