### ISSUE TITLE
Trying to update cursor on drag doesn't work on some screens.

### ISSUE THREAD

**Issue by rpivo** [clauderic/dnd-kit#85]
Really loving this library so far.
I'm seeing an odd behavior where starting to drag will not trigger `:active` styles or call `onMouseDown` on the draggable.

In the below screenshot, I'm using a DragOverlay on drag, although this issue seems to occur with or without the DragOverlay.

The draggable has a specified CSS width and height, and it doesn't have any contents. The DragOverlay also has the same width and height.

When I click to drag on the draggable, it appears that the cursor will not change unless I clicked closer to the lower right corner of the draggable. 

If there are multiple draggables inside the droppable container, the first draggable appears to not allow cursor change on click if the click happens anywhere directly below the top left quadrant or directly to the right of the top left quadrant, but the bottom right quadrant works fine.

Successive draggables beyond the first one inside a droppable container appear to have a larger portion where the cursor change is working, but the top left quadrant still doesn't work as expected.

Oddly, if I try this on just my laptop screen (roughly 15-inch), which is a touch screen, everything works fine. When clicking with the mouse on this laptop screen, it's all working perfectly. I'm not sure if this is because pointer and touch events would register differently on that screen, or because the screen is a smaller form factor than my other screen (note that the actual elements on the screen, including draggables and droppables, are the same pixel size on both screens).

The issue occurs exclusively on an external monitor (roughly 25-inch). This monitor doesn't have touch capabilities.

Happy to investigate this further within the dnd-kit codebase if there are any spots worth looking into.

Thanks!

![grab](https://user-images.githubusercontent.com/28677706/107375209-7b4a6f80-6ab6-11eb-9269-80c2175db915.gif)

**Comment by clauderic** [comment]
In my experience, the most reliable way to update the cursor is to dynamically update the `cursor` property on the `document.body` and set `pointer-events: none` on the drag overlay.

Something like:

```tsx
<DndContext
  onDragStart={() => {
    document.body.style.setProperty('cursor', 'grabbing');
  }}
  onDragEnd={() => {
    document.body.style.setProperty('cursor', '');
  }}
```

**Comment by rpivo** [comment]
@clauderic thanks. I tried:

```
  function handleDragEnd(event) {
    ...
    document.body.style.setProperty('cursor', '');
    ...
  }

  function handleDragStart(event) {
    ...
    document.body.style.setProperty('cursor', 'grabbing');
    ...
  }

...
```

It looks like I'm still seeing the issue with this, and I can see that the cursor now reverts back to a regular pointer when letting go, so it looks like the `setProperty` to an empty string is working..

I also have these styles on the DragOverlay being passed in elsewhere:

```
export const dragOverlay = {
  cursor: 'grabbing',
  pointerEvents: 'none'
};
```

Setting `cursor: 'grabbing'` on the DragOverlay seems to be helpful, but not on this screen.

Do you have any other suggestions for what could be happening here?

Is this likely an issue in my codebase, or do you recommend I look into this within the dnd-kit codebase somewhere as to what could be happening? Happy to help with this.

![grab2](https://user-images.githubusercontent.com/28677706/107385297-c2d5f900-6ac0-11eb-9eb5-038786d3a4c9.gif)

**Comment by rpivo** [comment]
Also worth noting that in Choice 2, the issue occurs when clicking directly on the text. Choice 1 has the issue occurring over most of the draggable, except for when I click on a small corner in the bottom right of the draggable.

**Comment by clauderic** [comment]
Are you able to replicate the issue in the stories here http://examples.dndkit.com/?

Can you share a bit more code or better, a CodeSandbox replicating the issue?

**Comment by rpivo** [comment]
@clauderic -- actually, it does look like I can replicate similar grab cursor issues in the storybook.

That story works fine on my laptop screen, but the behavior occurs on my external monitor.

![grab3](https://user-images.githubusercontent.com/28677706/107388213-966fac00-6ac3-11eb-854c-e7bfd7f04058.gif)

**Comment by rpivo** [comment]
@clauderic I'll see if I can sandbox this issue and provide a link here.

**Comment by rpivo** [comment]
@clauderic here is a simple codesandbox where I can see the problem occur: https://codesandbox.io/s/gracious-fermi-8i25x?file=/src/App.js

On my laptop screen, I am unable to replicate the issue, but on my external monitor, I'm able to see the issue in the sandbox.

Here's what I'm seeing:

![grab4](https://user-images.githubusercontent.com/28677706/107396515-d044b080-6acb-11eb-8205-e49ab06d894c.gif)

**Comment by rpivo** [comment]
@clauderic it looks like this only happens on my Windows machine, but not on Mac -- it could be some kind of driver issue.
