### ISSUE TITLE
Cancel drag when the the draggable item loses focus

### ISSUE THREAD

**Issue by marcospassos** [clauderic/dnd-kit#857]
Currently, when dragging using the keyboard, the item remains active even when focusing out of it. It leads to [several issues](https://github.com/ariakit/ariakit/issues/1684#issuecomment-1200007524) that can't be solved at the userland.

I tried implementing a custom sensor, but the current design doesn't allow for extension (note the `ts-ignore`):

```ts
/**
 * A custom keyboard sensor cancels the drag when moving the focus out of the draggable element.
 */
class CustomKeyboardSensor extends KeyboardSensor {
    private readonly sensorProps: SensorProps<SensorOptions>;

    constructor(props: KeyboardSensorProps) {
        super(props);

        this.sensorProps = props;

        this.handleDragCancel = this.handleDragCancel.bind(this);

        this.attachSensor();
    }

    private attachSensor(): void {
        this.sensorProps.event.target?.addEventListener('blur', this.handleDragCancel);
    }

    private detachSensor(): void {
        this.sensorProps.event.target?.removeEventListener('blur', this.handleDragCancel);
    }

    private handleDragCancel(): void {
        // There's no other way to notify the parent class to clean up the state.
        // @ts-ignore
        this.detach();
        this.detachSensor();
        this.sensorProps.onCancel();
    }
}
```

Even ignoring the error, other issues arise. For example, using the `CustomKeyboardSensor`, when pressing enter to finish dragging, DND kit announces the event as a cancel operation. Even worse, after calling the `onCancel` callback, in response to a click outside, the item steals the focus back, so you need to click twice to move the focus away from the item.

**Comment by codewitch** [comment]
Would love assistance on this as well. If a non keyboard user accidentally gets into a keyboard drag state, the app will feel like it is broken since they cant cancel the drag by clicking elsewhere.

One thought would be to build a combination sensor that taps into both keyboard and click events?

**Comment by pwang347** [comment]
For what it's worth, here's something hacky I did that seems to be working fine and not running into the issues mentioned above. Note also that in my application I am using `handleEnd` instead of `handleCancel`.

```typescript
export class CustomKeyboardSensor extends KeyboardSensor {
    constructor(props: KeyboardSensorProps) {
        super(props);

        const handleEnd = (this as any).handleEnd.bind(this);
        const detach = (this as any).detach.bind(this);

        props.activeNode.activatorNode.current?.addEventListener("blur", handleEnd);

        // hack: override the detach method to also remove the blur event
        (this as any).detach = () => {
            detach();
            props.activeNode.activatorNode.current?.removeEventListener("blur", handleEnd);
        };
    }
}
```

**Comment by theenoahmason** [comment]
Just chiming in here. After trying all of these methods and not being completely happy with them, I have come up with react-only, slightly hacky solution that will not break on updates to the keyboard sensor.

The methodology is to store a render key that can be used to force a remount of the sortable container when blur events are captured inside of it. See code below (note I have omitted everything but the code that pertains to this solution).

```tsx
export default function SortableContainer {

	/**
	 * Initialize render key state. This will be used to force
	 * a remount of the component, clearing its internal state.
	 */
	const [renderKey, setRenderKey] = useState<number>(0);

	/**
	 * Initialize keyboard active state.
	 */
	const [isKeyboardActive, setIsKeyboardActive] = useState<boolean>(false);

	/**
	 * Set keyboard active to true on the sensor's `onActivation` callback.
	 * Bonus: set "Tab" as a drag end (or cancel) trigger.
	 */
	const keyboardSensor = useSensor(KeyboardSensor, {
		// ...
		onActivation: () => setIsKeyboardActive(true),
		keyboardCodes: {
			end: ["Space", "Enter", "Tab"],
		},
	});

	const sensors = useSensors(keyboardSensor);

	/**
	 * Drag ended, set keyboard active to false.
	 */
	const handleDragEnd = useCallback(() => {
		// ...
		setIsKeyboardActive(false);
	}, []);

	/**
	 * Drag cancelled, set keyboard active to false.
	 */
	const handleDragCancel = useCallback(() => {
		// ...
		setIsKeyboardActive(false);
	}, []);

	/**
	 * On blur capture (any blur inside the target element), augment
	 * the render key, which will forces a remount of the container.
	 */
	const handleBlurCapture = useCallback(() => {
		if (isKeyboardActive) {
			// ...
			setRenderKey(key => (key + 1));
		}
	}, [isKeyboardActive]);

	return (
		<div
		{/* ... */}
		key={`SortableContainer-${renderKey}`}
		onBlurCapture={handleBlurCapture}>
			<DndContext
			{/* ... */}
			onDragEnd={handleDragEnd}
			onDragCancel={handleDragCancel}>
				{/* ... */}
			</DndContext>
		</div>
	);
}
```

**Comment by theenoahmason** [comment]
See [my answer here](https://github.com/clauderic/dnd-kit/issues/1367#issuecomment-2292433281) for how I implemented a pretty solid fix to this, including typescript support.
