### ISSUE TITLE
Problem with starting dragging when window scrolled veritcally

### ISSUE THREAD

**Issue by ozanarmagan** [clauderic/dnd-kit#86]
Hey, 

I have a problem and I dont know if its bug or not,but when the window is scrolled vertically (or when window.scrolly is not 0 we can say) if you pick up an item to drag it,it does not work properly.

initial:

https://user-images.githubusercontent.com/70442658/107522601-ef733900-6bc4-11eb-801b-b3da1aa1be30.mp4

when you scroll down the window a little bit:

https://user-images.githubusercontent.com/70442658/107522736-0ade4400-6bc5-11eb-9b32-3e43f08088a3.mp4

`            <DndContext   onDragOver={this.dragOverArticle} onDragStart={this.dragStart} onDragCancel={this.dragCancel} onDragMove={this.dragMove}>

            <div class="grid-newArticle">
                <div class="yazilar" style={{minHeight:"800px",width:"368px"}}>
                <div class="panel is-primary">
                    <div class="panel-heading" style={localStorage.getItem("theme")=="1" ? {textAlign:"center",backgroundColor:"#cc3333"} : {textAlign:"center",backgroundColor:"#00d1b2"}}>Yazılar</div>
                    <div class="card-body" style={localStorage.getItem("theme")=="1" ? {backgroundColor:"#333131",height:"800px"} : {backgroundColor:"#eae7e7",height:"100%"}}>
                    <FormGroup>
                        <Input type="text" onChange={this.onChangeSearch} placeHolder="Filtrele..." style={{marginTop:"17px",marginBottom:"20px"}} value={this.state.search}/>
                    </FormGroup>
                    <SortableContext  items={this.state.articles.filter(article => article.section==null).map(article => article.id)}>
                    {this.state.articles.filter(article => article.section == null).map(article => (
                        <Draggable key={article.id} url={article.id} article={article}/>
                    ))}
                    </SortableContext>
                </div>
                </div>
                </div>
                <div class="bölümler" style={{minHeight:"800px",width:"860px"}}> 
                <div class="row" style={{marginTop:"20px"}}>
                <Input type="text" value={this.state.newSectionName} onChange={this.onChangeSectionName} placeHolder="Yeni Bölüm ismi" style={{width:"250px"}}/>
                <button class="primebtn" style={{fontSize:"13px",marginLeft:"10px"}} onClick={this.newSection}>Ekle</button></div>
                <br/>
                <Grid columns={3}>
                  <SortableContext items={this.state.sections.map(section => section.id)}>
                     {
                         this.state.sections.map(section => (
                             <DraggableSection key={section.id} url={section.id} section={section} theme={localStorage.getItem("theme")}>
                                <SortableContext items={this.state.articles.filter(article => article.section == section.id)}>
                                    <Droppable id={section.id} key={section.id}>
                                                {
                                                    this.state.articles.filter(article => article.section == section.id).map(article => (
                                                        <Draggable key={article.id} url={article.id} article={article}/>
                                                    ))
                                                }
                                    </Droppable>
                                </SortableContext>
                             </DraggableSection>
                         ))

                     }
                  </SortableContext>  
                </Grid>
                </div>
                <div class="görünüm" style={{minHeight:"800px"}}>görünüm</div>
                
            </div>
            <DragOverlay>
            {
                this.state.isActive ? (
                    typeof this.state.activeItem == 'string' ? <SectionOverlay theme={localStorage.getItem("theme")} section={this.state.sections.filter(section => section.id == this.state.activeItem)[0]}>
                                                                        {
                                                                            this.state.articles.filter(article => article.section == this.state.sections.filter(section => section.id == this.state.activeItem)[0].id).map(article => (
                                                                                <ArticleOverlay  article={article}/>
                                                                            ))
                                                                        }
                                                                </SectionOverlay>
                                                            :  <ArticleOverlay  article={this.state.articles.filter(article => article.id == this.state.activeItem)[0]}/>
                ) : (null)
            }
            </DragOverlay>
          </DndContext>`

**Comment by ubeydtalha** [comment]
![photo5850343931236169035](https://user-images.githubusercontent.com/62707118/107702477-5a0e9c80-6ccb-11eb-82e4-6849307fd4a0.jpg)

brooo.

Same problem to ,moreover I used same code in example (copy paste)

**Comment by clauderic** [comment]
Hey @ozanarmagan, can you re-open the issue with a reproduction case in CodeSandbox replicating the issue pleasee.
