### ISSUE TITLE
Maximum update depth exceeded DndContext

### ISSUE THREAD

**Issue by DAJAKMPM** [clauderic/dnd-kit#861]
I am currently following the implementation of the multiple container Vertical Grid in dnd-kit's storybook implementation and when attempting to drag and drop an item to another container, a warning occurs as shown below:

![image](https://user-images.githubusercontent.com/33202282/183437987-4d45436a-c336-4d76-bf67-32cc2e09c5fa.png)

Listed below are the versions of dnd-kit that I have been using:
-     "@dnd-kit/core": "^6.0.5",
-     "@dnd-kit/sortable": "^7.0.1",
-     "@dnd-kit/utilities": "^3.2.0",

**Comment by victorsmits** [comment]
did you solve your issue ?

**Comment by ajmar3** [comment]
I am also having this issue

**Comment by DAJAKMPM** [comment]
I was using the latest versions of @dnd-kit and the react version of our project is 17.0.1. The workaround that I did was that I searched for a compatible @dnd-kit version to react v17.0.1 which is the list below:

"@dnd-kit/core": "5.0.3",
"@dnd-kit/sortable": "6.0.1",
"@dnd-kit/utilities": "3.2.0"

After applying this changes, it is working as expected without changing any code that I have implemented.

**Comment by pantelispanayiotou** [comment]
Any updates on this? I have the same issue when i drag fast. The error points to line 372 on the dispatch inside the drag move.

**Comment by parsagholipour** [comment]
This happens when I have many draggables and I drag fast

**Comment by a-borodko** [comment]
I have the same issue, React v17.0.2. 
"@dnd-kit/core": "^6.1.0",
"@dnd-kit/sortable": "^8.0.0",
"@dnd-kit/utilities": "^3.2.2",

Downgrade to the same version as @thisisdajaaa, thank you.
