### ISSUE TITLE
Animation plays twice when swapping vertically aligned elements in a grid

### ISSUE THREAD

**Issue by mahhmoud-enzyme** [clauderic/dnd-kit#875]
you can try it out here.
[sandbox](https://codesandbox.io/s/dndkit-grid-with-drag-handle-example-forked-s94d9u)

let me know if I'm missing something

**Comment by natan-fernandes** [comment]
A bit late but this is how I fixed it: https://github.com/clauderic/dnd-kit/issues/767#issuecomment-1646716469
