### ISSUE TITLE
Error buliding with TypeScript 4.8

### ISSUE THREAD

**Issue by benasher44** [clauderic/dnd-kit#877]
Hi there! We're getting the following error building the latest version (6.0.5) of the core package:

```
Error: node_modules/@dnd-kit/core/dist/sensors/types.d.ts(56,20): error TS2344: Type 'T' does not satisfy the constraint 'Object'.
```

It looks like one of the generic T parameters is missing an `extends Object` or `extends {}`, which TS 4.8 is stricter about.

**Comment by dcousens** [comment]
Relevant typescript
https://github.com/clauderic/dnd-kit/blob/3abe4f13a3db7c3c8257a7175728cf9a8e1d577c/packages/core/src/sensors/types.ts#L76-L87

See
```typescript
sensor: Sensor<T>; 
```

Cannot be satisfied when `T` is **not** refined to `extend Object`.

> (type parameter) T in type SensorDescriptor<T>
> Type 'T' does not satisfy the constraint 'Object'.
> ... This type parameter might need an `extends Object` constraint.

**Comment by Ayc0** [comment]
I can propose a PR
