### ISSUE TITLE
Cannot focus inputs inside of draggable items

### ISSUE THREAD

**Issue by apledger** [clauderic/dnd-kit#88]
Hey @clauderic, love the project and the API. Great work.

We have an application where we are rendering layers in a sortable list that can each open a popup with some inputs. While integrating dnd-kit, I ran into an issue where I couldn't focus any inputs in a portaled popup. I also noticed that I can still drag the popup due to the pointer events being bubbled through the synthetic tree. 

We've dealt with similar issues in our app, and have solved it by checking if `event.currentTarget.contains(event.target)` before calling `preventDefault` and doing our behavior.

I was wondering if you've got a good way to solve this?

Here's a [Codesandbox](https://codesandbox.io/s/dnd-kit-portaled-input-023xp?file=/src/App.js) with an example.

Edit. Just wanted to clarify that I am setting `activationContraint: { distance: 5 }` to enable click behavior.

**Comment by clauderic** [comment]
Fixed by rendering the contents of your `SortableItem` within a fragment rather than putting the portal within the sortable element.

https://codesandbox.io/s/dnd-kit-portaled-input-forked-yilzb?file=/src/SortableItem.js

**Comment by apledger** [comment]
That works, thanks for the response.

What about if there was an input instead of the chip? This solution wouldn't work because the desired UX would be for the input itself to be draggable. Is it possible to only prevent the mousedown default only if the activation constraint was met?

**Comment by Avizura** [comment]
Having same problem

**Comment by ranbena** [comment]
I'm having a similar issue. My draggable items have an `<input>` inside, which won't be allowed to focus on user click.
@clauderic it could be great if you could add a config to disable this line (perhaps as a `DndContext` prop?).

In the meantime, I did this dirty hack in my code:
```tsx
// make my own PointerSensor
class PointerSensorWithoutPreventDefault extends PointerSensor {
  static activators = [
    {
      eventName: "onPointerDown" as const,
      handler: ({ nativeEvent }: React.PointerEvent) => {
        if (!nativeEvent.isPrimary || nativeEvent.button !== 0) {
          return false;
        }

        // HACK: comment out prevention 🙀
        // nativeEvent.preventDefault();

        return true;
      },
    },
  ];
}

const sensors = useSensors(
  useSensor(PointerSensorWithoutPreventDefault), // 🎯
);

return (
  <DndContext sensors={sensors}>
    ...
  </DndContext>
);
```

**Comment by imwillhang** [comment]
Thanks so much @ranbena, this is hugely helpful.

@clauderic please please please add this! Without it, anything inside of a draggable item is basically useless.

**Comment by horprogs** [comment]
`onActivate` fixed the issue when you are trying to focus, but if you are trying to select text in the input, draggable items are moving. You could try to select text in the input here (focusing works fine).

![image](https://user-images.githubusercontent.com/14051960/124124279-2791f000-da70-11eb-91dd-f50a1d952fca.png)

**Comment by sampl** [comment]
Just in case this helps anyone else: I just moved the listeners to a drag handle instead of supporting drag on the whole draggable.

See https://docs.dndkit.com/api-documentation/draggable/usedraggable#listeners

Example with comments:

```tsx
function Draggable() {
  const {attributes, listeners, setNodeRef} = useDraggable({
    id: 'unique-id',
  });
  
  return (
    /* setNodeRef makes the top-level div draggable */
    <div ref={setNodeRef}>
      /* Input is inside the draggable element and works fine */
      <input type="text" value={myVal} onChange={...} />
      /* Listeners are on the drag handle, a sibling to the input (not parent) */
      <button {...listeners} {...attributes}>Drag handle</button>
    </div>
  );
}
```

**Comment by windstar20** [comment]
> Just in case this helps anyone else: I just moved the listeners to a drag handle instead of supporting drag on the whole draggable.이것이 다른 사람에게 도움이 될 경우를 대비하여 전체 드래그 가능 항목에 대한 드래그를 지원하는 대신 리스너를 드래그 핸들로 옮겼습니다.
> 
> See https://docs.dndkit.com/api-documentation/draggable/usedraggable#listenershttps://docs.dndkit.com/api-documentation/draggable/usedraggable#listeners를 참조하세요.
> 
> Example with comments: 주석의 예: 
> 
> ```tsx
> function Draggable() {
>   const {attributes, listeners, setNodeRef} = useDraggable({
>     id: 'unique-id',
>   });
>   
>   return (
>     /* setNodeRef makes the top-level div draggable */
>     <div ref={setNodeRef}>
>       /* Input is inside the draggable element and works fine */
>       <input type="text" value={myVal} onChange={...} />
>       /* Listeners are on the drag handle, a sibling to the input (not parent) */
>       <button {...listeners} {...attributes}>Drag handle</button>
>     </div>
>   );
> }
> ```

I had a similar issue while testing a toy program to use the library, and your answer was very helpful. thank you.👍🏼.👍🏼

**Comment by Horsty80** [comment]
I know this issue is close, but, i'm facing same issue, but in my case i don't have a button to use to drag the item.
It's a card with an form inside it, and all the card can be draggable.

How to deals with this ?

Thank

**Comment by owenjs** [comment]
We got around this issue by having restrictions on the sensors, see docs

[https://docs.dndkit.com/api-documentation/sensors#usesensor](https://docs.dndkit.com/api-documentation/sensors#usesensor)

This way for PointerEvents, the user is required to move by 10 pixels before activating the dragging, meaning other PointerEvents trigger before. At least for our setup. Hope this helps others
