### ISSUE TITLE
Problem with DragOverlay position when list was collapsed when user start sort

### ISSUE THREAD

**Issue by khmelevskii** [clauderic/dnd-kit#885]
Please take a look on attached video. For my opinion drag overlay should be close to cursor.

https://user-images.githubusercontent.com/668591/188359090-766100a6-be71-4c0b-8bac-33bcb0861dd7.mov

**Comment by psd-coder** [comment]
You can try to override `y` coordinate by using custom modifier in your `DndContext`:

```
import { getEventCoordinates } from '@dnd-kit/utilities'

const followMouseModifier: Modifier = ({ activatorEvent, draggingNodeRect, transform }) => {
  if (draggingNodeRect && activatorEvent) {
    const activatorCoordinates = getEventCoordinates(activatorEvent)

    if (!activatorCoordinates) {
      return transform
    }

    const offsetY = activatorCoordinates.y - draggingNodeRect.top

    return {
      ...transform,
      y: transform.y + offsetY - draggingNodeRect.height / 2,
    }
  }

  return transform
}
```

And then use it this way: `<DndContext modifiers={[restrictToVerticalAxis]}>...</DndContext>`

**Comment by khmelevskii** [comment]
It works perfectly! Thank you for awesome library @psd-coder !
