### ISSUE TITLE
autoScroll triggering infinite scroll

### ISSUE THREAD

**Issue by arananegra** [clauderic/dnd-kit#891]
Hi! A couple of users have warned about a bug that causes the page to keep stuck in an infinite scroll. 

It happens when you have a list large enough to enable the scroll, then you pick and move an item to place it on top of the grid. If you drop that element without stopping the autoscrolling in the page, then the scroll won't stop unless you reload the page.

I don't know if it has to do with the configuration of the library. I've disabled the autoScroll while this gets fixed but is a nice to have feature I would feel sad to lose. 

This is the sandbox: https://codesandbox.io/s/hardcore-hodgkin-78t0tu?file=/src/App.tsx

Here is a video showing what happens (you can sort the elements if you wait till the autoScroll ends):

https://user-images.githubusercontent.com/14930496/191275405-79ccfef3-579c-4371-9917-8c8e98cda3b9.mp4

Thank you for your help!

**Comment by OmarOmeiri** [comment]
Yes! I'm having the exact the same issue. After some hours of digging, I gave up and set autoScroll to `false` as well. But this it is a huge impact on UX. I hope someone takes a look at this.

**Comment by ytamir** [comment]
This is a serious issue I am encountering as well 

+ Bump +

**Comment by EnzoLtzyWeb** [comment]
Hello, 
I got the same issue there, did you find any solution that doesn't force to set autoScroll to false ?

I used to have it working well, but it suddenly stopped working ....

Have a great day !

**Comment by arananegra** [comment]
Hi all, I think the problem is having a wrapper component (the one from line 279) and using it on line 347. Can you give it a try? At least in my code seems to be root of the problem

**Comment by wibed** [comment]
https://github.com/clauderic/dnd-kit/pull/140


with these changes, infinite scrolling has been fixed for me

**Comment by arananegra** [comment]
I've tried to bump all the dnd-kit dependencies and the issue is still reproducible in the codesandbox

**Comment by anfinil** [comment]
The same issue

**Comment by veecam** [comment]
Make sure that your DndContext or it's parent component is defined outside a component.
Otherwise DndContext will be unmount and mount again, the intervalRef in useInterfal will be reset, and the AutoScroll won't stop.

**Comment by anfinil** [comment]
> Make sure that your DndContext or it's parent component is defined outside a component. Otherwise DndContext will be unmount and mount again, the intervalRef in useInterval will be reset, and the AutoScroll won't stop.
> 
> Don't do this:
> 
> ```js
> const SomeComponent = () => {
>   const Container = () => <DndContext />;
>   return <Container />;
> }
> ```
> 
> Change to:
> 
> ```js
> const Container = () => <DndContext />;
> const SomeComponent = () => <Container />;
> ```

Thanks, it works.

**Comment by zaidoooo** [comment]
any solution to this? facing similar issue like the OP sandbox

**Comment by wangqiaoling01** [comment]
any solution to this? facing similar issue like the OP sandbox. Help~~

**Comment by veecam** [comment]
> any solution to this? facing similar issue like the OP sandbox. Help~~

https://codesandbox.io/s/magical-rgb-2srcfs?file=/src/App.tsx

Do not let the DndContext been remounted.

**Comment by veecam** [comment]
> any solution to this? facing similar issue like the OP sandbox. Help~~

他那个演示代码里， DndContext写在SortableList这个组件内部， SortableList组件写在App内部， 导致每次setImages的时候，SortableList会被卸载、加载，DndContext也跟着一起被卸载、加载了。

要么把SortableList组件useMemo一下， 要么把组件定义在App组件外部，要么在App里直接用DndContext，总之`<<<不要让DndContext被重载>>>`。

这问题几乎都是该原因导致的。

**Comment by wangqiaoling01** [comment]
> > any solution to this? facing similar issue like the OP sandbox. Help~~
> 
> 他那个演示代码里， DndContext写在SortableList这个组件内部， SortableList组件写在App内部， 导致每次setImages的时候，SortableList会被卸载、加载，DndContext也跟着一起被卸载、加载了。
> 
> 要么把SortableList组件useMemo一下， 要么把组件定义在App组件外部，要么在App里直接用DndContext，总之`<<<不要让DndContext被重载>>>`。
> 
> 这问题几乎都是该原因导致的。

好使！！

**Comment by arananegra** [comment]
I'll close this as it is already solved (https://github.com/clauderic/dnd-kit/issues/891#issuecomment-1521176036 or https://github.com/clauderic/dnd-kit/issues/891#issuecomment-1344435200)
