### ISSUE TITLE
Crazy scroll in parent

### ISSUE THREAD

**Issue by wilav-dev** [clauderic/dnd-kit#911]
Hello, I have a Dialog with a scrollable content, and when dragging fast, the dialog scroll gets crazy. Any Idea?

collisionDetection: closestCenter
modifiers: [restrictToParentElement, restrictToFirstScrollableAncestor, restrictToVerticalAxis]
strategy: verticalListSortingStrategy

https://user-images.githubusercontent.com/71793326/195196547-a41a698d-e0ff-4877-95ce-3e43eefc67af.mov

**Comment by EnzoLtzyWeb** [comment]
Hello, 
I got the same issue there, did you find any solution ?

Have a great day !

**Comment by iamjoshua** [comment]
Is there any particular reason why this issue was closed? I'm seeing this same erratic scroll behavior with a bare-bones implementation.

**Comment by WinterSir** [comment]
hi,
I got the same issue there, did you find any solution ?
thank you！
