### ISSUE TITLE
Expose recomputeLayouts via imperative handle on DndContext

### ISSUE THREAD

**Issue by aartrost** [clauderic/dnd-kit#92]
Hi Claudéric,

First off I'd like to thank you for the amazing work on this library. It's an absolutely massive improvement over anything else out there and it's been a joy to use.

As for my question: I'm working on a sortable list that needs to dynamically move margin based on the position of the dragged item. Kind of like the [margin between items](https://5fc05e08a4a65d0021ae0bf2-zditmhymjz.chromatic.com/?path=/story/presets-sortable-vertical--margin-between-items) storybook example but instead of the margin staying in the same position it shifts along with the dragged item. Is something like that possible? I found that DndContext contains a `recomputeLayouts` method, but I haven't found a way of accessing that from my implementation. 

Thanks in advance for your time!

**Comment by clauderic** [comment]
Hey @aartrost, if the code where you need to recompute layouts is wrapped within a `<DndContext>` provider in the tree, then as you mentioned, you can use the `useDndContext()` hook to call the `recomputeLayouts` method.

Assuming you need to do this from the outside (for example, in the component that renders the `<DndContext>` component, right now you would not be able to, but it should be a fairly straightforward PR to expose this via an imperative handle exposed through the ref of `<DndContext>` (see https://reactjs.org/docs/hooks-reference.html#useimperativehandle)

**Comment by aartrost** [comment]
Hi @clauderic! 

Thank you for the hint, I was using the `recomputeLayouts` method outside the `<DndContext>` provider. Moving it inside fixed the issue for me. Your quick reply is much appreciated! 

I'll leave this issue open as being able to call this from outside the provider tree would likely be helpful for others.

**Comment by clauderic** [comment]
Closing this issue as I no longer have plans to expose this outside of `DndContext`
