### ISSUE TITLE
Collision detection with border radius

### ISSUE THREAD

**Issue by Mario-Eis** [clauderic/dnd-kit#922]
We use circular drop regions. But the collision detection algorithms rectIntersection and pointerWithin only detect intersections with the full rectangle, ignoring the border radius. I did not find this mentioned in the documentation. Is there a way to respect the border radius? Is this possibly a bug?

**Comment by Saturate** [comment]
You can create a custom detection if needed, would that fit you?

**Comment by clauderic** [comment]
Refer to the [Building custom collision detection algorithms
](https://docs.dndkit.com/api-documentation/context-provider/collision-detection-algorithms#building-custom-collision-detection-algorithms) section of the docs
