### ISSUE TITLE
It covers and prevent my original click on a button

### ISSUE THREAD

**Issue by hilmanski** [clauderic/dnd-kit#923]
I have a PDF pages like this.

![Screen Shot 2022-10-28 at 16 47 31](https://user-images.githubusercontent.com/4522467/198545761-8992016e-d5e1-46cb-bc16-4fc1f37cf2e7.png)

When we hover it shows a toolbar that I can click. But implementing dnd-kit, make the toolbar button not clickable. (It keep triggering onDragEnd(), even though I just click not dragging.

So maybe what I want is the toolbar become a non-draggable area. Even though the div parent covers it. 

Other question: why clicking triggering onDragEnd, can we turn this behavior off?

**Comment by hilmanski** [comment]
This is how I solve it.
by changing the distance of the sensor

const mouseSensor = useSensor(MouseSensor, {
        activationConstraint: {
            distance: 25
        },
    });
    
    const sensors = useSensors(
        mouseSensor,
    );

**Comment by SilentFlute** [comment]
oh dude, that's awesome, i met the same question, at a loss for words, i found this issue, and it worked, thx a lot :)

**Comment by hilmanski** [comment]
> oh dude, that's awesome, i met the same question, at a loss for words, i found this issue, and it worked, thx a lot :)

happy to help. Happened to me many times as well, just paying it forward. 
dev is amazing!

**Comment by SilentFlute** [comment]
hhh, dev is amazing, indeed for sure
