### ISSUE TITLE
Items dragged within a sortable grid are not properly moving according to widths

### ISSUE THREAD

**Issue by dilizarov** [clauderic/dnd-kit#93]
https://share.getcloudapp.com/yAu6ymWD

In the above, you'll notice that the calculations seem off. I'm not sure if I'm supposed to be calculating any widths and passing them to the library or if the library should be smartly moving these elements around according to their widths.

The elements are `inline-block` elements.

Also, I noticed that when I leverage `transform: translate3d...` CSS that you can noticeably see that the font styling changes... to avoid this, I instead just move them around with `top/left` CSS.

**Comment by clauderic** [comment]
Your layout is not predictable, so you'll need to follow the same strategy outlined here https://github.com/clauderic/dnd-kit/issues/44#issuecomment-757312037 or here https://github.com/clauderic/dnd-kit/issues/44#issuecomment-757324165

**Comment by dilizarov** [comment]
Oh cool. Thanks, @clauderic.

I implemented the `onDragOver` and there is only 1 more quirk and I'm curious what might be causing it:

https://share.getcloudapp.com/Qwu92XxX

Basically, sometimes the over element shifts just a tad bit... and doesn't fully swap with the active element while previewing the drag. Towards the end of the video, you'll see that while the swap wasn't fully done on preview, the when the drag is finished the active element actually switches positions with the over element.

**Comment by clauderic** [comment]
Did you set the `sortingStrategy` to a no-op? 

```js
function disableSortingStrategy() {
  return null;
}

<SortableContext strategy={disableSortingStrategy}>
```

**Comment by dilizarov** [comment]
Aha! I don't think I saw that in your example and thought that `onDragOver` must magically disable or override sorting. Big derp on my part. I think everything works!

I disabled the keyboard sensor because I don't care for it right now, but I did notice something that might either point to some bug in the library or my code.

https://share.getcloudapp.com/yAu60BmX

Essentially it seems like the DragOverlay maybe doesn't properly follow the underlying element. In truth, it almost feels like for keyboard purposes, the DragOverlay isn't even needed so I wonder if there is a way for me to detect the overlay and remove it when in keyboard mode.

If you watch enough of the video though, you'll notice that the keyboard mode sometimes kinda loses track of where it is and the item swaps start making little visual sense (wrong elements being swapped).

Again, cheers and thanks so much.

**Comment by dilizarov** [comment]
@clauderic Discovered another bug. I think `SortableContext` is keeping an internal reference of the items and doesn't update that internal reference even if the items prop passed in changes.

This is important in cases like the below video when I delete tags after rearranging them. You should notice strange behavior.

I provide my quick fix at the bottom (assuming one does not care for animation).

https://share.getcloudapp.com/ApuREoKr

Basically, in the above, when an item gets dragged, that state of `items` gets saved until the next time an item is dragged. This means when you are deleting tags like I do in the above, you'll notice the animation gets rather wonky. It continues animating the elements to their new location from where it last remembers drag events settling all the items.

If I drag again, this new state of items gets saved and you'll notice the animation changes, but again gets wonky over time.

If I disable the animations, you notice flickers of the incorrect `items` whenever an item is deleted.

I solve this by doing this:

```jsx
<SortableContext key={tags.length} items={tags} strategy={noop}>
   {...}
</SortableContext>
```

The `key={tags.length}` basically mounts a new SortableContext. While this isn't most ideal, it at least solves the flickering/animation bug because it ensures `items` is always fresh and updated upon change in item count.
