### ISSUE TITLE
Disappearing draggables in useDraggable example docs tab

### ISSUE THREAD

**Issue by sampl** [clauderic/dnd-kit#99]
When dragging some of the examples, the draggable item seems to disappear when dragged. It looks like it's going to the very bottom of its parent?

https://5fc05e08a4a65d0021ae0bf2-zditmhymjz.chromatic.com/?path=/docs/core-draggable-hooks-usedraggable--basic-setup

- It's only in the "docs" tab, not the "canvas" tab
- The first example works fine ("Basic Setup"), only subsequent examples seem to break (after "Drag Handle")
- It may only be on the useDraggable examples, not the others

Loom video: https://www.loom.com/share/e23adf550caf4b84b6a5be4e217bfda7

Mac OS, Chrome

Just adding as I see 'em, let me know if this is a known issue or a dupe :)

**Comment by clauderic** [comment]
Very odd, will investigate.
