### ISSUE TITLE
Dragging over a in a sortable context creates dupes, if there already is a item

### ISSUE THREAD

**Issue by stauersbol** [clauderic/dnd-kit#991]
Sometimes when I drag over a item it creates a bunch of dupes.
Now I have nailed the problem down to either being the collision strategy I'm using or it is a problem with my handleDragOver function.
Either way as soon as a certain thing fails it just creates 2-3 extras of that said item.

Video shows the issue I have(the screenrecorder is not the best hence why the mouse looks offset).

If you need any code for reference, I can post so you can see.

EDIT: Could it be because I'm using the Context API to store the state of the boxes? If so I might need to swap it out for a different state handler.

EDIT 2: I have no idea if it was because I had a .sort on the array in the `arrayMove` function. Right now the issue seems to be fixed as is.

https://user-images.githubusercontent.com/9026132/210975235-d009031b-76ff-4a26-934e-b5151aad9644.mp4

**Comment by stauersbol** [comment]
Issue solved.

What fixed it:

Don't have a .sort in the `arrayMove()` function.

**Comment by stauersbol** [comment]
Issue still persist.

As of writing, handleDragOver for me is very buggy.

**Comment by stauersbol** [comment]
```ts
    const handleDragOver = ({ active, over }: any) => {
        const { id } = active;
        const overChute = over?.id;

        if (!overChute || active.id in items) {
            return;
        }

        // Find the containers
        const activeContainer = findContainer(id);
        const overContainer = findContainer(overChute);
        if (
            !activeContainer ||
            !overContainer ||
            activeContainer === overContainer
        ) {
            return;
        }

        setItems((chutes) => {
            const activeItems = chutes[activeContainer];
            const overItems = chutes[overContainer];

            // Find the indexes for the items
            const activeIndex = activeItems.indexOf(id);
            const overIndex = overItems.indexOf(overChute);

            let newIndex: number;

            // BUG Error trail for duplicate items start here.
            /**
             * What I believe is wrong with this is due to my way of changing state.
             * This could be either because of the if function here or
             * The way I use Context API to handle my state globally.
             */
            if (chutes.hasOwnProperty(overChute)) {
                // We're at the root droppable of a container
                console.log("overChute here is:", overChute);
                newIndex = overItems.length + 1;
            } else {
                console.log("overChute here is:", overChute);
                const insertAfterLastItem: number =
                    over &&
                    overIndex === overItems.length - 1 &&
                    active.rect.current.translated &&
                    active.rect.current.translated.offsetLeft >
                    over.rect.offsetLeft + over.rect.width;

                const modifier: number = insertAfterLastItem ? 1 : 0;

                newIndex = overIndex >= 0 ? overIndex + modifier : overItems.length + 1;
            }

            return {
                ...chutes,
                [activeContainer]: [
                    ...chutes[activeContainer].filter((item) => item !== active.id),
                ],
                [overContainer]: [
                    ...chutes[overContainer].slice(0, newIndex),
                    items[activeContainer][activeIndex],
                    ...chutes[overContainer].slice(newIndex, chutes[overContainer].length),
                ],
            };
        });
    }
```

This is how I handle whenever I drag over something.

**Comment by stauersbol** [comment]
```ts

            return {
                ...chutes,
                [activeContainer]: [
                    ...chutes[activeContainer].filter((item) => item !== active.id),
                ],
                [overContainer]: [
                    ...overItems,
                    items[activeContainer][activeIndex],
                ],
            };
```

Solved this by doing this.

**Comment by cc-ww** [comment]
change opacity to 0

const SortableListItem = ({ itemKey, children }: { itemKey: number; children: React.ReactNode }) => {
    const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id: itemKey });

    const style = {
        transform: CSS.Transform.toString(transform),
        transition,
        opacity: isDragging ? 0 : 1, // 👈 change here
        height: 47, // 
        display: 'flex',
        alignItems: 'center',
        background: '#fff',
        borderBottom: '1px solid #f0f0f0',
        padding: '0 12px',
    };

    return (
        <div ref={setNodeRef} style={style} {...attributes} {...listeners}>
            {children}
        </div>
    );
